### ISSUE TITLE
Python 3 compatibility for Kodi 19

### ISSUE THREAD

**Issue by davidheitman** [croneter/PlexKodiConnect#1074]
The upcoming Kodi 19, now in alpha, requires plugins be converted to python 3.  Obviously alpha 1 is a long way from release, but this will be a major breaking change.  I've started the process with a quick-and-dirty run of 2to3 to catch the obvious changes such as library names and the like.  That gets us as far as:
`2019-12-03 13:43:56.603 T:44291   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'TypeError'>
                                            Error Contents: argument should be integer or bytes-like object, not 'str'
                                            Traceback (most recent call last):
                                              File "/home/loucipher/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 8, in <module>
                                                service_entry.start()
                                              File "/home/loucipher/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 578, in start
                                                LOG.info("Delaying Plex startup by: %s sec...", DELAY)
                                              File "/usr/lib/python3.7/logging/__init__.py", line 1378, in info
                                                self._log(INFO, msg, args, **kwargs)
                                              File "/usr/lib/python3.7/logging/__init__.py", line 1514, in _log
                                                self.handle(record)
                                              File "/usr/lib/python3.7/logging/__init__.py", line 1524, in handle
                                                self.callHandlers(record)
                                              File "/usr/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
                                                hdlr.handle(record)
                                              File "/usr/lib/python3.7/logging/__init__.py", line 894, in handle
                                                self.emit(record)
                                              File "/home/loucipher/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/loghandler.py", line 47, in emit
                                                xbmc.log(self.format(record), level=LEVELS[record.levelno])
                                              File "/usr/lib/python3.7/logging/__init__.py", line 869, in format
                                                return fmt.format(record)
                                              File "/usr/lib/python3.7/logging/__init__.py", line 609, in format
                                                if self.usesTime():
                                              File "/usr/lib/python3.7/logging/__init__.py", line 577, in usesTime
                                                return self._style.usesTime()
                                              File "/usr/lib/python3.7/logging/__init__.py", line 419, in usesTime
                                                return self._fmt.find(self.asctime_search) >= 0
                                            TypeError: argument should be integer or bytes-like object, not 'str'
                                            -->End of Python script error report<--`
I'll continue to work on this as time permits, but wanted to bring it up.  I have a branch up here: https://github.com/davidheitman/PlexKodiConnect/tree/2to3

**Comment by davidheitman** [comment]
Most of the issues have been down to python2's str/unicode vs python3's bytes/str differences.  I've fixed most of that, currently getting WebSocketTimeoutExceptions.  Calling it for the day, but the branch I linked in my first post is getting progressively closer to python3.  I won't claim it's elegant, but it's a good start.

**Comment by croneter** [comment]
Thanks a lot for your efforts!

Please make a pull request from your branch to beta-version here. We can then use that PR for this discussion reviews, etc

Since it's unclear when Kodi 19 Matrix hits, my goal is to make PKC compatible to BOTH Python 2 and 3. Unfortunately, your code won't run on Python 2 anymore. See here: https://python-future.org/compatible_idioms.html

**Comment by davidheitman** [comment]
Ah, good point, I didn't really give much thought to backward compatibility.  Not sure how that will work, since some of the module names have changed between the two (like "Queue" becoming "queue").  Can't say as I've ever looked into maintaining backward compatibility in that scenario.

**Comment by croneter** [comment]
'''
if VERSION == 2:
   import queue as _queue
else:
    import Queue as _queue

...

my_queue = _queue.Queue()
'''

**Comment by croneter** [comment]
Closing this issue. Please make a Pull Request from your branch towards the `beta-version` branch if you'd like to make the switch from Python 2 to Python 3!

**Comment by davidheitman** [comment]
Opened a draft PR, https://github.com/croneter/PlexKodiConnect/pull/1088
Needs work, I haven't had time to work on it any further, and of course there's the backward compatibility with python 2 issue.  Might not be able to do much more on this until after the holidays.
