### ISSUE TITLE
Error encountered:  - u'type'

### ISSUE THREAD

**Issue by rajil** [croneter/PlexKodiConnect#1110]
Hello,
PKC shows up syncing on the screen, but the media file do not appear in Kodi. If i try to browse to the media folder PKC gives an error,

```
2020-02-14 09:54:35.682 T:139815169271552   ERROR: PLEX.utils: Error encountered:  - u'type'
2020-02-14 09:54:35.684 T:139815169271552   ERROR: Previous line repeats 2 times.
2020-02-14 09:54:35.684 T:139815169271552   ERROR: PLEX.utils: _____________________________________________________________
2020-02-14 09:54:35.684 T:139815169271552   ERROR: PLEX.utils:     Traceback (most recent call last):
2020-02-14 09:54:35.684 T:139815169271552   ERROR: PLEX.utils:       File "/home/user/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/widgets.py", line 280, in prepare_listitem
2020-02-14 09:54:35.684 T:139815169271552   ERROR: PLEX.utils:         if item['type'] == "album" and 'album' not in item and 'label' in item:
2020-02-14 09:54:35.684 T:139815202842368   ERROR: PLEX.utils: _____________________________________________________________
2020-02-14 09:54:35.684 T:139815202842368   ERROR: PLEX.utils:     Traceback (most recent call last):
2020-02-14 09:54:35.684 T:139815194449664   ERROR: PLEX.utils: _____________________________________________________________
2020-02-14 09:54:35.685 T:139815169271552   ERROR: PLEX.utils:     KeyError: u'type'
2020-02-14 09:54:35.685 T:139815202842368   ERROR: PLEX.utils:       File "/home/user/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/widgets.py", line 280, in prepare_listitem
2020-02-14 09:54:35.685 T:139815194449664   ERROR: PLEX.utils:     Traceback (most recent call last):
2020-02-14 09:54:35.685 T:139815169271552   ERROR: PLEX.utils: _____________________________________________________________
2020-02-14 09:54:35.685 T:139815202842368   ERROR: PLEX.utils:         if item['type'] == "album" and 'album' not in item and 'label' in item:
2020-02-14 09:54:35.685 T:139815194449664   ERROR: PLEX.utils:       File "/home/user/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/widgets.py", line 280, in prepare_listitem
2020-02-14 09:54:35.685 T:139815169271552   ERROR: PLEX.widget: item that caused crash: {u'artist': [], u'file': u'plugin://plugin.video.plexkodiconnect.movies/?plex_id=4614&plex_type=movie&mode=play&filename=SomeName (2016).mkv', u'icon': u'DefaultMovies.png'}
2020-02-14 09:54:35.685 T:139815202842368   ERROR: PLEX.utils:     KeyError: u'type'
2020-02-14 09:54:35.686 T:139815194449664   ERROR: PLEX.utils:         if item['type'] == "album" and 'album' not in item and 'label' in item:
2020-02-14 09:54:35.686 T:139815202842368   ERROR: PLEX.utils: _____________________________________________________________
2020-02-14 09:54:35.686 T:139815194449664   ERROR: PLEX.utils:     KeyError: u'type'
2020-02-14 09:54:35.686 T:139815194449664   ERROR: PLEX.utils: _____________________________________________________________
2020-02-14 09:54:35.686 T:139815194449664   ERROR: PLEX.widget: item that caused crash: {u'artist': [], u'file': u'plugin://plugin.video.plexkodiconnect.movies/?plex_id=7439&plex_type=movie&mode=play&filename=Some Name1 (2018) Bluray-1080p.mkv', u'icon': u'DefaultMovies.png'}
2020-02-14 09:54:35.686 T:139815202842368   ERROR: PLEX.widget: item that caused crash: {u'artist': [], u'file': u'plugin://plugin.video.plexkodiconnect.movies/?plex_id=7288&plex_type=movie&mode=play&filename=Some Name (2019) WEBDL-2160p.mkv', u'icon': u'DefaultMovies.png'}

```

**Comment by croneter** [comment]
I need the entire DEBUG log please, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by rajil** [comment]
I think i may have found the issue. I was using mysql server with advancedsettings.xml. As soon i disabled that PKC started to work correctly.

**Comment by croneter** [comment]
MySQL does **NOT** work with PlexKodiConnect. PKC replaces MySQL 😉
