### ISSUE TITLE
Sync fails: Python int too large for SQL integer

### ISSUE THREAD

**Issue by toth0attila** [croneter/PlexKodiConnect#1176]
Plexkodiconnect sync failed when syncing plex database the error message:
pyton int too large for SQL interger

I take a look into plex databes, and i realize that from at time plex stat to give metadata id length from 6 to 10. maybe that is a problem.
![image](https://user-images.githubusercontent.com/47054006/81894963-5f5e7f80-95b1-11ea-9383-68f9cea91f9c.png)

i check that at a smaller library section (5 item only), which contains 6 lenght and 10 lenght too.
sync fail at the item with lenght 10.

Please give advice what to do with that.

thanks for your great work.
A.

**Comment by croneter** [comment]
Theoretically, the Plex id should be able to up to 9223372036854775807. Please share your entire Kodi DEBUG log file when PKC throws this error, according to https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
My guess is that you somehow botched the Plex database so it'll return a Plex ID that is WAY too high. Try to somehow reset the Plex DB (without losing your watched statuses, resume points, ratings as well as manually set artwork, etc.). E.g.
* https://support.plex.tv/articles/201154527-move-viewstate-ratings-from-one-install-to-another/
* https://support.plex.tv/articles/201100678-repair-a-corrupt-database/    
Do make a backup of your Plex DB before you start messing around!

**Comment by toth0attila** [comment]
Thanks, for your quick reply!
I will try it, and let you know, what is the result.

**Comment by toth0attila** [comment]
I make a repair process, but the error is the same.
I attach the log.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/4627199/kodi.log)

error in the line 959 for example.

**Comment by croneter** [comment]
Offending log lines:
```
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 119045 - Inside Ikea
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 114856 - GRAND PRIX Driver
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 119150 - Borbás Marcsi Szakácskönyve
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 114928 - Kinn az orosz vadonban
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 120872 - A Duna, Európa Gyöngyszeme
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 119159 - Inside Internet
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 120563 - Our Planet
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 120383 - Planet Earth
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 120884 - Vad Afrika Az élet Folyói S01
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 120893 - One Strange Rock
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 123794 - Seven Worlds, One Planet
2020-05-14 10:59:39.698 T:15176   DEBUG: PLEX.sync.full_sync: Put section in queue with 102 items: {'index': 2, 'name': 'Doku Sorozatok', 'section_id': 32, 'section_type': 'show', 'sync_to_kodi': True, 'last_sync': None}
2020-05-14 10:59:39.699 T:9904   DEBUG: PLEX.sync.fill_metadata_queue: Process section {'index': 2, 'name': 'Doku Sorozatok', 'section_id': 32, 'section_type': 'show', 'sync_to_kodi': True, 'last_sync': None} with 102 items
NOTICE: PLEX.sync.full_sync: User chose to not sync section {'index': 7, 'name': 'TV Shows', 'section_id': 1, 'section_type': 'show', 'sync_to_kodi': False, 'last_sync': None}
2020-05-14 10:59:39.699 T:15176   DEBUG: PLEX.sync.full_sync: Exiting threaded_get_generators
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 123858 - Our Planet (2019)
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 120905 - Planet Earth II
2020-05-14 10:59:39.701 T:9904   DEBUG: PLEX.sync.fill_metadata_queue: Put section in queue with 102 items: {'index': 2, 'name': 'Doku Sorozatok', 'section_id': 32, 'section_type': 'show', 'sync_to_kodi': True, 'last_sync': None}
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 121566 - Wild China
NOTICE: PLEX.tvshows: ADD tvshow plex_id: 1879048330 - Night on Earth
ERROR: PLEX.sync: Exception encountered: Python int too large to convert to SQLite INTEGER
ERROR: PLEX.utils: Error encountered:  - Python int too large to convert to SQLite INTEGER
ERROR: PLEX.utils: _____________________________________________________________
ERROR: PLEX.utils:     Traceback (most recent call last):
ERROR: PLEX.utils:       File "C:\Users\toth0\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\common.py", line 32, in run
ERROR: PLEX.utils:         self._run()
ERROR: PLEX.utils:       File "C:\Users\toth0\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\process_metadata.py", line 85, in _run
ERROR: PLEX.utils:         children=item['children'])
ERROR: PLEX.utils:       File "C:\Users\toth0\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes\tvshows.py", line 282, in add_update
ERROR: PLEX.utils:         last_sync=self.last_sync)
ERROR: PLEX.utils:       File "C:\Users\toth0\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\plex_db\tvshows.py", line 31, in add_show
ERROR: PLEX.utils:         last_sync))
ERROR: PLEX.utils:     OverflowError: Python int too large to convert to SQLite INTEGER
ERROR: PLEX.utils: _____________________________________________________________
```
`1879048330` is WAY larger than the last shows id 121566. But it should still go through, not sure yet why not

**Comment by toth0attila** [comment]
hello!

I fix my plex database, and work like a charm.
So this ticket can be closed.
Thanks,
A.
