### ISSUE TITLE
Playback occasionally fails in Windows

### ISSUE THREAD

**Issue by pbankovic** [croneter/PlexKodiConnect#1210]
Playback fails on some movies in Windows, while it works in Linux always. After some investigation, I figured out that it happens when there is a cyrillic subtitle present within a movie, and it seems to fail while trying to download it to the temp directory.
Below is a fragment of the log file which shows where it breaks.

> DEBUG: PLEX.api: Writing temp subtitle to C:\Users\XXXX\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.plexkodiconnect\temp\English (SRT External)_01.srt
2020-08-18 21:52:24.966 T:1640   DEBUG: PLEX.api: Writing temp subtitle to C:\Users\XXXX\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.plexkodiconnect\temp\hrvatski (SRT External)_01.srt
2020-08-18 21:52:24.976 T:1640   DEBUG: PLEX.api: Writing temp subtitle to C:\Users\XXXX\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.plexkodiconnect\temp\српски језик (SRT External)_00.srt
2020-08-18 21:52:24.977 T:1640   ERROR: PLEX.utils: Error encountered:  - [Errno 22] invalid mode ('wb') or filename: 'C:\\Users\\XXXX\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.plexkodiconnect\\temp\\?????? ????? (SRT External)_00.srt'
2020-08-18 21:52:24.977 T:1640   ERROR: PLEX.utils: _____________________________________________________________
2020-08-18 21:52:24.977 T:1640   ERROR: PLEX.utils:     Traceback (most recent call last):
2020-08-18 21:52:24.977 T:1640   ERROR: PLEX.utils:       File "C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\backgroundthread.py", line 362, in _runTask
2020-08-18 21:52:24.977 T:1640   ERROR: PLEX.utils:         task._run()
2020-08-18 21:52:24.977 T:1640   ERROR: PLEX.utils:       File "C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\backgroundthread.py", line 296, in _run
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:         self.run()
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:       File "C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\playback_starter.py", line 48, in run
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:         resume=resume)
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:       File "C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\playback.py", line 47, in playback_triage
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:         _playback_triage(plex_id, plex_type, path, resolve, resume)
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:       File "C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\playback.py", line 136, in _playback_triage
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:         _conclude_playback(playqueue, pos)
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:       File "C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\playback.py", line 467, in _conclude_playback
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:         listitem.setSubtitles(api.cache_external_subs())
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:       File "C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\plex_api\media.py", line 267, in cache_external_subs
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:         stream.get('codec'))
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:       File "C:\Users\XXXX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\plex_api\media.py", line 292, in download_external_subtitles
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:         with open(path_ops.encode_path(path), 'wb') as f:
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils:     IOError: [Errno 22] invalid mode ('wb') or filename: 'C:\\Users\\XXXX\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.plexkodiconnect\\temp\\?????? ????? (SRT External)_00.srt'
2020-08-18 21:52:24.978 T:1640   ERROR: PLEX.utils: _____________________________________________________________

**Comment by croneter** [comment]
As always- share your entire debug log file please, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Could you also share the subtitle file in question, if possible? Just "drop" it here when replying

**Comment by pbankovic** [comment]
Sure

https://pastebin.com/LsSxVsy8

I had to rename the subtitle file from .srt to .txt, because github rejected the .srt

[The NeverEnding Story (1984).sr.txt](https://github.com/croneter/PlexKodiConnect/files/5097190/The.NeverEnding.Story.1984.sr.txt)

**Comment by croneter** [comment]
Thanks a lot for reporting this! PKC version 2.12.3 should fix this issue. Please let me know here if this is not the case.

**Comment by pbankovic** [comment]
I confirm this has been fixed ;)
@croneter thanks for the effort, it is very appreciated :)
