### ISSUE TITLE
Playback progress report back to the PMS suddenly not working anymore

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#1246]
```
2020-12-15 21:35:11.439 T:1224700800  NOTICE: PLEX.plex_companion: ----===## Plex Companion stopped ##===----
2020-12-15 21:35:11.446 T:1224700800   ERROR: Exception in thread Thread-4:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_companion.py", line 261, in run
                                                self._run()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_companion.py", line 356, in _run
                                                self._process_tasks(task)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_companion.py", line 245, in _process_tasks
                                                self._process_playlist(data)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_companion.py", line 151, in _process_playlist
                                                _, container_key, query = PF.ParseContainerKey(data['containerKey'])
                                            KeyError: u'containerKey'
```

**Comment by croneter** [comment]
Hopefully fixed in [PKC **beta** version 2.12.5](https://github.com/croneter/PlexKodiConnect/releases/tag/2.12.5)
