### ISSUE TITLE
Local variable 'user' referenced before assignement

### ISSUE THREAD

**Issue by Kakunas** [croneter/PlexKodiConnect#1276]
Since 2.12.8 i have the problem at the logon to the Plex Server with the fault 
Local variable 'user' referenced before assignement

In 2.12.6 everything works fine. 

Plex Server is self hosted at a Qnap. Public in my own network with no special user.
Kodi 18.9 is also used.
Reproduced at 3 devices with Kodi Windows Store App and RPI4 with LibreElec

Error Lines from the log

2021-01-11 18:43:08.999 T:5368   ERROR: PLEX.utils: Error encountered:  - local variable 'user' referenced before assignment
2021-01-11 18:43:09.002 T:5368   ERROR: PLEX.utils: _____________________________________________________________
2021-01-11 18:43:09.003 T:5368   ERROR: PLEX.utils:     Traceback (most recent call last):
2021-01-11 18:43:09.003 T:5368   ERROR: PLEX.utils:       File "C:\Users\peter\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\backgroundthread.py", line 362, in _runTask
2021-01-11 18:43:09.003 T:5368   ERROR: PLEX.utils:         task._run()
2021-01-11 18:43:09.003 T:5368   ERROR: PLEX.utils:       File "C:\Users\peter\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\backgroundthread.py", line 296, in _run
2021-01-11 18:43:09.003 T:5368   ERROR: PLEX.utils:         self.run()
2021-01-11 18:43:09.003 T:5368   ERROR: PLEX.utils:       File "C:\Users\peter\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\backgroundthread.py", line 326, in run
2021-01-11 18:43:09.003 T:5368   ERROR: PLEX.utils:         result = self._function(*self._args, **self._kwargs)
2021-01-11 18:43:09.003 T:5368   ERROR: PLEX.utils:       File "C:\Users\peter\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\service_entry.py", line 246, in authenticate
2021-01-11 18:43:09.004 T:5368   ERROR: PLEX.utils:         if self._do_auth():
2021-01-11 18:43:09.004 T:8868   DEBUG: PLEX.kodimonitor: PKC settings change detected
2021-01-11 18:43:09.004 T:5368   ERROR: PLEX.utils:       File "C:\Users\peter\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\service_entry.py", line 420, in _do_auth
2021-01-11 18:43:09.005 T:8868   DEBUG: PLEX.kodimonitor: PKC settings change detected
2021-01-11 18:43:09.005 T:5368   ERROR: PLEX.utils:         'true' if user.isManaged else 'false')
2021-01-11 18:43:09.006 T:8868   DEBUG: PLEX.kodimonitor: PKC settings change detected
2021-01-11 18:43:09.006 T:5368   ERROR: PLEX.utils:     UnboundLocalError: local variable 'user' referenced before assignment
2021-01-11 18:43:09.006 T:5368   ERROR: PLEX.utils: _____________________________________________________________

**Comment by croneter** [comment]
Ups, sorry for that 😞 . And thanks a lot for reporting! Version 2.12.9 out now, should fix this.
