### ISSUE TITLE
Error encountered:  - u'game'

### ISSUE THREAD

**Issue by TATUMTOT** [croneter/PlexKodiConnect#1326]
ok looks like this might have started on the First. of the month. 

Not sure why but nothing new is syncing to the internal Kodi DB. Thought it might have been related to a PMS update but when I rolled back to before we noticed this same issue.  

I even install everything on a new PC and had the same issue. If we navigate throught the plugin stuff shows up like the updated items. but will not sync to the DB. 

2021-02-06 23:17:11.492 T:5448  NOTICE: PLEX.sync: Doing initial sync on Kodi startup
2021-02-06 23:17:11.518 T:5448  NOTICE: PLEX.sync.sections: Starting synching sections from the PMS
2021-02-06 23:17:12.026 T:5448  NOTICE: PLEX.sync.sections: Done synching sections from the PMS: []
2021-02-06 23:17:12.043 T:5448   ERROR: PLEX.sync: Exception encountered: u'game'
2021-02-06 23:17:12.043 T:5448   ERROR: PLEX.utils: Error encountered:  - u'game'
2021-02-06 23:17:12.045 T:5448   ERROR: PLEX.utils: _____________________________________________________________
2021-02-06 23:17:12.045 T:5448   ERROR: PLEX.utils:     Traceback (most recent call last):
2021-02-06 23:17:12.045 T:5448   ERROR: PLEX.utils:       File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\common.py", line 32, in run
2021-02-06 23:17:12.045 T:5448   ERROR: PLEX.utils:         self._run()
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:       File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\utils.py", line 1006, in wrapper
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:         result = func(*args, **kwargs)
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:       File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\full_sync.py", line 275, in _run
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:         if self.should_cancel() or not sections.sync_from_pms(self):
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:       File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\sections.py", line 637, in sync_from_pms
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:         return _sync_from_pms(pick_libraries)
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:       File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\sections.py", line 653, in _sync_from_pms
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:         sections.append(Section(index=i, xml_element=xml_element))
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:       File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\sections.py", line 86, in __init__
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:         self.from_xml(xml_element)
2021-02-06 23:17:12.046 T:5448   ERROR: PLEX.utils:       File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\sections.py", line 191, in from_xml
2021-02-06 23:17:12.047 T:5448   ERROR: PLEX.utils:         self.section_type = api.plex_type
2021-02-06 23:17:12.047 T:5448   ERROR: PLEX.utils:       File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\sections.py", line 137, in section_type
2021-02-06 23:17:12.047 T:5448   ERROR: PLEX.utils:         self.content = v.CONTENT_FROM_PLEX_TYPE[value]
2021-02-06 23:17:12.047 T:5448   ERROR: PLEX.utils:     KeyError: u'game'
2021-02-06 23:17:12.047 T:5448   ERROR: PLEX.utils: _____________________________________________________________
2021-02-06 23:17:12.047 T:5448  NOTICE: PLEX.sync: Done initial sync on Kodi startup

**Comment by TATUMTOT** [comment]
Using kodi 18.9 and i have tried plugins 12.2.*

**Comment by croneter** [comment]
Bad one, due to a new Plex library type `games` for arcade games... Thanks a ton for the bug report!

Fixed in both 3.0.8 as well as 2.12.13
