### ISSUE TITLE
How to update to Kodi 19 Matrix

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#1359]
# Here is what you need to do
* Install the new PlexKodiConnect repository for Kodi Matrix: https://github.com/croneter/PlexKodiConnect/wiki/Install-PKC-Repository
* Update PlexKodiConnect to the latest version number starting with `3` (should be at the top of the list of available versions): navigate to Add-ons -> My Add-Ons -> Video add-ons -> PlexKodiConnect. Hit `Update`
* Re-Enable PlexKodiConnect with `Enable`

**Comment by LetrixZ** [comment]
Matrix repository doesn't install.

**Comment by justgettinggood** [comment]
repo didn't auto upgrade so clicked on it manually and it upgraded.   Now won't connect to plex, says check log.   Checked log and get the below.   Have tried to completely remove and reinstall to no avail.  Seems uninstalling plexkodiconnect doesn't remove everything such as helper and media hack.  Please advise 

info from log
2021-03-04 15:43:56.470 T:48290    INFO <general>: Python interpreter stopped
2021-03-04 15:44:09.464 T:42406   ERROR <general>: Control 50 in window 10025 has been asked to focus, but it can't
2021-03-04 15:44:09.503 T:48325    INFO <general>: initializing python engine.
2021-03-04 15:44:09.757 T:48325   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'dir_util' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)
                                                   Traceback (most recent call last):
                                                     File "/home/justgettinggood/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 13, in <module>
                                                       from resources.lib import entrypoint, utils, transfer, variables as v, loghandler
                                                     File "/home/justgettinggood/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 14, in <module>
                                                       from . import utils
                                                     File "/home/justgettinggood/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 29, in <module>
                                                       from . import path_ops, variables as v
                                                     File "/home/justgettinggood/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/path_ops.py", line 20, in <module>
                                                       from distutils import dir_util
                                                   ImportError: cannot import name 'dir_util' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)
                                                   -->End of Python script error report<--

**Comment by croneter** [comment]
@justgettinggood just follow the steps above. You did not do that

**Comment by justgettinggood** [comment]
> @justgettinggood just follow the steps above. You did not do that. Top to bottom. The repo will NOT auto upgrade!

Thanks for such fast response croneter.  When i originally installed this addon i thought i followed the guide stated the recommended way to install so that it would auto update, must have misunderstood that part.    None the less, i realized that it didn't auto upgrade as it was broke and on older version.  So i tried to manually and failed with the above log errors after appearance of successful install.  Been at this awhile now, hence the reason for my post.  But as of now, i believe i solved one issue to only move to another.  I had to install python3-distutils with following command. sudo apt-get install python3-distutils   Not sure why that was needed now, maybe it was removed with kodi upgrade, unsure, but i can now connect again.    But when i try to click on a show i get below in logs 

 ERROR <general>: PLEX.utils: Error encountered:  - 'str' object has no attribute 'get' in log file

And

has left several classes in memory that we couldn't clean up.

And 
INFO <general>: Python interpreter stopped
2021-03-04 16:40:31.377 T:64858    INFO <general>: Creating InputStream
2021-03-04 16:40:32.237 T:64858   ERROR <general>: CCurlFile::FillBuffer - Failed: Transferred a partial file(18)
2021-03-04 16:40:32.237 T:64858 WARNING <general>: CCurlFile::FillBuffer - Reconnect, (re)try 1

You are right in saying i didn't follow the above though, i could not and still cannot find place to Try to reset the Kodi database in the PKC settings under Advanced (red text). Answer YES, then NO, let Kodi rescan the Plex library.  I have look high and low, change from basic, standard, advance and expert.  Went though even kodi settings, i cannot find the place to reset database.

**Comment by justgettinggood** [comment]
wow, found advanced.  Problem was you cannot click on the arrow for the headings in confluence. you have to arrow over with arrow keys on keyboard and it gives way more settings then i ever saw before included advanced.  Since below you can change view settings from basic to advance, i was confusing the two when i could not actually see the advanced menu due to not being able to move over via mouse click on the arrow for headings.categories

**Comment by justgettinggood** [comment]
i give for today...  can't get it to work. TV Show will load after long time of kodi "working"  but movies not at all or not at least in time i am willing to wait for it to load.  Some of the things poping up in the logs are below 

WARNING <general>: CPythonInvoker(4, /home/justgettinggood/.kodi/addons/plugin.video.plexkodiconnect.tvshows/default.py): the python script "/home/mada/.kodi/addons/plugin.video.plexkodiconnect.tvshows/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE

AND

WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.

AND
ERROR <general>: PLEX.playback: Could not seek to 0
ERROR <general>: PLEX.plexgdm: Unable to send registration message

Not sure what i got done wrong, assume its my fault.  Maybe tomorrow will try and figure out how to remove everything and start fresh.

**Comment by croneter** [comment]
@justgettinggood 
Do the following to start from scratch with PlexKodiConnect:
1. In Kodi, navigate to Add-ons -> My Add-ons -> All. **Remove** any add-ons starting with `PlexKodiConnect`, especially:
    * `PlexKodiConnect`
    * `PlexKodiConnect Addons for ...`
    * `PlexKodiConnect Beta Addons for ...`
    * `PlexKodiConnect Helper Movies`
    * `PlexKodiConnect Helper TV Shows`
2. Exit Kodi
3. In the folder `addons` of the [Kodi data folder](https://kodi.wiki/view/Kodi_data_folder), delete the following directories completely (if they still exist):
    * `plugin.video.plexkodiconnect`
    * `plugin.video.plexkodiconnect.movies`
    * `plugin.video.plexkodiconnect.tvshows`
    * `repository.plexkodiconnect`
    * `repository.plexkodiconnectbeta`
4. In the folder `addon_data` in the [Kodi userdata folder](https://kodi.wiki/view/Userdata#Location), delete the following directories completely (if they still exist):
    * `plugin.video.plexkodiconnect`
5. Install PlexKodiConnect again from scratch: https://github.com/croneter/PlexKodiConnect/wiki/Enable-PKC-Source
