### ISSUE TITLE
Local variable 'user' referenced before assignement

### ISSUE THREAD

**Issue by Kakunas** [croneter/PlexKodiConnect#1372]
Used Version 3.0.12

Maybe it's the same problem as in the previous version for Kodi 18.9 [https://github.com/croneter/PlexKodiConnect/issues/1276](url)

Otherwise i have a look what exactly goes worng 😊

**Comment by croneter** [comment]
I need your DEBUG Kodi log file as always, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Did you install the new PlexKodiConnect repository for Kodi Matrix as explained here? https://github.com/croneter/PlexKodiConnect/issues/1359

**Comment by Kakunas** [comment]
2021-02-26 11:01:46.097 T:11832   DEBUG <general>: PLEX.plex_functions: Checking connection successfull. Answer: 200
2021-02-26 11:01:46.097 T:11832    INFO <general>: PLEX.service: Server is online and ready
2021-02-26 11:01:46.178 T:19740   DEBUG <general>: PLEX.kodimonitor: PKC settings change detected
2021-02-26 11:01:46.277 T:6648     INFO <general>: Skipped 2 duplicate messages..
2021-02-26 11:01:46.277 T:6648     INFO <general>: PLEX.service: Authenticating user
2021-02-26 11:01:46.277 T:6648     INFO <general>: PLEX.service: Trying to authenticate without a token
2021-02-26 11:01:46.277 T:6648    DEBUG <general>: PLEX.plex_functions: Checking connection to server
2021-02-26 11:01:46.287 T:6648    DEBUG <general>: PLEX.plex_functions: Checking connection successfull. Answer: 200
2021-02-26 11:01:46.287 T:6648     INFO <general>: PLEX.service: Successfully authenticated
2021-02-26 11:01:46.289 T:6648    DEBUG <CAddonSettings[plugin.video.plexkodiconnect]>: trying to load setting definitions from old format...
2021-02-26 11:01:46.319 T:6648    ERROR <general>: Skipped 5 duplicate messages..
2021-02-26 11:01:46.319 T:6648    ERROR <general>: PLEX.utils: Error encountered:  - local variable 'user' referenced before assignment
2021-02-26 11:01:46.321 T:6648    ERROR <general>: PLEX.utils: _____________________________________________________________
2021-02-26 11:01:46.321 T:6648    ERROR <general>: PLEX.utils:     Traceback (most recent call last):
2021-02-26 11:01:46.321 T:6648    ERROR <general>: PLEX.utils:       File "C:\Users\Peter\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\backgroundthread.py", line 373, in _runTask
2021-02-26 11:01:46.321 T:6648    ERROR <general>: PLEX.utils:         task._run()
2021-02-26 11:01:46.321 T:6648    ERROR <general>: PLEX.utils:       File "C:\Users\Peter\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\backgroundthread.py", line 307, in _run
2021-02-26 11:01:46.321 T:6648    ERROR <general>: PLEX.utils:         self.run()
2021-02-26 11:01:46.321 T:6648    ERROR <general>: PLEX.utils:       File "C:\Users\Peter\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\backgroundthread.py", line 337, in run
2021-02-26 11:01:46.321 T:6648    ERROR <general>: PLEX.utils:         result = self._function(*self._args, **self._kwargs)
2021-02-26 11:01:46.321 T:6648    ERROR <general>: PLEX.utils:       File "C:\Users\Peter\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\service_entry.py", line 247, in authenticate
2021-02-26 11:01:46.321 T:6648    ERROR <general>: PLEX.utils:         if self._do_auth():
2021-02-26 11:01:46.322 T:6648    ERROR <general>: PLEX.utils:       File "C:\Users\Peter\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\service_entry.py", line 419, in _do_auth
2021-02-26 11:01:46.322 T:6648    ERROR <general>: PLEX.utils:         'true' if user.isManaged else 'false')
2021-02-26 11:01:46.322 T:6648    ERROR <general>: PLEX.utils:     UnboundLocalError: local variable 'user' referenced before assignment
2021-02-26 11:01:46.322 T:6648    ERROR <general>: PLEX.utils: _____________________________________________________________

**Comment by croneter** [comment]
Fixed with version 3.0.13
