### ISSUE TITLE
PKC fail to start - Matrix Ubuntu

### ISSUE THREAD

**Issue by Nadonate** [croneter/PlexKodiConnect#1391]
I'm having an issue, after installing PKC from the stable Matrix repo I get a "PlexKodiConnect error, please check logs" notification. When I got to settings and select "choose a plex server" under the connection header, nothing happens and I get the same error notification.

This is a fresh matrix install.

OS - Ubuntu 20
Kodi - Matrix 19

Here is the pertinent log info:
`7 11:54:08.159 T:3714    DEBUG <general>: -->Python Interpreter Initialized<--
2021-03-07 11:54:08.159 T:3714    DEBUG <general>: 
                                                   
2021-03-07 11:54:08.159 T:3714    DEBUG <general>: CPythonInvoker(4, /home/nado/.kodi/addons/plugin.video.plexkodiconnect/default.py): the source file to load is "/home/nado/.kodi/addons/plugin.video.plexkodiconnect/default.py"
2021-03-07 11:54:08.159 T:3714    DEBUG <general>: CPythonInvoker(4, /home/nado/.kodi/addons/plugin.video.plexkodiconnect/default.py): setting the Python path to /home/nado/.kodi/addons/plugin.video.plexkodiconnect:/home/nado/.kodi/addons/script.module.certifi/lib:/home/nado/.kodi/addons/script.module.chardet/lib:/home/nado/.kodi/addons/script.module.defusedxml/lib:/home/nado/.kodi/addons/script.module.idna/lib:/home/nado/.kodi/addons/script.module.requests/lib:/home/nado/.kodi/addons/script.module.urllib3/lib:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages
2021-03-07 11:54:08.159 T:3714    DEBUG <general>: CPythonInvoker(4, /home/nado/.kodi/addons/plugin.video.plexkodiconnect/default.py): entering source directory /home/nado/.kodi/addons/plugin.video.plexkodiconnect
2021-03-07 11:54:08.159 T:3714    DEBUG <general>: CPythonInvoker(4, /home/nado/.kodi/addons/plugin.video.plexkodiconnect/default.py): instantiating addon using automatically obtained id of "plugin.video.plexkodiconnect" dependent on version 3.0.0 of the xbmc.python api
2021-03-07 11:54:08.357 T:3714    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'dir_util' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)
                                                   Traceback (most recent call last):
                                                     File "/home/nado/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 13, in <module>
                                                       from resources.lib import entrypoint, utils, transfer, variables as v, loghandler
                                                     File "/home/nado/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 14, in <module>
                                                       from . import utils
                                                     File "/home/nado/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 29, in <module>
                                                       from . import path_ops, variables as v
                                                     File "/home/nado/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/path_ops.py", line 20, in <module>
                                                       from distutils import dir_util
                                                   ImportError: cannot import name 'dir_util' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)
                                                   -->End of Python script error report<--`

Let me know and I can pastebin the entire log if its needed.

-Thanks,

**Comment by croneter** [comment]
Yes as always, I need the entire DEBUG log, please consult https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Nadonate** [comment]
Pastebin has a 512 kb limit for free accounts now, and no pro accounts available?

Anyway, thanks for looking at this. I had to drop the log in google drive -->

[kodi.log](https://drive.google.com/file/d/1oA6X1hP0lFUiAhhGw38mrOZ6oHYUbOtI/view?usp=sharing)

**Comment by croneter** [comment]
Did you start with a fresh Kodi version? Seems like there's more amiss then "just" PlexKodiConnect, e.g. for the add-on `script.skinvariables`:
```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'json.decoder.JSONDecodeError'>
Error Contents: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
 File "/home/nado/.kodi/addons/script.skinvariables/script.py", line 10, in <module>
   TMDbScript.router()
 File "/home/nado/.kodi/addons/script.skinvariables/resources/lib/script.py", line 129, in router
   self.make_variables()
 File "/home/nado/.kodi/addons/script.skinvariables/resources/lib/script.py", line 37, in make_variables
   meta = loads(content) or []
 File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
   return _default_decoder.decode(s)
 File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
   obj, end = self.raw_decode(s, idx=_w(s, 0).end())
 File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
   raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
-->End of Python script error report<--
```

Other than that, PlexKodiConnect needs the Python module `distutils`_
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ImportError'>
Error Contents: cannot import name 'dir_util' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)
Traceback (most recent call last):
 File "/home/nado/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 13, in <module>
   from resources.lib import entrypoint, utils, transfer, variables as v, loghandler
 File "/home/nado/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 14, in <module>
   from . import utils
 File "/home/nado/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 29, in <module>
   from . import path_ops, variables as v
 File "/home/nado/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/path_ops.py", line 20, in <module>
   from distutils import dir_util
ImportError: cannot import name 'dir_util' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)
-->End of Python script error report<--
```

Kodi should already be shipped with it, don't know what happened in your case. Try to run this command in your Linux terminal, then try again:
```
sudo apt-get install python3-distutils --reinstall
```

**Comment by Nadonate** [comment]
That worked! Thanks for your help..now on to the skinvariables issue...

Thanks for your help, & thanks for the great addon @croneter !
