### ISSUE TITLE
Error on startup of Kodi and items won't play

### ISSUE THREAD

**Issue by jake404** [croneter/PlexKodiConnect#1445]
After getting PlexKodiConnect working with Kodi Matrix, it stopped working after a restart of Kodi. Now it shows the error message 'PlexKodiConnect error' and the spinner won't stop when trying to play a Plex item that worked before the restart.
<a href="https://imgbb.com/"><img src="https://i.ibb.co/vZ39Zc2/2021-04-11-16-26-32.png" alt="2021-04-11-16-26-32" border="0"></a><br />
   ####
Here is the full logfile from a fresh restart of Kodi and also trying to play an item.
https://pastebin.com/DmLcHE5P

**Comment by croneter** [comment]
You got this error in the log:
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
   Error Type: <class 'RuntimeError'>
   Error Contents: implement_array_function method already has a docstring
   Traceback (most recent call last):
     File "/home/htpcuser/.kodi/addons/script.embuary.helper/plugin.py", line 10, in <module>
       from resources.lib.plugin_content import *
     File "/home/htpcuser/.kodi/addons/script.embuary.helper/resources/lib/plugin_content.py", line 11, in <module>
       from resources.lib.image import *
     File "/home/htpcuser/.kodi/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module>
       from PIL import ImageFilter,Image,ImageOps
     File "/usr/lib/python3/dist-packages/PIL/ImageFilter.py", line 20, in <module>
       import numpy
     File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
       from . import core
     File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 17, in <module>
       from . import multiarray
     File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
       from . import overrides
     File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 16, in <module>
       add_docstring(
   RuntimeError: implement_array_function method already has a docstring
   -->End of Python script error report<--
```
I'm afraid there's not much I can do 😢 . Try to update the Python package `numpy` that throws this error, e.g. using
```
sudo pip install numpy --upgrade
```

**Comment by jake404** [comment]
I found that there is an incompatibility between PlexKodiConnect and the addon Embuary Helper. They both work on their own but not installed at the same time.

**Comment by croneter** [comment]
Ouch! Thanks a ton for the feedback
