### ISSUE TITLE
Error upon installation on Kodi Matrix (OSMC)

### ISSUE THREAD

**Issue by beffy** [croneter/PlexKodiConnect#1448]
Hi,

I get an error after installation of the add-on in Kodi Matrix on OSMC. The add-on seems to be installed, however, but when I try and open the add-on I get another error. 

Here are some debug logs after a fresh reboot where I install the add-on and try and open it afterwards.

Logs: https://pastebin.com/tA6K5uCy

**Comment by croneter** [comment]
Should be fixed in PKC **BETA** version 3.1.2. Let me know here if this is not the case!

**Comment by johndoewashere2** [comment]
Having a similar issue as well on the latest Kodi Matrix (OSMC) fresh image and PKC installation. 

Initial earlier beta version reports: 
`2021-05-11 19:01:40.136 T:3570     INFO <general>: initializing python engine.
2021-05-11 19:01:41.558 T:3570    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'dir_util' from 'distutils' (/usr/lib/python3.7/distutils/__init__.py)
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 13, in <module>
                                                       from resources.lib import entrypoint, utils, transfer, variables as v, loghandler
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 14, in <module>
                                                       from . import utils
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 29, in <module>
                                                       from . import path_ops, variables as v
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/path_ops.py", line 20, in <module>
                                                       from distutils import dir_util
                                                   ImportError: cannot import name 'dir_util' from 'distutils' (/usr/lib/python3.7/distutils/__init__.py)
                                                   -->End of Python script error report<--
                                                   
2021-05-11 19:01:41.695 T:3570     INFO <general>: Python interpreter stopped
2021-05-11 19:01:41.705 T:3569    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.plexkodiconnect/
2021-05-11 19:01:41.711 T:2586    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexkodiconnect/) failed
`

Updating to latest 3.1.3 beta reports: 
`2021-05-11 19:04:46.126 T:3581     INFO <general>: CAddonMgr::FindAddon: plugin.video.plexkodiconnect v3.1.3 installed
2021-05-11 19:04:46.137 T:3597     INFO <general>: initializing python engine.
2021-05-11 19:04:46.284 T:2586  WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2021-05-11 19:04:51.197 T:3597    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'shutil' has no attribute 'copy_tree'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 4, in <module>
                                                       from resources.lib import service_entry
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 11, in <module>
                                                       from . import sync, library_sync
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 7, in <module>
                                                       from . import library_sync, timing
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/__init__.py", line 2, in <module>
                                                       from .full_sync import start
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 9, in <module>
                                                       from .fill_metadata_queue import FillMetadataQueue
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/fill_metadata_queue.py", line 5, in <module>
                                                       from . import common, sections
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/sections.py", line 26, in <module>
                                                       preserve_mode=0)  # dont copy permission bits so we have write access!
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/path_ops.py", line 189, in copy_tree
                                                       return shutil.copy_tree(src, dst, *args, **kwargs)
                                                   AttributeError: module 'shutil' has no attribute 'copy_tree'
                                                   -->End of Python script error report<--
                                                   
2021-05-11 19:04:51.456 T:3597     INFO <general>: Python interpreter stopped
2021-05-11 19:05:03.689 T:2586    ERROR <general>: Control 9 in window 10146 has been asked to focus, but it can't
2021-05-11 19:05:09.025 T:3609     INFO <general>: initializing python engine.
2021-05-11 19:05:12.082 T:3609    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'shutil' has no attribute 'copy_tree'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 13, in <module>
                                                       from resources.lib import entrypoint, utils, transfer, variables as v, loghandler
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 22, in <module>
                                                       from .library_sync.nodes import NODE_TYPES
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/__init__.py", line 2, in <module>
                                                       from .full_sync import start
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 9, in <module>
                                                       from .fill_metadata_queue import FillMetadataQueue
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/fill_metadata_queue.py", line 5, in <module>
                                                       from . import common, sections
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/sections.py", line 26, in <module>
                                                       preserve_mode=0)  # dont copy permission bits so we have write access!
                                                     File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/path_ops.py", line 189, in copy_tree
                                                       return shutil.copy_tree(src, dst, *args, **kwargs)
                                                   AttributeError: module 'shutil' has no attribute 'copy_tree'
                                                   -->End of Python script error report<--
                                                   
2021-05-11 19:05:12.355 T:3609     INFO <general>: Python interpreter stopped
`

Please let me know if you require any more info for troubleshooting. :)

**Comment by croneter** [comment]
Kindly try PKC **BETA** version 3.1.4 and report back. Handling permissions with Linux systems is a pain with Python 😞

**Comment by johndoewashere2** [comment]
This appears to have resolved the Plex server sign in issue. :)
