### ISSUE TITLE
Error after fresh new install / PKC 3.1.3 / Kodi 19

### ISSUE THREAD

**Issue by Cyriltra** [croneter/PlexKodiConnect#1470]
Hello,

just did a brand new install of coreelec and PKC. After install of PKC, i got following error is the log:

`ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'shutil' has no attribute 'copy_tree'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 4, in <module>
                                                       from resources.lib import service_entry
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 11, in <module>
                                                       from . import sync, library_sync
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 7, in <module>
                                                       from . import library_sync, timing
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/__init__.py", line 2, in <module>
                                                       from .full_sync import start
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 9, in <module>
                                                       from .fill_metadata_queue import FillMetadataQueue
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/fill_metadata_queue.py", line 5, in <module>
                                                       from . import common, sections
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/sections.py", line 23, in <module>
                                                       path_ops.copy_tree(
                                                     File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/path_ops.py", line 189, in copy_tree
                                                       return shutil.copy_tree(src, dst, *args, **kwargs)
                                                   AttributeError: module 'shutil' has no attribute 'copy_tree'`

Thank you

**Comment by croneter** [comment]
That should be part of your standard Python installation. Please take this back to the CoreElec Team. Or use LibreElec. Or stick to Kodi 18 for now...

**Comment by Cyriltra** [comment]
i didnt dig in the code, only did a quick google search, shouldn't the function be named **copytree** instead of **copy_tree** ?
as seen on https://docs.python.org/3/library/shutil.html

**Comment by Portisch** [comment]
It's not fault of CE Team...
Please check first your code before point at other people, thank you.

https://github.com/croneter/PlexKodiConnect/commit/35c9aeff8b8f02f28b471fd384514e027b2b38d3

**Comment by croneter** [comment]
Uiuiuiui, you're correct, @Cyriltra, thanks for the pointer! Sorry for pointing fingers, @Portisch 😞

**Comment by Cyriltra** [comment]
Hi @croneter, i did rename the function to copytree and run again, but encounter below error:
```
File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/path_ops.py", line 189, in copy_tree
                                                       return shutil.copytree(src, dst, *args, **kwargs)
                                                   TypeError: copytree() got an unexpected keyword argument 'preserve_mode'
```
Hope that helps a bit further

Thank you !
Thanks @Portisch too

**Comment by aerogems** [comment]
I experienced the same issue on my Shield with AndroidTV. The issue appears to have started in either 3.1.1 or 3.1.2 (I never tested 3.1.1, sorry). Version 3.1.2 gives the same error, but 3.1.0 works correctly on a fresh install.

**Comment by ccutrer** [comment]
I was able to get the add-on to launch (3.1.3) by changing copy_tree to copytree, and then removing the preserve_mode argument from the caller. But when I got to settings, anytime I try to do anything like configure a server or log in to Plex.tv, it just relaunches the add-on. The logs says things like

```
2021-05-11 18:38:06.882 T:2638    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexkodiconnect/?mode=settings) failed
```

and

```
2021-05-11 18:41:09.214 T:3314     INFO <general>: CPythonInvoker(15, /home/osmc/.kodi/addons/plugin.video.plexkodiconnect/default.py): script aborted
2021-05-11 18:41:09.246 T:2638    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexkodiconnect/?mode=switchuser) failed
```

There's no exception or backtrace from what I can find in the logs.

I'm running the latest OSMC build on a Veros 4k.

**Comment by croneter** [comment]
@ccutrer 
Try to add this instead of preserve_mode: copy_function=shutil.copy

**Comment by croneter** [comment]
Kindly try PKC **BETA** version 3.1.4 and report back. Handling permissions with Linux systems is a pain with Python 😞

**Comment by aerogems** [comment]
Had to go through the "update the database for new version of Kodi" bit twice, but third time it started up like it should and seems to be working... so far. 🤞

**Comment by ccutrer** [comment]
yup, I'm able to log in to plex.tv now, but I can't choose libraries to sync (it crashes, and then has a pop up notification "Unauthorized for PMS", and it crashes when I go to Change logged in Plex home user.

**Comment by croneter** [comment]
@ccutrer Debug logs please, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
