### ISSUE TITLE
Kodi crashes on mark as visualized (both manually and automatic when the video ends). Also crashes after X minutes during video playback. 

### ISSUE THREAD

**Issue by xeviff** [croneter/PlexKodiConnect#1722]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
In the right moment when I finish to see a film or a episode, kodi crashes (restart). If I manually mark a video as seen, then it occurs the same effect. And furthermore, Kodi also crashes randomly when I'm whatching a video (film or tv show), sometimes it happens in 10 minuts, sometimes in 50... It's quite anoying because it breaks your emotion / experience.

## To Reproduce
1. Mark a film "visualized" / "seen" (I don't have the english Kodi version), or see a long movie (to have more probabilities to happen)
2. "Wait" to Kodi crash
4. See that Kodi is restarting

## Expected behavior
Kodi didn't crash and we could see the films without any interruption :-D

## You need to attach a KODI LOG FILE
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7605163/kodi.log)

A Kodi debug log file is needed that you recorded while you reproduced the bug. **Do clean your log of all Plex tokens (="Plex passwords")!!!** .
1. Activate Kodi's debug logging by going to the Kodi `Settings` -> `System` -> `Logging`. Then toggle the `Enable debug logging` setting.
2. Restart Kodi to start with a "fresh" log file.
3. Reproduce the bug.
4. Follow the [Kodi instructions](http://kodi.wiki/view/Log_file/Easy) to grab/share the Kodi log file. Usually only `kodi.log` is needed
    * You can [find the log file here](http://kodi.wiki/view/Log_file/Advanced#Location)
5. **Delete all references to any of your Plex tokens** by searching for `X-Plex-Token` and `accesstoken` and replacing the strings just after that!
    * It's easiest if you copy your token, then use Search&Replace for the entire log file
    * You don't want others to have access to your Plex installation....
6. Drop your log file here in this issue. Or use a free pasting-service like https://pastebin.com and include the link to it here
    
I am aware that I can delete Plex tokens that I accidentially posted by following the [instructions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server)

**Comment by croneter** [comment]
Something seems to be off with your Kodi (!!) installation:
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'datetime.timedelta' object has no attribute 'timestamp'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.widgets/plugin.py", line 9, in <module>
                                                       import main
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.widgets/resources/lib/main.py", line 20, in <module>
                                                       from metadatautils import MetadataUtils
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 10, in <module>
                                                       import helpers.kodi_constants as kodi_constants
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/helpers/kodi_constants.py", line 11, in <module>
                                                       from .utils import KODI_VERSION
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/helpers/utils.py", line 13, in <module>
                                                       import arrow
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/__init__.py", line 2, in <module>
                                                       from .api import get, now, utcnow
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/api.py", line 12, in <module>
                                                       from arrow.arrow import TZ_EXPR, Arrow
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/arrow.py", line 34, in <module>
                                                       from arrow import formatter, locales, parser, util
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/parser.py", line 26, in <module>
                                                       from arrow.util import next_weekday, normalize_timestamp
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/util.py", line 6, in <module>
                                                       from arrow.constants import (
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.arrow/lib/arrow/constants.py", line 16, in <module>
                                                       _MAX_TIMESTAMP = datetime.max.timestamp()
                                                   AttributeError: 'datetime.timedelta' object has no attribute 'timestamp'
                                                   -->End of Python script error report<--
```
I don't see anything PKC-related. I'm personally using PKC on Android as well - no issue at all. Try to reset Kodi completely, start from scratch, and make sure that you're using the latest software.
