### ISSUE TITLE
Upnext and Dashboard Plex Server

### ISSUE THREAD

**Issue by showkubii** [croneter/PlexKodiConnect#1723]
Matrix - PKC 3.5.16 Beta - Direct Paths

I pressed play episode 2 from Upnext but the Dashboard Plex Server shows that I am playing episode 1.

I want the Dashboard Plex Server to show the correct episode.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7622750/kodi.log)

**Comment by croneter** [comment]
Well, the Kodi add-on upnext itself has issues:
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'binascii.Error'>
                                                   Error Contents: Incorrect padding
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kat\AppData\Roaming\Kodi\addons\service.upnext\resources\lib\utils.py", line 127, in decode_data
                                                       json_data = unhexlify(encoded)
                                                   binascii.Error: Odd-length string
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kat\AppData\Roaming\Kodi\addons\service.upnext\resources\lib\monitor.py", line 111, in onNotification
                                                       decoded_data, encoding = decode_json(data)
                                                     File "C:\Users\kat\AppData\Roaming\Kodi\addons\service.upnext\resources\lib\utils.py", line 141, in decode_json
                                                       return decode_data(encoded[0])
                                                     File "C:\Users\kat\AppData\Roaming\Kodi\addons\service.upnext\resources\lib\utils.py", line 130, in decode_data
                                                       json_data = b64decode(encoded)
                                                     File "C:\Program Files\Kodi\system\python\Lib\base64.py", line 87, in b64decode
                                                       return binascii.a2b_base64(s)
                                                   binascii.Error: Incorrect padding
                                                   -->End of Python script error report<--
```
I'll look into it

**Comment by croneter** [comment]
Opened a new issue with upnext: https://github.com/im85288/service.upnext/issues/267

**Comment by croneter** [comment]
Thanks for your bug report! Try the brand new beta version 3.5.17 please

**Comment by showkubii** [comment]
> Thanks for your bug report! Try the brand new beta version 3.5.17 please

Good job, It works as expected. 

Thank you very much.

**Comment by showkubii** [comment]
Matrix - PKC 3.6.13 Beta - Direct Paths.
The problem happened again.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/8427043/kodi.log)

**Comment by showkubii** [comment]
After restart plex server.
PKC is back to work.
