### ISSUE TITLE
PKC quitting video playback after a few minutes

### ISSUE THREAD

**Issue by roc16** [croneter/PlexKodiConnect#1736]
Hi @croneter,
I have a strange issue. My video is quitting after a few min of playback. I'm using Coreelec 19.3 Matrix on an Odroid N2+ with Pkc 3.5.8. I did a fresh install of everything and added PKC as the only addon. Skin is Estuary. Plex server version is 1.25.1.5286 installed on Synology 920+ DSM 7. Log file is attached (I reproduced using Alvin and the chipmunks movie). 

Also, running PKC on coreelec 9.2.6 (Leia 18.9) gives me no issues. Any help would be appreciated.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7704257/kodi.log)

**Comment by croneter** [comment]
Sorry, this is not a PlexKodiConnect issue, but a Kodi issue:
````
ERROR <general>: Read - Error( -4, read call failed with "Command was cancelled" )
ERROR <general>: Process - <nfs://192.168.178.158/volume1/media/movies/Alvin and the Chipmunks (2007)/Alvin and the Chipmunks (2007) Bluray-1080p.mp4> source read failed with -4!
INFO <general>: CVideoPlayer::OnExit()
```
PKC just tells Kodi what to play. Then it's all up to Kodi. 

Caught another, minor and unrelated PKC bug though thanks to your log:
```
2021-12-13 13:36:23.140 T:4807    DEBUG <general>: CheckIdle - Closing session to https://<IP>.plex.direct (easy=0xc23393c8, multi=0xe4b1b690)
2021-12-13 13:36:24.164 T:4807    DEBUG <general>: CheckIdle - Closing session to https://<IP>.plex.direct (easy=0xdef5bdc0, multi=0xdfdf51c0)
2021-12-13 13:36:24.241 T:5102    ERROR <general>: CCurlFile::Stat - Failed: Timeout was reached(28) for https://assets.fanart.tv/fanart/movies/68718/moviethumb/django-unchained-5cced56135128.jpg
2021-12-13 13:36:24.241 T:5102    DEBUG <general>: GetImageHash - unable to stat url https://assets.fanart.tv/fanart/movies/68718/moviethumb/django-unchained-5cced56135128.jpg
2021-12-13 13:36:27.240 T:4977    DEBUG <general>: PLEX.plexgdm: Recieved UDP packet from [('192.168.178.158', 46815)] containing [M-SEARCH * HTTP/1.1]
2021-12-13 13:36:27.240 T:4977    DEBUG <general>: PLEX.plexgdm: Detected client discovery request from ('192.168.178.158', 46815). Replying
2021-12-13 13:36:27.240 T:4977    DEBUG <general>: PLEX.plexgdm: Sent registration data HTTP/1.0 200 OK
2021-12-13 13:36:31.491 T:5006  WARNING <general>: PLEX.download: Server unreachable at: http://webservice.fanart.tv/v3/movies/tt0107711?api_key=639191cb0774661597f28a47e7e2bad5
2021-12-13 13:36:31.492 T:5006  WARNING <general>: PLEX.download: HTTPConnectionPool(host='webservice.fanart.tv', port=80): Max retries exceeded with url: /v3/movies/tt0107711?api_key=639191cb0774661597f28a47e7e2bad5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xe5b27150>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2021-12-13 13:36:31.521 T:5006    ERROR <general>: PLEX.utils: Error encountered:  - 'NoneType' object has no attribute 'ok'
2021-12-13 13:36:31.527 T:5006    ERROR <general>: PLEX.utils: _____________________________________________________________
2021-12-13 13:36:31.527 T:5006    ERROR <general>: PLEX.utils:     Traceback (most recent call last):
2021-12-13 13:36:31.527 T:5006    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/additional_metadata.py", line 88, in run
2021-12-13 13:36:31.527 T:5006    ERROR <general>: PLEX.utils:         self._run()
2021-12-13 13:36:31.527 T:5006    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/additional_metadata.py", line 74, in _run
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:         self._loop()
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/additional_metadata.py", line 68, in _loop
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:         self._process_in_batches(item_getter, processor, plex_type)
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/additional_metadata.py", line 58, in _process_in_batches
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:         processor(plex_id, plex_type, self.refresh)
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/additional_metadata_tmdb.py", line 134, in process_fanart
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:         artworks = api.fanart_artwork(artworks)
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_api/artwork.py", line 144, in fanart_artwork
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:         artworks = self.lookup_fanart_tv(external_id[0], artworks)
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_api/artwork.py", line 227, in lookup_fanart_tv
2021-12-13 13:36:31.528 T:5006    ERROR <general>: PLEX.utils:         if not data.ok:
2021-12-13 13:36:31.529 T:5006    ERROR <general>: PLEX.utils:     AttributeError: 'NoneType' object has no attribute 'ok'
2021-12-13 13:36:31.529 T:5006    ERROR <general>: PLEX.utils: _____________________________________________________________
```

**Comment by roc16** [comment]
Hiya @croneter thanks for the quick response. At least I know it’s not a PKC issue. I’ll roll back to kodi 19.2 and see if that fixes it. Cheers.

**Comment by roc16** [comment]
Hi @croneter, I’ve raised the issue over on the coreelec forum and will leave the outcome here in case it helps anyone else. Feel free to close this issue. Thanks.
