### ISSUE TITLE
Crash when selecting "set network credentials for Direct Paths and direct play"

### ISSUE THREAD

**Issue by lmarianski** [croneter/PlexKodiConnect#1749]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiCon nect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
When selecting the mentioned option, kodi just crashes.
The same thing happens when i try to "Reset the database and optionally reset PlexKodiConnect"

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7765481/kodi.log)

**Comment by croneter** [comment]
Your log states:
```
ERROR <general>: Traceback (most recent call last):
ERROR <general>:   File "/usr/lib/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters
ERROR <general>:     
ERROR <general>: register_converter("timestamp", convert_timestamp)
ERROR <general>: 
ERROR <general>: KeyError
ERROR <general>: : 
ERROR <general>: 'timepart_full'
ERROR <general>: 
ERROR <general>: Exception ignored deletion of interned string failed
ERROR <general>: :
ERROR <general>: Traceback (most recent call last):
ERROR <general>:   File "/usr/lib/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters
ERROR <general>:     
ERROR <general>: register_converter("timestamp", convert_timestamp)
ERROR <general>: 
ERROR <general>: KeyError
ERROR <general>: : 
ERROR <general>: 'timepart'
ERROR <general>: 
ERROR <general>: Exception ignored deletion of interned string failed
ERROR <general>: :
ERROR <general>: Traceback (most recent call last):
ERROR <general>:   File "/usr/lib/python3.10/sqlite3/dbapi2.py", line 83, in register_adapters_and_converters
ERROR <general>:     
ERROR <general>: register_converter("timestamp", convert_timestamp)
ERROR <general>: 
ERROR <general>: KeyError
ERROR <general>: : 
ERROR <general>: 'datepart'
ERROR <general>: 
ERROR <general>: Exception ignored deletion of interned string failed
ERROR <general>: :
ERROR <general>: Traceback (most recent call last):
ERROR <general>:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
ERROR <general>: KeyError
ERROR <general>: : 
ERROR <general>: 'convert_timestamp'
ERROR <general>: 
ERROR <general>: Exception ignored deletion of interned string failed
ERROR <general>: :
ERROR <general>: Traceback (most recent call last):
ERROR <general>:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
ERROR <general>: KeyError
ERROR <general>: : 
ERROR <general>: 'convert_date'
ERROR <general>: 
ERROR <general>: Exception ignored deletion of interned string failed
ERROR <general>: :
ERROR <general>: Traceback (most recent call last):
ERROR <general>:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
ERROR <general>: KeyError
ERROR <general>: : 
ERROR <general>: 'adapt_datetime'
ERROR <general>: 
ERROR <general>: Exception ignored deletion of interned string failed
ERROR <general>: :
ERROR <general>: Traceback (most recent call last):
ERROR <general>:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
ERROR <general>: KeyError
ERROR <general>: : 
ERROR <general>: 'adapt_date'
ERROR <general>: 
```
Nothing I can do from the PKC-side of things for now. 

Kodi seems to be using your Linux' Python installation (and not its own). That in version 3.10, where the Python modul `sqlite3` seems to have experienced some changes. Try to downgrade to something like 3.8 and try again (minimal requirement for PKC is Python >= 3.6).

**Comment by lmarianski** [comment]
ah, ok, it does look like my python update from 3.9 to 3.10 recently

**Comment by lmarianski** [comment]
huh, looks like its a bug in python: https://bugs.python.org/issue46070

**Comment by lmarianski** [comment]
Ok, i was able to temporarily solve it by downgrading to `3.10.0`, but an actual fix needs to happen in python itself apparently
