### ISSUE TITLE
Unauthorized PMS

### ISSUE THREAD

**Issue by kitn9** [croneter/PlexKodiConnect#1773]
I installed PKC on my windows PC running the latest  Kodi Matrix. I selected a Plex server that my friend shared with me and finished the setup. Once I restarted the Kodi app and tried playing a movie, it kept giving me a play error and also an Unauthorized PMS error. I attached the trimmed log file that says error 401. I have no idea what that is and it would be great if someone can help me out.

PS: Later I tried selecting my personal server and I was able to play my files perfectly
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7869948/kodi.log)

**Comment by croneter** [comment]
You probably selected a Plex user that is not authorized for your friends PMS. Go to Add-ons - Video Add-ons - PlexKodiConnect. Select "Sign out User XXXXX“

**Comment by kitn9** [comment]
> You probably selected a Plex user that is not authorized for your friends PMS. Go to Add-ons - Video Add-ons - PlexKodiConnect. Select "Sign out User XXXXX“

I tried that but it still gives unauthorized for PMS error :(

**Comment by croneter** [comment]
Please try again: Log out, reboot Kodi, make TRIPPLE sure you're selecting a Plex user that has credentials to access your friend's PMS

**Comment by kitn9** [comment]
> Please try again: Log out, reboot Kodi, make TRIPPLE sure you're selecting a Plex user that has credentials to access your friend's PMS

I reinstalled Kodi and repeated the whole process. I went into the advanced settings of PKC and did a reset of the addon. I am still getting the same error :( :(

I am attaching screenshots of the logged-in user proof and the error that comes after the unauthorized PMS error
![Screenshot 2022-01-14 232302](https://user-images.githubusercontent.com/97733598/149562915-e7f7a492-4b36-4f3b-9982-0aaeab39eace.jpg)
![Screenshot 2022-01-14 232507](https://user-images.githubusercontent.com/97733598/149562924-9aed0d36-c330-4cf9-a4ff-c04555e4ade9.jpg)
.

**Comment by croneter** [comment]
Using Plex Web, use the **same** Plex user as in PlexKodiConnect. Make tripple sure that you can access your friend's PMS and that you can play the video you can't play using PKC. 

Does that work?

**Comment by kitn9** [comment]
> Using Plex Web, use the **same** Plex user as in PlexKodiConnect. Make tripple sure that you can access your friend's PMS and that you can play the video you can't play using PKC.
> 
> Does that work?

I used Plex web and Plex on ATV to confirm that I can access my friend's library. However, it doesn't work on PKC on my PC :(
and I also made sure to select the right user on Kodi. 

I am trying to use PKC on my personal PC because I am planning to build an HTPC. I just wanted to confirm before starting the process.

**Comment by croneter** [comment]
This error should not be happening. Can you please share your entire DEBUG log please? See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
```
2022-01-14 16:26:32.599 T:4720    ERROR <general>: PLEX.websocket: pms_websocket: got an unexpected exception of type <class 'ValueError'>: scheme https is invalid
                                                   Traceback (most recent call last):
                                                     File "C:\Users\manoj\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_app.py", line 312, in run_forever
                                                       self.sock.connect(
                                                     File "C:\Users\manoj\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_core.py", line 260, in connect
                                                       self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                                                     File "C:\Users\manoj\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_http.py", line 102, in connect
                                                       hostname, port, resource, is_secure = parse_url(url)
                                                     File "C:\Users\manoj\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_url.py", line 68, in parse_url
                                                       raise ValueError("scheme %s is invalid" % scheme)
```

**Comment by kitn9** [comment]
> This error should not be happening. Can you please share your entire DEBUG log please? See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
> 
> ```
> 2022-01-14 16:26:32.599 T:4720    ERROR <general>: PLEX.websocket: pms_websocket: got an unexpected exception of type <class 'ValueError'>: scheme https is invalid
>                                                    Traceback (most recent call last):
>                                                      File "C:\Users\manoj\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_app.py", line 312, in run_forever
>                                                        self.sock.connect(
>                                                      File "C:\Users\manoj\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_core.py", line 260, in connect
>                                                        self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
>                                                      File "C:\Users\manoj\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_http.py", line 102, in connect
>                                                        hostname, port, resource, is_secure = parse_url(url)
>                                                      File "C:\Users\manoj\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_url.py", line 68, in parse_url
>                                                        raise ValueError("scheme %s is invalid" % scheme)
>                                                    ValueError: scheme https is invalid
> ```

Thank you so much for your reply. I am attaching the full 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/8050505/kodi.log)
KODI log.

**Comment by croneter** [comment]
I need DEBUG Kodi log files as explained above. Please enable Kodi debug logging, then restart Kodi, then reproduce the issue and share the log. 

See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Where did you get/download your Kodi?

**Comment by kitn9** [comment]
> I need a DEBUG Kodi log files as explained above. Please enable Kodi debug logging, then restart Kodi, then reproduce the issue and share the log.
> 
> See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Really sorry, I thought I had turned it on. Attaching the debug log.

Btw I downloaded KODI on the kodi.tv website

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/8077294/kodi.log)

**Comment by kitn9** [comment]
> Where did you get/download your Kodi?

I got a new Odroid N2+ and I am running coreElec on it. I installed pkc on it and I am still running into the same problem. I think it has something to do with my friends sever. 

Could you please help me out? I don’t understand why it isn’t working :(

**Comment by croneter** [comment]
Sorry it took so long to reply - kinda busy. 

This is really confusing:
```
PLEX.websocket: uri to connect pms websocket: ws://plex.yyyyy.in:80/:/websockets/notifications
...
ValueError: scheme https is invalid
```
The scheme is NOT `https` but `ws`...

Can you try to connect to your PMS via HTTPS instead of only HTTP?

**Comment by kitn9** [comment]
> Sorry it took so long to reply - kinda busy.
> 
> This is really confusing:
> 
> ```
> PLEX.websocket: uri to connect pms websocket: ws://plex.yyyyy.in:80/:/websockets/notifications
> ...
> ValueError: scheme https is invalid
> ```
> 
> The scheme is NOT `https` but `ws`...
> 
> Can you try to connect to your PMS via HTTPS instead of only HTTP?

Thank you for your reply.

So if I have to switch to Https I will be needing the SSL certificate right? So I asked my friend to send me the certificate and he sent me a .der file from his cloudflare account. However, when I added the .der file location in PKC settings I tried manually entering the url and selected the HTTPS option, but it gives an error: can’t validate the certificate. Can you tell me if I am doing something wrong here?

**Comment by croneter** [comment]
Unfortunately, this is not how HTTPS works. I VERY highly advise you and even more your friend to use SSL/HTTPS. Otherwise, anyone could potentially listen in on you communicating with the PMS. you really don't want that.

I can fix the issue here if I find the time. But again: use HTTPS. I can't tell you how, that's way too complicated and not a PKC-only thing, sorry

**Comment by kitn9** [comment]
> Unfortunately, this is not how HTTPS works. I VERY highly advise you and even more your friend to use SSL/HTTPS. Otherwise, anyone could potentially listen in on you communicating with the PMS. you really don't want that.
> 
> I can fix the issue here if I find the time. But again: use HTTPS. I can't tell you how, that's way too complicated and not a PKC-only thing, sorry

Actually he said he is using HTTPS. When I open his website manually on a browser it is redirecting me to a  HTTPS website. 

I am guessing the problem occurs when I try to play something. Because the sync is happening normally. Anything else I can do to fix the playback?

**Comment by croneter** [comment]
Yes, for now, switch to https 😆

**Comment by kitn9** [comment]
Can someone please help me out here?

The server itself is using HTTPS but I don't understand how to properly add the certificate in Kodi :(

**Comment by kitn9** [comment]
> Unfortunately, this is not how HTTPS works. I VERY highly advise you and even more your friend to use SSL/HTTPS. Otherwise, anyone could potentially listen in on you communicating with the PMS. you really don't want that.
> 
> I can fix the issue here if I find the time. But again: use HTTPS. I can't tell you how, that's way too complicated and not a PKC-only thing, sorry

Hey,

Can you point out where this is all going wrong? :/

**Comment by mbianucci** [comment]
Hi, it seems like I'm facing this same issue with the same setup - Windows 10 latest Matrix install, friend's server, etc. Looking at the logs, I also see the same sequence (see [`doesnt_play_kodi.log`](https://github.com/croneter/PlexKodiConnect/files/10088345/doesnt_play_kodi.log)):

```txt
2022-11-24 21:56:55.150 T:13608   DEBUG <general>: PLEX.websocket: uri to connect pms websocket: ws://<numbers>.<server_domain>.com:80/:/websockets/notifications
...
2022-11-24 21:56:55.291 T:13608   ERROR <general>: PLEX.websocket: pms_websocket: got an unexpected exception of type <class 'ValueError'>: scheme https is invalid
                                                   Traceback (most recent call last):
                                                     File "C:\<my_pc_path>\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_app.py", line 312, in run_forever
                                                       self.sock.connect(
                                                     File "C:\<my_pc_path>\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_core.py", line 260, in connect
                                                       self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
                                                     File "C:\<my_pc_path>\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_http.py", line 102, in connect
                                                       hostname, port, resource, is_secure = parse_url(url)
                                                     File "C:\<my_pc_path>\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\websocket\_url.py", line 68, in parse_url
                                                       raise ValueError("scheme %s is invalid" % scheme)
                                                   ValueError: scheme https is invalid
```

Also, I think I have HTTPS turned on already - I say _think_ because it depends on how I view the settings, if it is "turned on" or not. If I do Add-ons>Long press on PKC>Settings, it says it is turned on. If I do Add-ons>PKC>Settings, it shows off. Additionally, if I try to turn it on, after hitting ok I just get the spinning icon forever. I added [`forever_loading.log`](https://github.com/croneter/PlexKodiConnect/files/10088343/forever_loading.log) for that, in case anything is useful there.

A couple more things that may be noteworthy while trying to get to the bottom of this:
- AFAIK, transcoding from this server will never work. I see some logs that suggest maybe transcoding is happening, but not totally sure if that's normal or not (I believe the file I'm playing shouldn't require it, and I have Direct Play on).
  - I don't know if a 401 would be expected when transcoding is attempted though, seems kind like a weird response?
- Not sure if I need to try to set the server address etc manually or not. I've tried setting it but get various errors or infinite loading icon. I tried a few things in my browser just to see what works, and this is what I got:
    - `<numbers>.<server_domain>.com:80` - Works as expected to visit plex and watch movies
    - `<numbers>.<server_domain>.com:443` - 400 bad request
    - `https://<numbers>.<server_domain>.com:80` - `The connection for this site is not secure`
    - `https://<numbers>.<server_domain>.com:443` - Works as expected to visit plex and watch movies

Maybe that last bit isn't really useful or interesting after all, but networking is not something I know much about, so erring on the side of too much info rather than not enough.

**Comment by Schnielz** [comment]
Hi, I ran into the same issues. Connection via Browser is working but pkc won't connect stating the user is not allowed to connect (wich is not true). I don't use https as I connect via a secured VPN. Do I really need to create another certificate? How to even make a fire tv stick trust a self signed certificate...?
