### ISSUE TITLE
Skip Items - Unstable db warning still there in 1.5.6

### ISSUE THREAD

**Issue by dettwild** [croneter/PlexKodiConnect#183]
Hi
Last night I installed the latest PKC beta 1.5.6 to my RPI2 Libreelec 7.9.010 (containing Krypton beta 7) and did the mandated full db rebuild. Returning to Kodi after a while, I saw the error message on screen that some items had to be skipped and that db may be unstable.
I checked the logfile and believe the following extract to contain the relevant error:

`00:35:48.782 T:1437897632  NOTICE: PLEX.librarysync -> Starting sync threads
00:35:48.795 T:1437897632  NOTICE: PLEX.librarysync -> 1 download threads spawned
00:35:48.809 T:1437897632  NOTICE: PLEX.librarysync -> Processing thread spawned
00:35:48.816 T:1437897632  NOTICE: PLEX.librarysync -> Kodi Infobox thread spawned
00:35:51.337 T:1602122656  NOTICE: PLEX.artwork -> DEBUG:: Cached art: https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ1MzYyMjQ0Nl5BMl5BanBnXkFtZTcwMTA0ODkyMg@@._V1._SX400_.jpg
00:35:51.553 T:1602122656  NOTICE: PLEX.artwork -> DEBUG:: Cached art: https://images-na.ssl-images-amazon.com/images/M/MV5BMjU3ODIxNzEyNl5BMl5BanBnXkFtZTgwNTg1Nzg4NjE@._V1._SX400_.jpg
00:35:52.004 T:1602122656  NOTICE: PLEX.artwork -> DEBUG:: Cached art: https://images-na.ssl-images-amazon.com/images/M/MV5BMTk4NTE3MjEwMF5BMl5BanBnXkFtZTYwODkzNTkz._V1._SX400_.jpg
00:36:03.860 T:1874850720  NOTICE: PLEX.utils -> ERROR:: add_updateSeason has crashed. Error: database is locked
00:36:06.780 T:1874850720  NOTICE: PLEX.utils -> ERROR:: Traceback:
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 855, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/itemtypes.py", line 699, in add_updateSeason
                                                seasonid = self.kodi_db.addSeason(showid, seasonnum)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/kodidb_functions.py", line 1247, in addSeason
                                                self.cursor.execute(query, (showid, seasonnumber,))
                                            OperationalError: database is locked
00:36:06.793 T:1874850720  NOTICE: PLEX.utils -> ERROR:: add_updateSeason has crashed. Error: database is locked
00:36:06.798 T:1874850720  NOTICE: PLEX.utils -> ERROR:: Traceback:
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 855, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/itemtypes.py", line 699, in add_updateSeason
                                                seasonid = self.kodi_db.addSeason(showid, seasonnum)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/kodidb_functions.py", line 1247, in addSeason
                                                self.cursor.execute(query, (showid, seasonnumber,))
                                            OperationalError: database is locked
00:36:06.801 T:1874850720  NOTICE: PLEX.utils -> ERROR:: add_updateSeason has crashed. Error: database is locked`

another example (this time add_update crashing)  would be this:

`00:53:56.930 T:1437897632  NOTICE: PLEX.utils -> ERROR:: add_update has crashed. Error: database is locked
00:53:56.938 T:1437897632  NOTICE: PLEX.utils -> ERROR:: Traceback:
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 855, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/itemtypes.py", line 402, in add_update
                                                artwork.addArtwork(API.getAllArtwork(), movieid, "movie", kodicursor)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/artwork.py", line 355, in addArtwork
                                                cursor=cursor)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/artwork.py", line 401, in addOrUpdateArt
                                                self.deleteCachedArtwork(url)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/artwork.py", line 434, in deleteCachedArtwork
                                                (url,))
                                            OperationalError: database is locked
`

Note: I am not sure why the database is marked as locked - perhaps a performance issue?
Or is this something that 'can' happen and just needs to be handled, e.g. by waiting a bit?
Anyhow, it may also be worth to mentioned that I have set up my RPi 2 to use a USB stick as storage location instead of the default that writes everything to the system SD card. However, I believe this actually improves performance rather than possibly causing the locking.

I hope the above pasted error messages help to find and fix the reason for the crashes.
If needed, I could also provide the entire 23 MB logfile, but at the moment I see little value in that.

Thanks

**Comment by croneter** [comment]
Ouh, it really is another process locking the Kodi DB. I can increase the waiting time.

**Comment by dettwild** [comment]
Happy to try that as I really don't know what other process would be locking the db.
Will that require a new Beta release or is there somewhere a setting for that? If you tell me where I guess I could also edit the respective *.py file.
Also, perhaps it would make sense to not just increase the waiting time, but have a controlled skip in the code to reduce the errors.

**Comment by croneter** [comment]
In `utils.py`, change this part:
```
def kodiSQL(media_type="video"):

    if media_type == "plex":
        dbPath = tryDecode(xbmc.translatePath("special://database/plex.db"))
    elif media_type == "music":
        dbPath = getKodiMusicDBPath()
    elif media_type == "texture":
        dbPath = tryDecode(xbmc.translatePath(
            "special://database/Textures13.db"))
    else:
        dbPath = getKodiVideoDBPath()

    connection = sqlite3.connect(dbPath, timeout=15.0)
    return connection
```

Try doubling the `timeout=15.0` to `timeout=30.0`
