### ISSUE TITLE
Can not get pin from plex.tv

### ISSUE THREAD

**Issue by zid99825** [croneter/PlexKodiConnect#1848]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
an error message shown "Could not sign in to plex.tv. Try again later"

## To Reproduce
1. install PlexKodiConnect in Kodi 19.4
2. start plugin
3. auto display plex link page

## Expected behavior
new install from kodi 19.4 on xbox, can not get the link pin when setup plex

## You need to attach a KODI LOG FILE!
A Kodi debug log file is needed that you recorded while you reproduced the bug. **Do clean your log of all Plex tokens (="Plex passwords")!!!** .

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/8824162/kodi.log)

**Comment by croneter** [comment]
Thanks for the report! Is it possible that the device name in the PKC settings contains non-ASCII characters...?

```
2022-06-02 21:15:14.916 T:6868  WARNING <general>: PLEX.download: Traceback (most recent call last):
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\downloadutils.py", line 171, in downloadUrl
                                                       r = self._doDownload(s, action_type, **kwargs)
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\downloadutils.py", line 103, in _doDownload
                                                       r = s.post(**kwargs)
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.requests\lib\requests\api.py", line 119, in post
                                                       return request('post', url, data=data, json=json, **kwargs)
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.requests\lib\requests\api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.requests\lib\requests\sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.requests\lib\requests\sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.requests\lib\requests\adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 699, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 394, in _make_request
                                                       conn.request(method, url, **httplib_request_kw)
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.urllib3\lib\urllib3\connection.py", line 234, in request
                                                       super(HTTPConnection, self).request(method, url, body=body, headers=headers)
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.4.0.70_x64__4n2hpmxwrvr6p\system\python\lib\http\client.py", line 1255, in request
                                                       self._send_request(method, url, body, headers, encode_chunked)
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.4.0.70_x64__4n2hpmxwrvr6p\system\python\lib\http\client.py", line 1296, in _send_request
                                                       self.putheader(hdr, value)
                                                     File "Q:\Users\UserMgr1\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.module.urllib3\lib\urllib3\connection.py", line 219, in putheader
                                                       _HTTPConnection.putheader(self, header, *values)
                                                     File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_19.4.0.70_x64__4n2hpmxwrvr6p\system\python\lib\http\client.py", line 1228, in putheader
                                                       values[i] = one_value.encode('latin-1')
                                                   UnicodeEncodeError: 'latin-1' codec can't encode character '\u7684' in position 9: ordinal not in range(256)
```

**Comment by zid99825** [comment]
Yes, there is an Chinese character in device name. it fixed after changing the device name, Thx

**Comment by croneter** [comment]
I reopened because you should not even be able to enter invalid characters 😉

**Comment by zid99825** [comment]
those characters are from xbox console name, it can be set in any characters. just like "XXX的Xbox", then you get the device name like "Kodi(XXX的Xbox)" in the PKC settings
