### ISSUE TITLE
Issues replacing an episode with better quality

### ISSUE THREAD

**Issue by Mibix** [croneter/PlexKodiConnect#1871]
So my server will frequently grab a tv show then sometimes very shortly after grab a replacement for the exact same episode that has better sound or video and it will replace the old file with the new(usually slightly different file name).   It will say unable to locate file, want to delete? If you do delete it, that makes it impossible to get it back in to Kodi without a full resync of the plexkodiconnect library so I never chose to do that. Sometimes  a perform manual library sync will work to fix this, usually not.   If you go to the context menu and play from PMS, like the FAQ says, it doesn't even ask you to pick a version but it will play.  After that, you still can't play it normally without the play from PMS option.  The only way I've found to fix this is to manually find the file, add a .plexignore to the end of the file extension, wait for it to disappear from plex and Kodi, then remove the file extension, and wait for the file to reappear.  

I would expect this to just be able to resync with plex and play the version without need for manual adjustments.

The attached log file is me hitting it when it says it can't locate the file (big sky episode), playing it with the play in PMS from the context menu, trying to play it with two different players in kodi (dsplayer and default).
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/9880660/kodi.log)

**Comment by croneter** [comment]
Sorry it took me so long. This is your issue:
```
10:57:39.315 T:7976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'xbmc.Player' object has no attribute 'isExternalPlayer'
                                            Traceback (most recent call last):
                                              File "C:\Users\Mibix\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\kodimonitor.py", line 70, in onNotification
                                                self.PlayBackStart(data)
                                              File "C:\Users\Mibix\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\kodimonitor.py", line 363, in PlayBackStart
                                                status['external_player'] = app.APP.player.isExternalPlayer() == 1
                                            AttributeError: 'xbmc.Player' object has no attribute 'isExternalPlayer'
                                            -->End of Python script error report<--
```
You seem to be using a "non standard" Kodi installation. I just checked with the latest official Kodi Nexus Release Candidate build from kodi.tv. I cannot replicate your issue. Whatever build of Kodi you're using, it's missing the `isExternalPlayer` method (source code see here: https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/legacy/Player.cpp). Nothing I can do from my side, sorry.

**Comment by croneter** [comment]
Solution for you: use a newer Kodi! You're trying a version 17.6. There's a 20 out already!
```
10:49:01.505 T:13280  NOTICE: Starting Kodi (17.6 Git:20171126-13194ec). Platform: Windows NT x86 64-bit
```

**Comment by jaimbo** [comment]
I have been experiencing the same issue for a while now where a file is upgraded to a higher quality and the file name changes, then Kodi can no longer find the old file and doesn't seem to sync the new file name to the database.

I don't have the above error and am using the latest release of Kodi Nexus. I have reviewed my kodi.log and searched for an episode that I know currently has this issue and found the following:

`2022-12-27 20:08:28.079 T:21309   error <general>: SQL: [Textures13.db] SQLite error SQLITE_CORRUPT (database disk image is malformed)
                                                   Query: SELECT id, cachedurl, lasthashcheck, imagehash, width, height FROM texture JOIN sizes ON (texture.id=sizes.idtexture AND sizes.size=1) WHERE url='http://ip:port/photo/:/transcode?width=1920&height=1920&minSize=1&upscale=0&url=/library/metadata/19321/thumb/1672159766&X-Plex-Token=x'
2022-12-27 20:08:28.079 T:21309   error <general>: GetCachedTexture, failed on url 'http://ip:port/photo/:/transcode?width=1920&height=1920&minSize=1&upscale=0&url=/library/metadata/19321/thumb/1672159766&X-Plex-Token=x'
2022-12-27 20:08:28.088 T:21309   debug <general>: CCurlFile::GetMimeType - <http://ip:port/photo/:/transcode?width=1920&height=1920&minSize=1&upscale=0&url=/library/metadata/19321/thumb/1672159766&X-Plex-Token=x> -> image/jpeg
2022-12-27 20:08:28.090 T:21309   debug <general>: CurlFile::Open - <http://ip:port/photo/:/transcode?width=1920&height=1920&minSize=1&upscale=0&url=/library/metadata/19321/thumb/1672159766&X-Plex-Token=x>
2022-12-27 20:08:28.094 T:21309   debug <general>: ffmpeg[0x2a3de99b10]: [image2] Custom AVIOContext makes no sense and will be ignored with AVFMT_NOFILE format.
2022-12-27 20:08:28.107 T:21309   debug <general>: Caching image 'http://ip:port/photo/:/transcode?width=1920&height=1920&minSize=1&upscale=0&url=/library/metadata/19321/thumb/1672159766&X-Plex-Token=x' to '9/923bd8f7.jpg':
2022-12-27 20:08:28.107 T:21309   debug <general>: cached image 'special://masterprofile/Thumbnails/9/923bd8f7.jpg' size 640x360
2022-12-27 20:08:28.130 T:21309   error <general>: SQL: [Textures13.db] SQLite error SQLITE_CORRUPT (database disk image is malformed)
                                                   Query: DELETE FROM texture WHERE url='http://ip:port/photo/:/transcode?width=1920&height=1920&minSize=1&upscale=0&url=/library/metadata/19321/thumb/1672159766&X-Plex-Token=x' (database disk image is malformed)
2022-12-27 20:08:28.130 T:21309   error <general>: AddCachedTexture failed on url 'http://192.168.0.4:port/photo/:/transcode?width=1920&height=1920&minSize=1&upscale=0&url=/library/metadata/19321/thumb/1672159766&X-Plex-Token=wzMBcFpUNzkzRoL9ZBNs'`

**Comment by Mibix** [comment]
> Solution for you: use a newer Kodi! You're trying a version 17.6. There's a 20 out already!
> 
> ```
> 10:49:01.505 T:13280  NOTICE: Starting Kodi (17.6 Git:20171126-13194ec). Platform: Windows NT x86 64-bit
> ```

This is the newest version with Kodi DSPLayer(MadVR).  Newer versions still are terrible with HDR content.

**Comment by croneter** [comment]
17.6 is way too old, you really should upgrade to Kodi 19

Im using Marven's build e.g. for Dolby Vision-support, check out https://www.kodinerds.net/index.php/Thread/69428-Maven-s-Kodi-Builds-f%C3%BCr-Android/

**Comment by Mibix** [comment]
> 17.6 is way too old, you really should upgrade to Kodi 19
> 
> Im using Marven's build e.g. for Dolby Vision-support, check out https://www.kodinerds.net/index.php/Thread/69428-Maven-s-Kodi-Builds-f%C3%BCr-Android/

That is for Android not Windows unfortunately
