### ISSUE TITLE
Library not updated

### ISSUE THREAD

**Issue by xefil** [croneter/PlexKodiConnect#19]
Hello,
I've setup a fresh Kodi installation and installed this plugin. Seems all works, but the library is not updated.
In the log I can see:

```
 17:36:07 T:139689299494656  NOTICE: PlexKodiConnect Service -> ======== START PlexKodiConnect ========
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect Service -> Platform: Linux
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect Service -> KODI Version: 16.0 Git:Unknown
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect Service -> PlexKodiConnect Version: 1.1.5
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect Service -> Using plugin paths: True
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect Service -> Log Level: 1
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect VideoNodes -> Clearing nodes properties.
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect InitialSetup -> Initial setup called.
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect UserClient -> Returning active server: https://<STRING_CUTTED_BY_ME>.plex.direct:32400
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect InitialSetup -> Found plex.tv token in settings
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect PlexAPI -> Checking connection to server https://plex.tv/api/home/users with verifySSL=None
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect ClientInfo -> Unique device Id plex_client_Id loaded: <STRING_CUTTED_BY_ME>
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect PlexAPI -> Checking connection successfull. Answer: 200
    17:36:07 T:139689299494656  NOTICE: PlexKodiConnect InitialSetup -> plex.tv connection with token successful
    17:36:08 T:139689299494656  NOTICE: PlexKodiConnect InitialSetup -> Updated Plex info from plex.tv
    17:36:08 T:139689299494656  NOTICE: PlexKodiConnect InitialSetup -> Server is already set.
    17:36:08 T:139689299494656  NOTICE: PlexKodiConnect InitialSetup -> url: https://<STRING_CUTTED_BY_ME>.plex.direct:32400, Plex machineIdentifier: <STRING_CUTTED_BY_ME>
    17:36:08 T:139689299494656  NOTICE: PlexKodiConnect UserClient -> Returning active server: https://<STRING_CUTTED_BY_ME>.plex.direct:32400
    17:36:08 T:139689299494656  NOTICE: PlexKodiConnect PlexAPI -> Checking connection to server https://<STRING_CUTTED_BY_ME>.plex.direct:32400/library/onDeck with verifySSL=None
    17:36:08 T:139689299494656  NOTICE: PlexKodiConnect PlexAPI -> Checking connection successfull. Answer: 401
    17:36:08 T:139689299494656  NOTICE: PlexKodiConnect Service -> Server https://<STRING_CUTTED_BY_ME>.plex.direct:32400 is online and ready.
    17:36:08 T:139687696000768  NOTICE: PlexKodiConnect UserClient -> ----===## Starting UserClient ##===----
    17:36:08 T:139687696000768  NOTICE: PlexKodiConnect UserClient -> Authenticating user
    17:36:08 T:139687696000768  NOTICE: PlexKodiConnect UserClient -> Returning active server: https://<STRING_CUTTED_BY_ME>.plex.direct:32400
    17:36:08 T:139687696000768  NOTICE: PlexKodiConnect UserClient -> Trying to authenticate with old settings
    17:36:08 T:139687696000768  NOTICE: PlexKodiConnect UserClient -> Loading current user
    17:36:08 T:139687696000768  NOTICE: PlexKodiConnect UserClient -> Returning active server: https://<STRING_CUTTED_BY_ME>.plex.direct:32400
    17:36:08 T:139687696000768  NOTICE: PlexKodiConnect UserClient -> Testing validity of current token
    17:36:08 T:139687696000768  NOTICE: PlexKodiConnect PlexAPI -> Checking connection to server https://<STRING_CUTTED_BY_ME>.plex.direct:32400/library/onDeck with verifySSL=None
    17:36:09 T:139687696000768  NOTICE: PlexKodiConnect PlexAPI -> Checking connection successfull. Answer: 401
    17:36:09 T:139687696000768   ERROR: PlexKodiConnect UserClient -> Token is no longer valid
    17:36:09 T:139687696000768  NOTICE: PlexKodiConnect UserClient -> Failed to use the settings credentials. Deleting them
    17:36:09 T:139687696000768  NOTICE: PlexKodiConnect UserClient -> Trying to connect to plex.tv to get a user list
    17:36:09 T:139689299494656  NOTICE: PlexKodiConnect Service -> Not authenticated yet.
    17:36:26 T:139687696000768  NOTICE: PlexKodiConnect PlexAPI -> Selected user: <STRING_CUTTED_BY_ME>
    17:36:26 T:139687696000768  NOTICE: PlexKodiConnect PlexAPI -> Asking for users PIN
    17:36:34 T:139687696000768  NOTICE: PlexKodiConnect PlexAPI -> Switching to user <STRING_CUTTED_BY_ME>
    17:36:34 T:139687696000768   ERROR: Exception in thread Thread-4:
                                                Traceback (most recent call last):
                                                  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
                                                    self.run()
                                                  File "/home/kodi/.kodi/addons/PlexKodiConnect-develop/resources/lib/userclient.py", line 384, in run
                                                    if self.authenticate():
                                                  File "/home/kodi/.kodi/addons/PlexKodiConnect-develop/resources/lib/userclient.py", line 293, in authenticate
                                                    userInfo = plx.ChoosePlexHomeUser(plextoken)
                                                  File "/home/kodi/.kodi/addons/PlexKodiConnect-develop/resources/lib/PlexAPI.py", line 854, in ChoosePlexHomeUser
                                                    utils.settings('plex_machineIdentifier'))
                                                  File "/home/kodi/.kodi/addons/PlexKodiConnect-develop/resources/lib/PlexAPI.py", line 933, in PlexSwitchHomeUser
                                                    headerOptions={'X-Plex-Token': token})
                                                TypeError: downloadUrl() got an unexpected keyword argument 'type'

```
So what's wrong?
Thanks!
Simon

**Comment by xefil** [comment]
If I try a manual library scan:

```
17:58:45 T:139687696000768  NOTICE: Using Image Cache Thread Count: 25 -> 1
17:58:45 T:139687696000768  NOTICE: plugin.video.plexkodiconnect started
17:58:45 T:139687696000768  NOTICE: PlexKodiConnect - Full sys.argv received: ['plugin://plugin.video.plexkodiconnect/', '4', '?mode=manualsync']
17:58:45 T:139687696000768  NOTICE: PlexKodiConnect - Parameter string: ?mode=manualsync
17:58:45 T:139687696000768  NOTICE: PLEX -> Requesting full library scan
17:58:45 T:139687696000768  NOTICE: plugin.video.plexkodiconnect stopped
17:58:45 T:139690315831808   ERROR: GetDirectory - Error getting plugin://plugin.video.plexkodiconnect/?mode=manualsync
17:58:45 T:139690315831808   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexkodiconnect/?mode=manualsync) failed
17:58:45 T:139687696000768  NOTICE: Using Image Cache Thread Count: 25 -> 1
17:58:45 T:139687696000768  NOTICE: plugin.video.plexkodiconnect started
17:58:45 T:139687696000768  NOTICE: PlexKodiConnect - Full sys.argv received: ['plugin://plugin.video.plexkodiconnect/', '5', '?content_type=video']
17:58:45 T:139687696000768  NOTICE: PlexKodiConnect - Parameter string: ?content_type=video
17:58:45 T:139687696000768  NOTICE: plugin.video.plexkodiconnect stopped
```

My system:

Fedora 23
Kodi 16.0 (default installation, first plugin this one)
Python 2.7.11

Thanks
Simon

**Comment by croneter** [comment]
You found a bug, that's the first log you posted. I hope the second is connected to that. Thanks for sharing!

**Comment by xefil** [comment]
Oh great to help!
Meanwhile I've opened Firefox and used there for a moment Plex.
Then, back to KODI and it has started to sync. I don't know if it's related.
Then, I've tried to start play a stream, but:

```
19:30:07 T:139710004328192  NOTICE: Using Image Cache Thread Count: 25 -> 1
19:30:07 T:139710004328192  NOTICE: Parameter string: ?dbid=95&mode=play&id=2974&filename=<STRING_CUTTED_BY_ME>.mkv
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect DownloadUtils -> Request session does not exist: start one
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect DownloadUtils -> Verify SSL certificates set to: true
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect DownloadUtils -> SSL client side certificate set to: None
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect DownloadUtils -> Set server: https://<STRING_CUTTED_BY_ME>.plex.direct:32400
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect DownloadUtils -> Set token: xxxxxxx
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect DownloadUtils -> Set userId: <STRING_CUTTED_BY_ME>
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect DownloadUtils -> Set username: <STRING_CUTTED_BY_ME>
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect DownloadUtils -> Requests session started on: https://<STRING_CUTTED_BY_ME>.plex.direct:32400
19:30:07 T:139710004328192  NOTICE: Using Image Cache Thread Count: 25 -> 1
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect PlaybackUtils -> Play called.
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect PlayUtils -> Kodi cannot access file None - no direct play
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect PlayUtils -> The add-on settings bitrate is: 320, the video bitraterequired is: 1215
19:30:07 T:139710004328192  NOTICE: PlexKodiConnect PlayUtils -> The network speed is insufficient to direct stream file. Transcoding
19:30:08 T:139710004328192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect.tvshows/default.py", line 41, in <module>
                                                entrypoint.doPlayback(itemid, dbid)
                                              File "/home/kodi/.kodi/addons/PlexKodiConnect-develop/resources/lib/entrypoint.py", line 268, in doPlayback
                                                return pbutils.PlaybackUtils(xml).play(itemid, dbid)
                                              File "/home/kodi/.kodi/addons/PlexKodiConnect-develop/resources/lib/playbackutils.py", line 59, in play
                                                playurl = playutils.getPlayUrl()
                                              File "/home/kodi/.kodi/addons/PlexKodiConnect-develop/resources/lib/playutils.py", line 58, in getPlayUrl
                                                elif self.isTranscoding():
                                              File "/home/kodi/.kodi/addons/PlexKodiConnect-develop/resources/lib/playutils.py", line 221, in isTranscoding
                                                if not self.item['MediaSources'][0]['SupportsTranscoding']:
                                              File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 266, in __getitem__
                                                return self._children[index]
                                            TypeError: list indices must be integers, not str
                                            -->End of Python script error report<--
19:30:08 T:139710692825600   ERROR: PlayMedia could not play media: plugin://plugin.video.plexkodiconnect.tvshows/2966/?dbid=95&mode=play&id=2974&filename=<STRING_CUTTED_BY_ME>.mkv
```

Something related?

Simon

**Comment by croneter** [comment]
No. To fix that last one, go to PKC settings, playback, and set quality to 1920x1080 40Mbps

**Comment by xefil** [comment]
Thanks croneter!! Suggestion works ;)

**Comment by xefil** [comment]
And thx for the update as well!
Cheers
