### ISSUE TITLE
issue with sync when episode title contains accented characters

### ISSUE THREAD

**Issue by davidacarter1984** [croneter/PlexKodiConnect#20]
hello

I keep getting an error popping up saying that some files were skipped during db sync.

extracts from the log with associated xml code retrieved from plex server for specific episodes

11:05:47 T:1544  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\PlexKodiConnect-develop\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\PlexKodiConnect-develop\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\PlexKodiConnect-develop\resources\lib\PlexAPI.py", line 1241, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 57: invalid start byte
11:05:47 T:1544   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 4089. Error:
11:05:47 T:1544   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xe4 in position 83: invalid continuation byte
11:05:47 T:1544  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\PlexKodiConnect-develop\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\PlexKodiConnect-develop\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\PlexKodiConnect-develop\resources\lib\PlexAPI.py", line 1241, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 83: invalid continuation byte
11:05:47 T:1544   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 4054. Error:
11:05:47 T:1544   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xe4 in position 83: invalid continuation byte
11:05:47 T:1544  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\PlexKodiConnect-develop\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\PlexKodiConnect-develop\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\PlexKodiConnect-develop\resources\lib\PlexAPI.py", line 1241, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 83: invalid continuation byte
11:05:47 T:1544   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 5272. Error:
11:05:47 T:1544   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xe1 in position 58: invalid continuation byte

[from plex.txt](https://github.com/croneter/PlexKodiConnect/files/244084/from.plex.txt)

**Comment by croneter** [comment]
Thanks! 

What PKC version were you using? Today's update should have solved this issue.

**Comment by davidacarter1984** [comment]
Am on the latest version as every I have to manually edit  one of the files that  is part of the companion to allow windows phone plex app to find kodi. I will have  annother look at the logs to see if  something else is also causing the error. Being a developer myself I prefer to narrow down errors as much as I can before saying  something doesn't work. Did you see the issue  Iposted yesterday?

**Comment by davidacarter1984** [comment]
I have added 2 more episodes which are still showing up in the logs to the attached file. as you can see one has a power and the other has an accented a in the name. I have made sure that I am up to date in the machine I took the logs from

22:16:14 T:4100   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 5301. Error:
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xb0 in position 62: invalid start byte
22:16:14 T:4100  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\PlexAPI.py", line 1240, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 62: invalid start byte
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 4089. Error:
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xe4 in position 83: invalid continuation byte
22:16:14 T:4100  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\PlexAPI.py", line 1240, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 83: invalid continuation byte
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 4584. Error:
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0x91 in position 87: invalid start byte
22:16:14 T:4100  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\PlexAPI.py", line 1240, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0x91 in position 87: invalid start byte
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 5272. Error:
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xe1 in position 58: invalid continuation byte
22:16:14 T:4100  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\PlexAPI.py", line 1240, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 58: invalid continuation byte
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 4700. Error:
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0x92 in position 57: invalid start byte
22:16:14 T:4100  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\PlexAPI.py", line 1240, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 57: invalid start byte
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 4054. Error:
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xe4 in position 83: invalid continuation byte
22:16:14 T:4100  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\PlexAPI.py", line 1240, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 83: invalid continuation byte
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 7857. Error:
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xf1 in position 95: invalid continuation byte
22:16:14 T:4100  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\PlexAPI.py", line 1240, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xf1 in position 95: invalid continuation byte
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 700. Error:
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xb2 in position 85: invalid start byte
22:16:14 T:4100  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\PlexAPI.py", line 1240, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xb2 in position 85: invalid start byte
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 2710. Error:
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xe0 in position 82: invalid continuation byte
22:16:14 T:4100  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\PlexAPI.py", line 1240, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 82: invalid continuation byte
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 2630. Error:
22:16:14 T:4100   ERROR: PlexKodiConnect Items -> 'utf8' codec can't decode byte 0xb2 in position 79: invalid start byte
22:16:14 T:4100  NOTICE: PlexKodiConnect Items -> Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1188, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1306, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                                              File "C:\Users\candd\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\PlexAPI.py", line 1240, in getFilePath
                                                res = unquote(res).decode('utf-8')
                                              File "C:\Program Files\Kodi\system\python\Lib\encodings\utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xb2 in position 79: invalid start byte

[from plex.txt](https://github.com/croneter/PlexKodiConnect/files/244352/from.plex.txt)
