### ISSUE TITLE
PKC won't start. Error message: "SyntaxError: future feature annotations is not defined"

### ISSUE THREAD

**Issue by Sk3tchs** [croneter/PlexKodiConnect#2006]
I get a error as soon as I load Kodi. The issues appeared after I adjusted the time on my NAS, but that my be a coincidence.

log : 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/13553459/kodi.log)

May be related to this : https://github.com/pannal/plex-for-kodi/issues/68

**Comment by Stern1900** [comment]
I have the same error

**Comment by megakroug** [comment]
same issue too, has anyone a solution ?

Thanks for your help !

**Comment by megakroug** [comment]
For not working plugin urllib3 module need to be downgraded (from 2.1.0 to 1.26.16 version: [https://mirrors.kodi.tv/addons/nexus/sc ... trix.1.zip](https://mirrors.kodi.tv/addons/nexus/script.module.urllib3/script.module.urllib3-1.26.16+matrix.1.zip)).
    Try to downgrade myconnpy module from 8.0.33 to 8.0.18 version: [https://mirrors.kodi.tv/addons/nexus/sc ... trix.1.zip](https://mirrors.kodi.tv/addons/nexus/script.module.myconnpy/script.module.myconnpy-8.0.18+matrix.1.zip) 

I replaced all the contents of the library 1.26.16 with the sudo command in the location /share/CACHEDEV1_DATA/.qpkg/Kodi20/opt/.kodi/addons/script.module.urllib3.

Everything works well  !!!

**Comment by Stern1900** [comment]
@megakroug Thank you for the detailed description

**Comment by simtaj** [comment]
For me Plexkodiconnect from today not work anymore. How did you solve the problem?

Is Plexkodiconnect dead ?

**Comment by simtaj** [comment]
@megakroug I tried as you suggested, but for me is not working. After plex link it gives me my local server and after choosing addon paths, goes to fine tuning settings page. But this setting page is all grey, so I cannot make any settings and PKC don’t work.

Do you have any suggestion ?
Thank you !

**Comment by croneter** [comment]
I will look into this issue

**Comment by croneter** [comment]
This might be separate issues. Your original issue, @Sk3tchs, stems from this error in the logs:
```
2023-12-05 10:26:57.165 T:14177   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'SyntaxError'>
Error Contents: future feature annotations is not defined (__init__.py, line 5)
Traceback (most recent call last):
 File "/opt/Kodi19L/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 4, in <module>
   from resources.lib import service_entry
 File "/opt/Kodi19L/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 10, in <module>
   from . import initialsetup
 File "/opt/Kodi19L/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/initialsetup.py", line 11, in <module>
   from .downloadutils import DownloadUtils as DU, exceptions
 File "/opt/Kodi19L/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/downloadutils.py", line 4, in <module>
   import requests
 File "/opt/Kodi19L/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
   import urllib3
 File "/opt/Kodi19L/.kodi/addons/script.module.urllib3/lib/urllib3/__init__.py", line 5
   from __future__ import annotations
                                    ^
SyntaxError: future feature annotations is not defined
-->End of Python script error report<--
```
There is NOTHING I can do about that as PKC is simply importing existing Python packages. The solution is found in comment https://github.com/croneter/PlexKodiConnect/issues/2006#issuecomment-1850540514 by @megakroug - thanks very much!!

@simtaj: Please share a DEBUG log file as described here, otherwise no-one can help you: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
On first glance I don't see anything special in your log, @simtaj - what did you do exactly and what was the issue when recording the log file?

**Comment by croneter** [comment]
Juck, that's bad luck @simtaj . Looks like Kodi and or PKC files got corrupted, that can happen. Try deleting the folder plugin.video.plexkodiconnect in the directory addon-data in your [Kodi user data folder](https://kodi.wiki/view/Userdata#Location) when Kodi is not running

**Comment by simtaj** [comment]
@croneter I did now as you said deleted folder plugin.video.plexkodiconnect but it didn’t help. All the same greyout settings.

Strange is, that it was like that same problem end of december. And copying urllib3 1.26 and clearing cache did help. Now problem come back and nothing helps….Does PKC with urllib3 2.1.0 works by you or you have to have version 1.26 too ?
Do you think that deleting KODI and clean install is the only solution ?

**Comment by croneter** [comment]
Thing is, PKC does not render the settings, that's Kodi itself. In your place I'd make a backup, then indeed try again from scratch with a completely fresh Kodi instance

**Comment by Stern1900** [comment]
I fixed it. Not relay good. But its work for me. In Kodi stoped update Adons. Install the Last Kodoconnect.
And follow 
For not working plugin urllib3 module need to be downgraded (from 2.1.0 to 1.26.16 version: [https://mirrors.kodi.tv/addons/nexus/sc ... trix.1.zip](https://mirrors.kodi.tv/addons/nexus/script.module.urllib3/script.module.urllib3-1.26.16+matrix.1.zip)).
Try to downgrade myconnpy module from 8.0.33 to 8.0.18 version: [https://mirrors.kodi.tv/addons/nexus/sc ... trix.1.zip](https://mirrors.kodi.tv/addons/nexus/script.module.myconnpy/script.module.myconnpy-8.0.18+matrix.1.zip)

I replaced all the contents of the library 1.26.16 with the sudo command in the location /share/CACHEDEV1_DATA/.qpkg/Kodi20/opt/.kodi/addons/script.module.urllib3.

Everything works well !!!  Not reals but its work.

**Comment by Stern1900** [comment]
What I don't understand is why you are using a different Phyton version than the original program. In the end, we all appreciate your work, but you can't program a plugin that nobody can us

**Comment by Stern1900** [comment]
> What I don't understand is why you are using a different Phyton version than the original 

> program. In the end, we all appreciate your work, but you can't program a plugin that nobody can us. Sorry but I am a little disappointed.
Wow now i undertsna the problem is QNAP. Under Windows its run like hell. 

/

**Comment by Stern1900** [comment]
I was sitting on my sofa thinking about why PKC is now using a different Python library than my KODI on my **QNAP NAS**. 
A quick test under Windows shows me that both programs work. So it's because of the KODI version installed on the **QNAP**. Officially **QNAP** does not support Kodi anymore.
So what to do:
I have disabled the update in KODI under Addons.
Then installed PKC 3.8.1.
Copy the files[https://mirrors.kodi.tv/addons/nexus/sc ... trix.1.zip](https://mirrors.kodi.tv/addons/nexus/script.module.urllib3/script.module.urllib3-1.26.16+matrix.1.zip)) and [https://mirrors.kodi.tv/addons/nexus/sc ... trix.1.zip](https://mirrors.kodi.tv/addons/nexus/script.module.myconnpy/script.module.myconnpy-8.0.18+matrix.1.zip) to share/CACHEDEV1_DATA/.qpkg/Kodi20/opt/.kodi/addons/ and everything works as usual.  Sorry for my bad english
