### ISSUE TITLE
PlexKodiConnect error: "SyntaxError: future feature annotations is not defined"

### ISSUE THREAD

**Issue by Stern1900** [croneter/PlexKodiConnect#2019]
And again i have a PlexKodi error.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/14053941/kodi.log
)And no idea what the problem is

**Comment by croneter** [comment]
Your issue is this:
```
2024-01-25 15:29:50.406 T:30282   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: future feature annotations is not defined (__init__.py, line 5)
                                                   Traceback (most recent call last):
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 4, in <module>
                                                       from resources.lib import service_entry
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 10, in <module>
                                                       from . import initialsetup
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/initialsetup.py", line 11, in <module>
                                                       from .downloadutils import DownloadUtils as DU, exceptions
                                                     File "/opt/Kodi20/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/downloadutils.py", line 4, in <module>
                                                       import requests
                                                     File "/opt/Kodi20/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                       import urllib3
                                                     File "/opt/Kodi20/.kodi/addons/script.module.urllib3/lib/urllib3/__init__.py", line 5
                                                       from __future__ import annotations
                                                                                        ^
                                                   SyntaxError: future feature annotations is not defined
                                                   -->End of Python script error report<--
```

**Comment by croneter** [comment]
This was reported in issue #2006 before. Unfortunately, it's an issue with different Python version - NOTHING PKC can do anything about, you need to fix it yourself (or hopefully Kodi fixes this in the future). 

The solution is described in https://github.com/croneter/PlexKodiConnect/issues/2006#issuecomment-1850540514. Please follow the steps detailed there
