### ISSUE TITLE
Sync had to skip some items warning in kodi. 

### ISSUE THREAD

**Issue by mvanbaak** [croneter/PlexKodiConnect#207]
Every time plexkodiconnect does a library scan I get a message:

Sync had to skip some items because they could not be processed. Kodi may be unstable now!

Kodi version: 17.0 Git 20170201-a10c504 (Installed with the installer downloaded from kodi.tv)
PlexKodiConnect version: 1.5.11 (installed using the beta channel)
OS: MacOS Sierra 10.12.4 beta (16E144f)
PMS version: 1.3.4.3285

Log:

```
20:16:45.689 T:123145432100864  NOTICE: PLEX.librarysync -> DEBUG:: self.updatelist: []
20:16:45.690 T:123145432100864  NOTICE: PLEX.librarysync -> DEBUG:: GetAndProcessXMLs completed for seasons
20:16:50.324 T:123145432100864  NOTICE: PLEX.librarysync -> DEBUG:: Analyzed all episodes of TV show with Plex Id 2
20:16:50.324 T:123145432100864  NOTICE: PLEX.librarysync -> DEBUG:: self.updatelist: [{'itemId': '23581', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Echoes', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23860', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'The Emotion Detection Automation', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23924', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Dulcinea', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23910', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'The Big Empty', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23932', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Remember the Cant', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23928', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'CQB', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23917', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Back to the Butcher', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23935', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Rock Bottom', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23921', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Windmills', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23913', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Salvage', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23904', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Critical Mass', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23905', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Leviathan Wakes', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23857', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Safe', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23906', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Doors & Corners', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23861', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': "Not Everything's About Annalise", 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23566', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Riders on the Storm', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23326', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'The Target', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23329', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'The Detail', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23333', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'The Buys', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23336', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Old Cases', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23340', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'The Pager', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23344', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'The Wire', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23348', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'One Arrest', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23352', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Lessons', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23356', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Game Day', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23359', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'The Cost', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23365', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'The Hunt', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23369', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Cleaning Up', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23373', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Sentencing', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23378', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Ebb Tide', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23383', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Collateral Damage', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23384', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Hot Shots', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23389', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Hard Cases', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23390', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Undertow', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23395', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'All Prologue', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23396', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Backwash', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23401', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Duck and Cover', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23402', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Stray Rounds', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23407', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Storm Warnings', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23408', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Bad Dreams', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23417', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Port in a Storm', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23466', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Time After Time', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23471', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'All Due Respect', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23474', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Dead Soldiers', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23479', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Amsterdam', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23482', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Straight and True', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23487', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Homecoming', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23492', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Back Burners', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23495', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Moral Midgetry', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23500', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Slapstick', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23503', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Reformation', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23508', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Middle Ground', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23511', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Mission Accomplished', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23517', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Boys of Summer', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23518', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Soft Eyes', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23523', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Home Rooms', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23524', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Refugees', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23529', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Alliances', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23532', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Margin of Error', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23537', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Unto Others', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23542', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Corner Boys', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23543', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Know Your Place', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23546', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Misgivings', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23551', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'A New Day', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23554', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': "That's Got His Own", 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23559', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Final Grades', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23425', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'More With Less', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23430', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Unconfirmed Reports', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23433', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Not For Attribution', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23436', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Transitions', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23441', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'React Quotes', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23444', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'The Dickensian Aspect', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23449', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Took', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23452', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Clarifications', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23457', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': 'Late Editions', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23460', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': '-30-', 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}, {'itemId': '23582', 'itemType': 'TVShows', 'viewName': u'TV Shows', 'title': "Bill & Tez's Sexcellent Sexventure", 'viewId': u'2', 'mediaType': 'episode', 'method': 'add_updateEpisode'}]
20:16:50.324 T:123145432100864  NOTICE: PLEX.librarysync -> Starting sync threads
20:16:50.349 T:123145432100864  NOTICE: PLEX.librarysync -> 10 download threads spawned
20:16:50.351 T:123145432100864  NOTICE: PLEX.librarysync -> Processing thread spawned
20:16:50.369 T:123145507819520  NOTICE: PLEX.itemtypes -> UPDATE episode itemid: 23860
20:16:50.370 T:123145507819520  NOTICE: PLEX.utils -> ERROR:: add_updateEpisode has crashed. Error: unrecognized token: ""
                                                            "
20:16:50.370 T:123145507819520  NOTICE: PLEX.utils -> ERROR:: Traceback:
                                            Traceback (most recent call last):
                                              File "/Volumes/mvanbaak/homedir/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 858, in wrapper
                                                return func(*args, **kwargs)
                                              File "/Volumes/mvanbaak/homedir/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/lib/itemtypes.py", line 931, in add_updateEpisode
                                                fileid, seasonid, userdata['UserRating'], episodeid))
                                            OperationalError: unrecognized token: ""
                                                            "
20:16:50.382 T:123145507819520  NOTICE: PLEX.itemtypes -> UPDATE episode itemid: 23904
20:16:50.382 T:123145507819520  NOTICE: PLEX.utils -> ERROR:: add_updateEpisode has crashed. Error: unrecognized token: ""
                                                            "
20:16:50.382 T:123145507819520  NOTICE: PLEX.utils -> ERROR:: Traceback:
                                            Traceback (most recent call last):
                                              File "/Volumes/mvanbaak/homedir/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 858, in wrapper
                                                return func(*args, **kwargs)
                                              File "/Volumes/mvanbaak/homedir/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/lib/itemtypes.py", line 931, in add_updateEpisode
                                                fileid, seasonid, userdata['UserRating'], episodeid))
                                            OperationalError: unrecognized token: ""
                                                            "
```

**Comment by mvanbaak** [comment]
Ah, I see this is probably fixed in 1.5.12. Updates are FAST man! Thanks!
