### ISSUE TITLE
UnicodeDecodeError in playlist_func.py for file path or plex library with cyrillic characters

### ISSUE THREAD

**Issue by SeyfSV** [croneter/PlexKodiConnect#229]
Version 1.6.0
```
21:02:54.344 T:1170469872  NOTICE: PLEX.default -> plugin.video.plexkodiconnect started
21:02:54.366 T:1340077040  NOTICE: PLEX.playback_starter -> Process_play called with plex_id 39392, kodi_id 49
21:02:54.406 T:1340077040  NOTICE: PLEX.playbackutils -> Playbackutils called
21:02:54.416 T:1340077040  NOTICE: PLEX.playutils -> videoCodec: {'videocodec': 'h264', 'container': 'mkv', 'bitrate': '11589', 'height': '1040', 'width': '1920', 'bitDepth': '8', 'aspectratio': None, 'resolution': '1080'}
21:02:54.433 T:1340077040  NOTICE: PLEX.playutils -> File is direct playing.
21:02:54.433 T:1340077040  NOTICE: PLEX.playutils -> The playurl is: /filestore/video/Мультфильмы/Song.of.the.Sea.2014.1080p.BluRay.x264.Rus.2xEng.ac3.dts.NTb.0dayTeam.mkv
21:02:54.484 T:1340077040  NOTICE: PLEX.playbackutils -> Playing from contextmenu: False
21:02:54.484 T:1340077040  NOTICE: PLEX.playbackutils -> Playlist start position: 0
21:02:54.484 T:1340077040  NOTICE: PLEX.playbackutils -> Playlist plugin position: 0
21:02:54.484 T:1340077040  NOTICE: PLEX.playbackutils -> Playlist size: 1
21:02:54.492 T:1340077040  NOTICE: PLEX.PlexAPI -> Found external subs: []
21:02:54.493 T:1340077040  NOTICE: PLEX.playbackutils -> Play as a widget item
21:02:54.609 T:1340077040  NOTICE: PLEX.playback_starter -> ERROR: Error encountered for mode play, params {u'dbid': u'49', u'filename': u'/library/metadata/39392', u'mode': u'play', u'id': u'39392'}
21:02:54.611 T:1340077040  NOTICE: PLEX.playback_starter -> ERROR: Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playback_starter.py", line 76, in triage
                                                params.get('dbid'))
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playback_starter.py", line 66, in process_play
                                                % self.playqueue.playqueues)
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist_func.py", line 36, in __repr__
                                                answ += "items: %s, " % self.items
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist_func.py", line 83, in __repr__
                                                answ += '%s: %s, ' % (key, getattr(self, key))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 23: ordinal not in range(128)
21:02:54.659 T:1170469872  NOTICE: PLEX.default -> ERROR: Error encountered, aborting
21:02:54.659 T:1958626224   ERROR: PlayMedia could not play media: plugin://plugin.video.plexkodiconnect/movies/?dbid=49&mode=play&id=39392&filename=%2Flibrary%2Fmetadata%2F39392
21:02:54.660 T:1170469872  NOTICE: PLEX.default -> plugin.video.plexkodiconnect stopped
```

**Comment by iStatiK** [comment]
Can confirm same error and am unable to even play movies or TV shows.
```
09:56:17.696 T:716  NOTICE: PLEX.playback_starter -> ERROR: Error encountered for mode play, params {u'dbid': u'251', u'filename': u'/library/metadata/390', u'mode': u'play', u'id': u'390'}
09:56:17.697 T:716  NOTICE: PLEX.playback_starter -> ERROR: Traceback (most recent call last):
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\playback_starter.py", line 76, in triage
                                                params.get('dbid'))
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\playback_starter.py", line 64, in process_play
                                                xml.attrib.get('librarySectionUUID'))
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\playbackutils.py", line 44, in play
                                                log.info("Playbackutils called")
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\logging\__init__.py", line 1159, in info
                                                self._log(INFO, msg, args, **kwargs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\logging\__init__.py", line 1269, in _log
                                                fn, lno, func = self.findCaller()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\logging\__init__.py", line 1238, in findCaller
                                                filename = os.path.normcase(co.co_filename)
                                            SystemExit
09:56:17.697 T:716  NOTICE: PLEX.pickler -> DEBUG: Start pickling: None
09:56:17.698 T:716  NOTICE: PLEX.pickler -> DEBUG: Successfully pickled
09:56:17.698 T:716  NOTICE: PLEX.playback_starter -> ----===## Playback_Starter stopped ##===----
09:56:17.746 T:2224  NOTICE: PLEX.playqueue -> ----===## PlayQueue client stopped ##===----
09:56:17.769 T:3264 WARNING: CPythonInvoker(6, C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\service.py): the python script "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\service.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::Player,class XBMCAddon::xbmc::Monitor,class PythonBindings::XBMCAddon_xbmc_Monitor_Director,class XBMCAddon::xbmc::PlayList,class XBMCAddon::xbmc::PlayList,class XBMCAddon::xbmc::PlayList,class XBMCAddon::xbmcgui::Dialog,class XBMCAddon::xbmcaddon::Addon,class PythonBindings::XBMCAddon_xbmc_Player_Director
```

However, i have to hit the back button then am prompted with the error "One or more items failed to play. Check the log file for details'"  Then Kodi goes on to crash.
