### ISSUE TITLE
Cannot fling music from ios client to Plex Companion

### ISSUE THREAD

**Issue by davidtron** [croneter/PlexKodiConnect#233]
I am unable to fling music from the ios plex client to PKC Plex Companion.

The error appears to be caused by Kodi being unable to play the song from a play list.

`
16:57:58.959 T:1268511728  NOTICE: PLEX.playlist_func -> ERROR: Could not add item to playlist. Kodi reply. {u'jsonrpc': u'2.0', u'id': 1, u'error': {u'message': u'Invalid params.', u'code': -32602}}
16:57:59.027 T:1268511728   ERROR: Exception in thread Thread-7:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/PlexCompanion.py", line 209, in run
                                                self.processTasks(task)
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/PlexCompanion.py", line 113, in processTasks
                                                offset=data.get('offset'))
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playqueue.py", line 93, in update_playqueue_from_PMS
                                                PlaybackUtils(xml, playqueue).play_all()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playbackutils.py", line 310, in play_all
                                                '%sItemID' % self.playqueue.kind)
                                            IndexError: list index out of range
`

[debug log](https://github.com/croneter/PlexKodiConnect/files/801395/cannot-play-music.txt)

After this plex companion for PKC is no longer visible from ios app until I restart Kodi.

This only occur with music, flinging Film works fine.

Kodi version 17.1 (OSMC running on Vero)
PlexKodiConnect version 1.6.0
Plex server version 1.3.4.3285

**Comment by croneter** [comment]
You're unable to fling Plex music at PlexKodiConnect using Plex Companion because of the way the Kodi music database works - or better, doesn't work - with PKC direct paths.

If you switch to Addon paths in the PKC settings and reset the Kodi database (under Advanced), you should be fine.

**Comment by croneter** [comment]
Added this bug here: https://github.com/croneter/PlexKodiConnect/issues/84

**Comment by davidtron** [comment]
Apologies, I missed the last line of #84 - thanks

**Comment by croneter** [comment]
Just added that a couple of minutes ago ;-)
