### ISSUE TITLE
Cant play Movies or TV Shows

### ISSUE THREAD

**Issue by iStatiK** [croneter/PlexKodiConnect#237]
EDIT: After a complete reinstall of Kodi and PKC everything appears to be working fine now.

I commented on this thread but my issue a little different.
https://github.com/croneter/PlexKodiConnect/issues/229

Running Kodi 17.1 and PKC 1.6.0 on Windows 10.

Snippet:
```
09:56:17.696 T:716  NOTICE: PLEX.playback_starter -> ERROR: Error encountered for mode play, params {u'dbid': u'251', u'filename': u'/library/metadata/390', u'mode': u'play', u'id': u'390'}
09:56:17.697 T:716  NOTICE: PLEX.playback_starter -> ERROR: Traceback (most recent call last):
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\playback_starter.py", line 76, in triage
                                                params.get('dbid'))
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\playback_starter.py", line 64, in process_play
                                                xml.attrib.get('librarySectionUUID'))
                                              File "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\playbackutils.py", line 44, in play
                                                log.info("Playbackutils called")
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\logging\__init__.py", line 1159, in info
                                                self._log(INFO, msg, args, **kwargs)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\logging\__init__.py", line 1269, in _log
                                                fn, lno, func = self.findCaller()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\logging\__init__.py", line 1238, in findCaller
                                                filename = os.path.normcase(co.co_filename)
                                            SystemExit
09:56:17.697 T:716  NOTICE: PLEX.pickler -> DEBUG: Start pickling: None
09:56:17.698 T:716  NOTICE: PLEX.pickler -> DEBUG: Successfully pickled
09:56:17.698 T:716  NOTICE: PLEX.playback_starter -> ----===## Playback_Starter stopped ##===----
09:56:17.746 T:2224  NOTICE: PLEX.playqueue -> ----===## PlayQueue client stopped ##===----
09:56:17.769 T:3264 WARNING: CPythonInvoker(6, C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\service.py): the python script "C:\Users\USER\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\service.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::Player,class XBMCAddon::xbmc::Monitor,class PythonBindings::XBMCAddon_xbmc_Monitor_Director,class XBMCAddon::xbmc::PlayList,class XBMCAddon::xbmc::PlayList,class XBMCAddon::xbmc::PlayList,class XBMCAddon::xbmcgui::Dialog,class XBMCAddon::xbmcaddon::Addon,class PythonBindings::XBMCAddon_xbmc_Player_Director
```

However, i have to hit the back button then am prompted with the error "One or more items failed to play. Check the log file for details'"  Then Kodi goes on to crash.

Logs are 60 MB and 230 MB so i cant upload them.

**Comment by croneter** [comment]
Should also be solved with 1.6.1. Please reopen the issue if this is not the case
