### ISSUE TITLE
Not working when using Proxy internet connection

### ISSUE THREAD

**Issue by capoeirabg** [croneter/PlexKodiConnect#241]
I've recently switched from Plexbmc and in the proccess i discovered that i cannot setup a remote connection when using Proxy. I've tried http and socks5 both of my proxy servers work fine but was unable to connect to remote plex server. 
I've tried even if i setup the PlexKodiConnect and then enable proxy again it cannot connect. 
Imediately after I disable the proxy in settings it worked like a charm.

**Comment by croneter** [comment]
Please share a log, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by capoeirabg** [comment]
https://docs.google.com/document/d/1zWU7n3HLiFb_3VJXKQfg4lhdTZ8_KZWukdZc0DTc3J4/edit?usp=sharing

**Comment by croneter** [comment]
You did not upload your log - please try again :-)

**Comment by capoeirabg** [comment]
[01_KODI.log.txt](https://github.com/croneter/PlexKodiConnect/files/813086/01_KODI.log.txt)

**Comment by croneter** [comment]
Thanks! Unfortunately, not even LibreElec is able to connect:
```
14:34:14.363 T:140623445214976   ERROR: ## LibreELEC Addon ## oe::load_url(http://releases.libreelec.tv/releases.json) ## ERROR: (URLError(gaierror(-3, 'Temporary failure in name resolution'),))
14:34:14.363 T:140623445214976   ERROR: Traceback (most recent call last):
                                              File "/home/chewitt/LibreELEC.80-official/build.LibreELEC-Generic.x86_64-8.0.0/LibreELEC-settings-5429575/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/oe.py", line 271, in load_url
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                              File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
                                            URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```
This can also be seen for all the (art) URLs that PKC handed over to Kodi to process (cache the artwork):
```
ERROR: CCurlFile::Stat - Failed: Couldn't connect to server(7) for https://193-19-174-118.584a237995b14f35b79103e6f61b1248.plex.direct:32400/library/metadata/2078/thumb/1480339810?X-Plex-Token=password
```
This is a KODI error, not PKC. 

Have you tried using Kodi on another client in the same network, e.g. Windows?

Bottom line: even if PKC could handle your proxy, Kodi could not :-(.

**Comment by capoeirabg** [comment]
But I can still connect to direct IP stream through Proxy. 
I installed Kodi on my debian Laptop, version 16.1 and still get the error in connection.

**Comment by croneter** [comment]
What do you mean with 
>  But I can still connect to direct IP stream through Proxy.
