### ISSUE TITLE
Plex Channels aren't working

### ISSUE THREAD

**Issue by Pavuucek** [croneter/PlexKodiConnect#253]
Some channels outright crash, others at least display channel menu and crash at an attempt to play something...
I've tried following channels:
Mangafox Reader, NextPVR, HDHR Viewer 2, ComicReader, Tested, KissNetwork, Google Music, Trakt.tv
[logs.zip](https://github.com/croneter/PlexKodiConnect/files/835960/logs.zip)

**Comment by Pavuucek** [comment]
Well, KissNetwork started working and playing, but other channels are still crashing with errors like this complaining about codecs...

> 21:47:14.000 T:18446744072320147152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('codec',)
                                            Traceback (most recent call last):
                                              File "/storage/sdcard0/Kodi/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 209, in <module>
                                                Main()
                                              File "/storage/sdcard0/Kodi/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 91, in __init__
                                                plex_section_id=params.get('id'))
                                              File "/storage/sdcard0/Kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 878, in browse_plex
                                                __build_item(item)
                                              File "/storage/sdcard0/Kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 964, in __build_item
                                                api.AddStreamInfo(listitem)
                                              File "/storage/sdcard0/Kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/PlexAPI.py", line 2453, in AddStreamInfo
                                                mediastreams = self.getMediaStreams()
                                              File "/storage/sdcard0/Kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/PlexAPI.py", line 1735, in getMediaStreams
                                                videotrack['codec'] = mediaStream['codec'].lower()
                                            KeyError: ('codec',)
                                            -->End of Python script error report<--


[kodi.old.log.txt](https://github.com/croneter/PlexKodiConnect/files/836907/kodi.old.log.txt)

**Comment by croneter** [comment]
Which channels are we talking about?

**Comment by Pavuucek** [comment]
The rest of those I previously mentioned: Mangafox Reader, NextPVR, HDHR Viewer 2, ComicReader, Tested and Google Music

**Comment by croneter** [comment]
Darn

**Comment by Pavuucek** [comment]
I'm afraid it's still not working. At least there was some progress, channel menus are now displaying properly, but when I attempt to play anything Kodi just hangs for few moments and nothing happens. Not even an error message. :-(
[kodi.log.txt](https://github.com/croneter/PlexKodiConnect/files/840381/kodi.log.txt)

**Comment by croneter** [comment]
We're talking about pictures/images now, correct, not videos?
Something changed in Krypton, I haven't figured out yet how to fix showing images

**Comment by Pavuucek** [comment]
Both video and images

**Comment by croneter** [comment]
Working on it. By the way, one of your channels crashes (mangafox.me?):
```
<?xml version='1.0' encoding='utf-8'?>
<Response code="2000" status="FrameworkException: Status != 200">
<Traceback>Traceback (most recent call last):
File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-03e4cfa35\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request
result = f(**d)
File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-03e4cfa35\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\handlers\services.py", line 38, in url_lookup
raise Framework.exceptions.FrameworkException("Status != 200")
FrameworkException: Status != 200
</Traceback>
</Response>
```

**Comment by croneter** [comment]
OK, they should be working now, starting with PKC version 1.7.4. Be sure to check whether a channel REALLY works - e.g. your Kiss channel seems broken right now. 

# Warning
Kodi only displays videos if you navigate through Videos -> Video Addons ->... Channels. And pictures only if you navigate through Pictures -> Picture Addons -> ... Channels. 
Nothing I can do about that, unfortunately :-(
