### ISSUE TITLE
Error: Could not get PMS settings on startup

### ISSUE THREAD

**Issue by jamietre** [croneter/PlexKodiConnect#263]
I've been successfully using PlexKodiConnect with Kodi 16 for a while, love it. I tried to set it up with Kodi 17 with the same config and can't get it to start. 

Important to note that I have *Kodi 16 and 17 running on the same box*. It seems that this is supported generally for Kodi (i've changed web server ports to avoid conflicts) but thought I would mention it. This is an Android box (Zidoo X8) - I can't uninstall Kodi 16 and wouldn't want to anyway since it's a custom build that came with the box, and has unique hardware support that I need. But I would love to get this working for Kodi 17 also, because it's much preferable to 16 when I don't need those features.

Detailed log is below. Any ideas? I tried both 1.7.2 and 1.7.4.

```
20:44:44.179 T:18446744073051048240  NOTICE: PLEX.service -> Delaying Plex startup by: 0 sec...
20:44:44.208 T:18446744073051048240  NOTICE: PLEX.service -> ======== START PlexKodiConnect ========
20:44:44.208 T:18446744073051048240  NOTICE: PLEX.service -> Platform: Linux
20:44:44.209 T:18446744073051048240  NOTICE: PLEX.service -> KODI Version: 17.1 Git:20170320-fc1619b
20:44:44.209 T:18446744073051048240  NOTICE: PLEX.service -> PlexKodiConnect Version: 1.7.4
20:44:44.219 T:18446744073051048240  NOTICE: PLEX.service -> Using plugin paths: True
20:44:44.229 T:18446744073051048240  NOTICE: PLEX.service -> Number of sync threads: 10
20:44:44.229 T:18446744073051048240  NOTICE: PLEX.service -> Log Level: 2
20:44:44.230 T:18446744073051048240  NOTICE: PLEX.service -> Full sys.argv received: ['']
20:44:44.231 T:18446744073051048240  NOTICE: PLEX.videonodes -> Clearing nodes properties.
20:44:44.232 T:18446744072973187376  NOTICE: PLEX.monitor_kodi_play -> ----===## Starting Kodi_Play_Client ##===----
20:44:44.233 T:18446744073051048240  NOTICE: PLEX.initialsetup -> DEBUG: Entering initialsetup class
20:44:44.286 T:18446744073051048240  NOTICE: PLEX.userclient -> DEBUG: Returning active server: https://176.16.2.10:32400
20:44:44.377 T:18446744073051048240  NOTICE: PLEX.initialsetup -> DEBUG: Found a plex.tv token in the settings
20:44:44.378 T:18446744073051048240  NOTICE: PLEX.initialsetup -> Initial setup called.
20:44:44.417 T:18446744073051048240  NOTICE: PLEX.initialsetup -> PMS is already set: https://176.16.2.10:32400. Checking now...
20:44:44.417 T:18446744073051048240  NOTICE: PLEX.PlexAPI -> DEBUG: Checking connection to server https://176.16.2.10:32400/library/onDeck with verifySSL=False
20:44:44.427 T:18446744073051048240  NOTICE: PLEX.clientinfo -> Unique device Id plex_client_Id loaded: 40d992f4-ed98-4286-a7c0-0caff50e79f4
20:44:44.667 T:18446744073051048240  NOTICE: PLEX.PlexAPI -> DEBUG: Checking connection successfull. Answer: 401
20:44:44.836 T:18446744073051048240  NOTICE: PLEX.PlexFunctions -> DEBUG: Found machineIdentifier a0148c041b6762332da9e326bd02533a9461b713 for the PMS https://176.16.2.10:32400
20:44:44.837 T:18446744073051048240  NOTICE: PLEX.initialsetup -> Using PMS https://176.16.2.10:32400 with machineIdentifier a0148c041b6762332da9e326bd02533a9461b713
20:44:45.025 T:18446744073051048240  NOTICE: PLEX.initialsetup -> ERROR: Could not get PMS settings for https://176.16.2.10:32400
20:44:45.067 T:18446744073051048240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 368, in <module>
                                                Service().ServiceEntryPoint()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 154, in ServiceEntryPoint
                                                self.library = LibrarySync(self)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 337, in __init__
                                                self.fullSyncInterval = int(settings('fullSyncInterval')) * 60
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
20:44:59.344 T:18446744073171192112  NOTICE: Storing total System Uptime
20:44:59.346 T:18446744073171192112  NOTICE: Saving settings
20:44:59.369 T:18446744073171192112  NOTICE: Saving skin settings
20:44:59.374 T:18446744073171192112  NOTICE: stop all
20:44:59.374 T:18446744073171192112  NOTICE: stop player
20:44:59.376 T:18446744073171192112  NOTICE: ES: Stopping event server
20:44:59.376 T:18446744073171192112  NOTICE: stopping upnp
20:44:59.543 T:18446744073171192112  NOTICE: CWebServer[8081]: Stopped
20:44:59.766 T:18446744073020954928  NOTICE: ES: UDP Event server stopped
20:44:59.787 T:18446744073171192112  NOTICE: clean cached files!
20:45:04.879 T:18446744073171192112   ERROR: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/service.py): script didn't stop in 5 seconds - let's kill it
20:45:04.887 T:18446744073171192112  NOTICE: closing down remote control service
20:45:04.888 T:18446744073171192112  NOTICE: stopped
20:45:05.055 T:18446744073051048240 WARNING: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/service.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon4xbmc7MonitorE,N9XBMCAddon9xbmcaddon5AddonE
20:45:05.088 T:18446744073171192112  NOTICE: destroy
20:45:05.088 T:18446744073171192112  NOTICE: unload skin
20:45:05.153 T:18446744073171192112  NOTICE: unload sections
20:45:05.178 T:18446744073171192112  NOTICE: special://profile/ is mapped to: special://masterprofile/
20:45:05.197 T:18446744073171192112  NOTICE: application stopped...

```

**Comment by croneter** [comment]
Somehow your PKC settings got corrupted. Navigate to the Kodi userdata folder (http://kodi.wiki/view/userdata), then into `addon_data`, then `plugin.video.plexkodiconnect`. Either delete the file `settings.xml` entirely or look for the entry `fullSyncInterval`. Change that to 60 (it should be empty right now)

**Comment by croneter** [comment]
Do report back and reopen the issue if this shouldn't work ;-)

**Comment by jamietre** [comment]
Thanks for the quick reply, will try it tonight!
