### ISSUE TITLE
LibrarySync thread crashed: "Can't create file, if it exists."

### ISSUE THREAD

**Issue by jPPuetz** [croneter/PlexKodiConnect#286]
Hi,
after helping me in Plex Forum with kodi profile changed bug (thx for that!), i got a new one.

```
10:52:50.268 T:11152  NOTICE: PLEX.utils -> Successfully added playlist: Movies
10:52:50.269 T:11152  NOTICE: PLEX.librarysync -> ERROR: LibrarySync thread crashed. Error message: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: u'C:\\Users\\\xfc\\AppData\\Roaming\\Kodi\\userdata\\library\\video'
10:52:50.274 T:11152  NOTICE: PLEX.librarysync -> ERROR: Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1426, in run
                                                self.run_internal()
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1540, in run_internal
                                                librarySync = fullSync()
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\utils.py", line 891, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 269, in fullSync
                                                if self._fullSync() is False:
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 290, in _fullSync
                                                if not self.maintainViews():
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 525, in maintainViews
                                                totalnodes)
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 469, in processView
                                                folderid)
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\videonodes.py", line 86, in viewNode
                                                "special://profile/library/video")))
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\shutil.py", line 177, in copytree
                                                os.makedirs(dst)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: u'C:\\Users\\\xfc\\AppData\\Roaming\\Kodi\\userdata\\library\\video'
10:52:52.199 T:11152   ERROR: Exception in thread Thread-7:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1426, in run
                                                self.run_internal()
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1540, in run_internal
                                                librarySync = fullSync()
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\utils.py", line 891, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 269, in fullSync
                                                if self._fullSync() is False:
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 290, in _fullSync
                                                if not self.maintainViews():
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 525, in maintainViews
                                                totalnodes)
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 469, in processView
                                                folderid)
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\videonodes.py", line 86, in viewNode
                                                "special://profile/library/video")))
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\shutil.py", line 177, in copytree
                                                os.makedirs(dst)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: u'C:\\Users\\\xfc\\AppData\\Roaming\\Kodi\\userdata\\library\\video'
```
Edit: Complete log file is attached.

[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/969940/kodi.txt)

Thanks for your help.

**Comment by croneter** [comment]
Ouh, poor you, yet another bug ;-). Can you reproduce it? Does it happen on every library sync?

**Comment by jPPuetz** [comment]
It happens everytime i start kodi. I think then PKC tries syncing. If manually force sync via settings of PKC it happens too. It's still the "first library sync" and it it happend directly after i installed the latest beta version of PKC reconfigured the PMS (login at plex.tv/pin) and entering my plex passcode. So everything was configured and the first sync was ready to go...

I'm now for about two weeks not at home and can't do any testing stuff. If you have tasks for me or it would be better to completly remove kodi + PKC (maybe because the bug before?!) i can do that when i'm back at home. It would be good to know which file there that shouldn't be there (i would just delete it :)...).

**Comment by jPPuetz** [comment]
Hi,
I'm still having the issue described above with latest PKC beta.

```
16:03:22.825 T:7780  NOTICE: PLEX.utils -> ERROR: [Errno 2] No such file or directory: 'C:\\Users\\\xc3\xbc\\AppData\\Roaming\\Kodi\\userdata\\playlists\\video\\Plex 1.xsp'
16:03:22.826 T:7780  NOTICE: PLEX.librarysync -> ERROR: LibrarySync thread crashed. Error message: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\\xc3\xbc\\AppData\\Roaming\\Kodi\\userdata\\library\\video'
16:03:22.829 T:7780  NOTICE: PLEX.librarysync -> ERROR: Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1434, in run
                                                self.run_internal()
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1548, in run_internal
                                                librarySync = fullSync()
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\utils.py", line 901, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 268, in fullSync
                                                if self._fullSync() is False:
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 289, in _fullSync
                                                if not self.maintainViews():
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 533, in maintainViews
                                                totalnodes)
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 468, in processView
                                                folderid)
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\videonodes.py", line 81, in viewNode
                                                dst=xbmc.translatePath("special://profile/library/video"))
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\shutil.py", line 177, in copytree
                                                os.makedirs(dst)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\\xc3\xbc\\AppData\\Roaming\\Kodi\\userdata\\library\\video'
16:03:24.679 T:7780   ERROR: Exception in thread Thread-7:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1434, in run
                                                self.run_internal()
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1548, in run_internal
                                                librarySync = fullSync()
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\utils.py", line 901, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 268, in fullSync
                                                if self._fullSync() is False:
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 289, in _fullSync
                                                if not self.maintainViews():
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 533, in maintainViews
                                                totalnodes)
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 468, in processView
                                                folderid)
                                              File "C:\Users\𜁰pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\videonodes.py", line 81, in viewNode
                                                dst=xbmc.translatePath("special://profile/library/video"))
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\shutil.py", line 177, in copytree
                                                os.makedirs(dst)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'C:\\Users\\\xc3\xbc\\AppData\\Roaming\\Kodi\\userdata\\library\\video'
```
[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/998706/kodi.txt)

I uninstalled kodi with RevoUninstaller (removed all appdata stuff etc.) and performed a fresh reinstall of kodi and PKC beta. After entering pin at plex and my local plex pin I think PKC first crashed with something like 'Permissions denied' at some folder. After that i restarted kodi as administrator and got the above error.

**Comment by croneter** [comment]
This issue is bugging me. How does your directory 'C:\\Users\\\xc3\xbc\\AppData\\Roaming\\Kodi\\userdata\\library\\video' look like? What's your Windows username? (after the `Users` part)

**Comment by jPPuetz** [comment]
My windows user name is like "AAA AüA". I removed the part around the german umlaut (the 'ü'). So i have a blank and a german umlaut in my name. I'm not sure if the issue is about the 'ü'... a lot of programs got problems with german umlaute. So the '\xc3\xbc' part is the escaping sequence of the letter 'ü'.

The dir is empty (in my real accout folder) \video doesn't exists.... Oh wait
There is a new user folder: With the following chars in it 'Ã¼' ==> This happens when a program can't handle umlaute. So it creates it's own Appdata folder in the newly created user home dir. Thats also the reason i got at first a error about 'permissons'. Kodi needed admin rights to create such a folder.

Here is the content of the AppData folder in the wrong user home dir.
```
 Verzeichnis von C:\Users\Ã¼\AppData\Roaming\Kodi\userdata\library\video

13.05.2017  16:03    <DIR>          .
13.05.2017  16:03    <DIR>          ..
20.03.2017  18:19               201 addons.xml
20.03.2017  18:19               188 files.xml
13.05.2017  15:49    <DIR>          movies
13.05.2017  15:49    <DIR>          musicvideos
20.03.2017  18:19               206 playlists.xml
13.05.2017  15:49    <DIR>          tvshows
               3 Datei(en),            595 Bytes
               5 Verzeichnis(se), 86.619.570.176 Bytes frei
```
I think on weekend i got more time to investigate this issue. A good start point would be to get the AppData folder fixed.

**Comment by croneter** [comment]
I 100% agree with you. 
Do you have these issues also with PKC v1.7.7? (stable version)

**Comment by jPPuetz** [comment]
I reinstalled kodi and tried to use PKC 1.7.7. I'm getting the error about kodi profile / ascii decoding. Log is attached. Also the kodi didn't asked me about my plex pin and therefore connections to the PMS fail.
```
20:16:32.255 T:6232   ERROR: C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\service.py:167: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              if window('plex_kodiProfile') != kodiProfile:
20:16:32.255 T:6232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 36: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\service.py", line 368, in <module>
                                                Service().ServiceEntryPoint()
                                              File "C:\Users\��pData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\service.py", line 171, in ServiceEntryPoint
                                                % (kodiProfile, window('plex_kodiProfile')))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 36: ordinal not in range(128)
                                            -->End of Python script error report<--
```

[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/1015175/kodi.txt)

**Comment by jPPuetz** [comment]
Thank you! Everything is working and finally the sync succeeded.
