### ISSUE TITLE
UnicodeDecodeError for walk() in deletePlaylists() function

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#364]
Probably need to completely replace walk()
```
15:52:53.439 T:18446744072803359024 ERROR: PLEX.librarysync: LibrarySync thread crashed. Error message: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
15:52:53.447 T:18446744072803359024 ERROR: PLEX.librarysync: Traceback:
Traceback (most recent call last):
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1503, in run
self.run_internal()
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1613, in run_internal
deletePlaylists()
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 920, in deletePlaylists
for root, _, files in walk(path):
File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-debug/lib/python2.7/os.py", line 286, in walk
File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-debug/lib/python2.7/posixpath.py", line 71, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

**Comment by croneter** [comment]
Should you run into this issue, tripple check whether all your python installation is up-to-date and all python packages are also updated. 

If that is the case and you still have this issue, report back here.
