### ISSUE TITLE
Error "Sync had to skip some items..." since PKC 1.1.10

### ISSUE THREAD

**Issue by badrabbit** [croneter/PlexKodiConnect#39]
Since PKC 1.1.10 i'm getting the "Sync had to skip some items because they could not be processed..." error.
Tried a full reset --> error message pops up "check the log"
Did a full Kodi and PKC reinstall --> sync works the first time but after a Kodi restart it won't sync, video directories are empty and the "Sync had to skip..." error shows up.

Log attached. Thanks.
[kodilog.log.zip](https://github.com/croneter/PlexKodiConnect/files/272945/kodilog.log.zip)

**Comment by croneter** [comment]
You got a corrupted DB, e.g. because Kodi could not shut down correctly. This was not caused by PKC
```
17:52:14 T:123145311043584  NOTICE: PlexKodiConnect Items -> add_updateEpisode : Traceback:
                                            Traceback (most recent call last):
                                              File "/Users/macmini_home/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/lib/itemtypes.py", line 1190, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                                              File "/Users/macmini_home/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/lib/itemtypes.py", line 1233, in run_add_updateEpisode
                                                kodicursor.execute(query, (episodeid,))
                                            DatabaseError: database disk image is malformed
```

Shut down Kodi. Go to your [userdata folder](http://kodi.wiki/view/userdata) and delete all the databases.
