### ISSUE TITLE
Beta 2.0.0 On Deck Empty

### ISSUE THREAD

**Issue by tomatosoupcan** [croneter/PlexKodiConnect#398]
See kodi.log attached. No On Deck entries show up for TV Shows:
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1698750/kodi.log)

**Comment by tomatosoupcan** [comment]
Rolling back to 1.8.18 on deck returns as expected

**Comment by dazedcrazy** [comment]
Empty On Deck and Recently Added for TV Shows throws up errors
```
14:08:18.729 T:2967466848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 211, in <module>
                                                Main()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 79, in __init__
                                                int(params.get('limit')))
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 387, in getRecentEpisodes
                                                allshowsIds.add(tv_show['tvshowid'])
                                            TypeError: string indices must be integers
                                            -->End of Python script error report<--
14:08:19.108 T:3702518624   ERROR: GetDirectory - Error getting plugin://plugin.video.plexkodiconnect/?id=35&mode=recentepisodes&type=tvshows&tagname=TV Shows&limit=25
14:08:19.123 T:4102594880   ERROR: GetDirectory - Error getting library://video/Plex-35/35_recentepisodes.xml/
14:08:19.124 T:4102594880   ERROR: CGUIMediaWindow::GetDirectory(library://video/Plex-35/35_recentepisodes.xml/) failed
```
