### ISSUE TITLE
Server discovery causes an error

### ISSUE THREAD

**Issue by dazedcrazy** [croneter/PlexKodiConnect#409]
```
15:52:04.231 T:9012  NOTICE: PLEX.default: plugin.video.plexkodiconnect started
15:52:04.231 T:9012  NOTICE: PLEX.entrypoint: Choosing PMS server requested, starting
15:52:04.271 T:9012  NOTICE: PLEX.PlexFunctions: Start discovery of Plex Media Servers
15:52:06.271 T:9012  NOTICE: PLEX.PlexFunctions: Checking with plex.tv for more PMS to connect to
15:52:06.273 T:9012  NOTICE: PLEX.clientinfo: Unique device Id plex_client_Id loaded: 5f8f66f2-4c25-4596-b08f-52aff5ac097b
15:52:07.839 T:9012   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('scheme',)
                                            Traceback (most recent call last):
                                              File "C:\Users\KompLeX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py", line 211, in <module>
                                                Main()
                                              File "C:\Users\KompLeX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py", line 141, in __init__
                                                entrypoint.chooseServer()
                                              File "C:\Users\KompLeX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\entrypoint.py", line 43, in chooseServer
                                                server = setup.pick_pms(showDialog=True)
                                              File "C:\Users\KompLeX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\initialsetup.py", line 305, in pick_pms
                                                server = self._user_pick_pms()
                                              File "C:\Users\KompLeX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\initialsetup.py", line 418, in _user_pick_pms
                                                chk = self._check_pms_connectivity(server)
                                              File "C:\Users\KompLeX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\initialsetup.py", line 256, in _check_pms_connectivity
                                                % (server['scheme'], server['ip'], server['port']))
                                            KeyError: ('scheme',)
                                            -->End of Python script error report<--
15:52:07.883 T:9012 WARNING: CPythonInvoker(13, C:\Users\KompLeX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py): the python script "C:\Users\KompLeX\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
```
When i click "Choose Plex Server from a list" it sees the local server fine but when i click it i get the above error, manually entering IP works just fine

**Comment by croneter** [comment]
I need the entire log and lease enable debug logging

**Comment by dazedcrazy** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1728490/kodi.log)
Was being lazy and didn't want to have to remove my token lol

**Comment by croneter** [comment]
Wierd that this bug didn't bite me in the face, so obvious
