### ISSUE TITLE
Music: Party mode doesn't sync correct track playback

### ISSUE THREAD

**Issue by dazedcrazy** [croneter/PlexKodiConnect#419]
When you use party mode for playing music whatever the first track is it reports that back as being played even when you've skipped 1/2/3 tracks ahead, I mean I like Simple Minds as much as the next man but not 64 minutes of the same track lol
![sbgrbbb](https://user-images.githubusercontent.com/9027988/36782519-1c144a90-1c71-11e8-9d40-97a79c949f0b.png)
Here's a log were I click party mode, first track is a Taylor Swift one i skip to the next one wait a bit then skip to the next one again but it stills shows in plexpy and in web browser that I'm listening to the first track
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1766649/kodi.log)

**Comment by croneter** [comment]
You have an interesting element here that probably caused this behavior:
```
10:08:59.653 T:3110450016   DEBUG: PLEX.playqueue: Detected new Kodi element at position 4: {u'title': u'Juicy Booty', u'type': u'song', u'id': 96, u'file': u'smb://media-pc/music/Chris Brown/Heartbreak on a Full Moon - Cuffing Season - 12 Days of Christmas/15 - Chris Brown feat Jhen\xe9 Aiko & R Kelly - Juicy Booty.flac', u'label': u'15. Chris Brown feat. Jhen\xe9 Aiko & R. Kelly - Juicy Booty'}
10:08:59.656 T:3482317664   DEBUG: DoWork - took 101 ms to load special://masterprofile/Thumbnails/c/c67b0dcd.jpg
10:08:59.672 T:3110450016   ERROR: Exception in thread Thread-11:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playqueue.py", line 237, in run
                                                self._compare_playqueues(playqueue, kodi_pl)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playqueue.py", line 194, in _compare_playqueues
                                                kodi_item=new_item)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist_func.py", line 517, in add_item_to_PMS_playlist
                                                item = playlist_item_from_kodi(kodi_item)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist_func.py", line 263, in playlist_item_from_kodi
                                                LOG.debug('Made playlist item from Kodi: %s', item)
                                              File "/usr/lib/python2.7/logging/__init__.py", line 1155, in debug
                                              File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
                                              File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
                                              File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
                                              File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/loghandler.py", line 44, in emit
                                                xbmc.log(self.format(record), level=LEVELS[record.levelno])
                                              File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
                                              File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
                                              File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist_func.py", line 172, in __repr__
                                                try_encode(getattr(self, key)))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 134: ordinal not in range(128)
```

**Comment by croneter** [comment]
OK, can reproduce it. Funny enough, this seems to be a Kodi bug with unicode/string conversions :rofl:

**Comment by dazedcrazy** [comment]
Ah i recently redone all my music with MusicBrainz Picard and changed the naming convention

**Comment by dazedcrazy** [comment]
https://github.com/croneter/PlexKodiConnect/commit/2fb79b97f8d4dae17164d34b4306ea84ae353982 didn't fix the problem. 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1786779/kodi.log)

**Comment by dazedcrazy** [comment]
No errors in the log this time but still syncs wrong track back, first time i tested this morning i took the first track like before i and reported that back as being played even after skipping ahead a few tracks. Now when i skip ahead a track it reports the next track in the playlist as being played not the current one, maybe it has something to so with how [Party Mode](https://kodi.wiki/view/Music_navigation#Party_Mode) works.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1789460/kodi.log)

**Comment by croneter** [comment]
Difficult one 😉

**Comment by dazedcrazy** [comment]
What's even worse is that it seems random. Just made a playlist with 3 tracks and like before it only synced the first track but when i stopped it and played the same playlist again it syncs the correct tracks... lol

**Comment by croneter** [comment]
OK, thanks for your patience 😉 

So this applies ONLY to party mode? Or do you manage to "break" PKC with normal viewing/listening? If so, then I'd be really interested in another log and ideally a timestamp of you (and maybe the song title) when things started going south

**Comment by croneter** [comment]
So yes, this issue occurs only for party mode?

**Comment by dazedcrazy** [comment]
We'll go with yes and put it happening when i played a playlist this morning down to a fluke as i can't reproduce it

**Comment by dazedcrazy** [comment]
I think this might be somehow related to this https://github.com/croneter/PlexKodiConnect/issues/446 if i turned off "play next song automatically" seems to have fixed it (well that and recent updates) been testing and so far the right track is getting reported back.

**Comment by croneter** [comment]
Funny... Does it break again if you re-activate the Kodi setting?

**Comment by dazedcrazy** [comment]
You know i was just so happy it was working never thought to check it again with the setting on lol So with "play next song automatically" on or off the correct track is reported back every time so must be one of your recent commits that did it
