### ISSUE TITLE
Library sync thread crash

### ISSUE THREAD

**Issue by zonly1** [croneter/PlexKodiConnect#448]
Hey croneter, I got a library sync thread has crashed message when I switched to Kodi so I'm not sure what happened but it looks like it happened during a sync. 
Here is a log but I didn't have debug logging enabled.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1866095/kodi.log)

**Comment by croneter** [comment]
Should be enough, thanks!

**Comment by croneter** [comment]
For future reference, funny bug:
```
22:10:45.387 T:3023385440   ERROR: PLEX.librarysync: Traceback:
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1465, in run
                                                self.run_internal()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1598, in run_internal
                                                now = unix_timestamp()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 333, in unix_timestamp
                                                future = datetime.utcnow()
                                            ValueError: day is out of range for month
```

**Comment by zonly1** [comment]
Noticed it in the log, funny bug indeed.

**Comment by croneter** [comment]
Not much I can do about it - seems to be a bug of the python module datetime. Probably already is "solved" - see if it still pops up if you restart kodi

**Comment by zonly1** [comment]
Yeah, didn't happen again after a restart so far for a few hours now. I was thinking it might be just a rare bug with the module or something.
