### ISSUE TITLE
Sync error for certain shows with beta version

### ISSUE THREAD

**Issue by RickDB** [croneter/PlexKodiConnect#462]
**Issue**

During sync get a PKC notifcation that certain items failed to sync, the items will get added however it will not have any images like covers or fanart.

Error log seems to point some SQL constraint error:

```
22:06:47.089 T:28740  NOTICE: PLEX.librarysync: Processing Plex Movies. Libraries: [{'itemtype': u'movie', 'kodi_tagid': 2, 'id': u'2', 'sync_to_kodi': 1, 'name': u'Movies'}]
22:06:48.173 T:28740  NOTICE: PLEX.librarysync: Movies sync is finished.
22:06:48.176 T:28740  NOTICE: PLEX.utils: It took 0:00:01.088000 to run the function plex_movies
22:06:48.176 T:28740  NOTICE: PLEX.librarysync: Media folders for TVShows: [{'itemtype': u'show', 'kodi_tagid': 1, 'id': u'11', 'sync_to_kodi': 1, 'name': u'Anime'}, {'itemtype': u'show', 'kodi_tagid': 3, 'id': u'14', 'sync_to_kodi': 1, 'name': u'Nederlandse TV'}, {'itemtype': u'show', 'kodi_tagid': 4, 'id': u'13', 'sync_to_kodi': 1, 'name': u'Opnames'}, {'itemtype': u'show', 'kodi_tagid': 5, 'id': u'3', 'sync_to_kodi': 1, 'name': u'TV Shows'}]
22:06:48.708 T:15444  NOTICE: PLEX.itemtypes: ADD tvshow itemid: 56138 - Title: The Seven Deadly Sins: Signs of Holy War
22:06:48.716 T:15444   ERROR: PLEX.utils: add_update has crashed. Error: UNIQUE constraint failed: genre_link.media_id, genre_link.media_type, genre_link.genre_id
22:06:48.724 T:15444   ERROR: PLEX.utils: Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\Rick\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\utils.py", line 1007, in wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\Rick\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 705, in add_update
                                                self.kodi_db.modify_genres(showid, v.KODI_TYPE_SHOW, genres)
                                              File "C:\Users\Rick\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\kodidb_functions.py", line 346, in modify_genres
                                                'genre_id')
                                              File "C:\Users\Rick\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\kodidb_functions.py", line 306, in _modify_link_and_table
                                                self.cursor.execute(query, (entry_id, kodi_id, kodi_type))
                                            IntegrityError: UNIQUE constraint failed: genre_link.media_id, genre_link.media_type, genre_link.genre_id
22:07:08.908 T:24040  NOTICE: PLEX.itemtypes: ADD episode itemid: 56140 - Title: The Dark Dream Begins
22:07:08.914 T:24040  NOTICE: PLEX.itemtypes: ADD episode itemid: 56141 - Title: Our Fighting Festival
22:07:08.935 T:24040  NOTICE: PLEX.itemtypes: ADD episode itemid: 56142 - Title: Chasing The First Love
22:07:08.937 T:24040  NOTICE: PLEX.itemtypes: ADD episode itemid: 56143 - Title: Form of Love
22:07:22.409 T:28740  NOTICE: PLEX.librarysync: TVShows sync is finished.
22:07:22.448 T:28740  NOTICE: PLEX.utils: It took 0:00:34.272000 to run the function plex_tv_show
22:07:22.498 T:20164  NOTICE: VideoInfoScanner: Starting scan ..
22:07:22.500 T:20164  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
22:10:27.029 T:8616  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
22:22:53.039 T:28740  NOTICE: Previous line repeats 2 times.
```

The show from that error ("The Seven Deadly Sins: Signs of Holy War") does indeed lack any images as I double checked in Kodi info display.
Didn't have debug at that time but if you want can do another PKC reset if that helps getting the exact query info, since it reports genre_link error here are the genre tags from that show:

![sds_genres](https://user-images.githubusercontent.com/347084/39667407-eb5410d8-50b5-11e8-9ca7-3c2fcc38bcc4.JPG)

**Steps to reproduce**

Not sure but seems to be mostly for my Anime share.

**Resolutions**

Tried a few things to rule out any installation errors but had the same result:

- Full PKC reset
- Clean Kodi library function
- Fresh Kodi install on a different machine

Only thing that solves it is to downgrade to latest PKC stable (1.8.*) which syncs successfully after I do a PKC reset.

**Information**

**Kodi**: 17.6
**OS**: Windows 10 x64
**PKC**: 2.0.22
**PMS**: 1.13.0.5003

**Comment by croneter** [comment]
Thanks for the report, will be fixed in the next version. You can ignore the warning for now, nothing bad should happen :wink:

**Comment by RickDB** [comment]
Thanks 👍
