### ISSUE TITLE
Error resuming playback

### ISSUE THREAD

**Issue by FallingSnow** [croneter/PlexKodiConnect#481]
Clicked play and choose to resume from the kodi web ui. Kodi was stuck with the busy loading spinner so I looked at the log and found an error.

Using the latest beta (2.0.27) and Kodi 17 on a Raspberry Pi 2. Kodi database was cleared after updating to 2.0.27.

Let me know if you need more of the log.

```
...
11:38:41.756 T:1660724128  NOTICE: LoadJpeg: unable to load https://assets.fanart.tv/fanart/movies/949/moviethumb/heat-57f55826c5210.jpg
11:38:42.319 T:1278825376  NOTICE: PLEX.playback: playback_triage called with plex_id 234, plex_type movie, path None, resolve True,
11:38:42.338 T:1278825376   ERROR: Exception in thread Thread-11:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playback_starter.py", line 71, in run
                                                self._triage(item)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playback_starter.py", line 42, in _triage
                                                resolve=resolve)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 1153, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playback.py", line 65, in playback_triage
                                                pos = js.get_position(playqueue.playlistid)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/json_rpc.py", line 437, in get_position
                                                'properties': ['position']})['result']['position']
                                            KeyError: 'result'
11:38:42.486 T:1249899424 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
11:38:42.896 T:1249899424 WARNING: Previous line repeats 2 times.
11:38:42.896 T:1249899424  NOTICE: LoadJpeg: unable to load https://assets.fanart.tv/fanart/movies/127380/moviethumb/finding-dory-581559230bde9.jpg
...
```

**Comment by FallingSnow** [comment]
Try to play from beginning instead of resume results in a different error.

```
...
11:50:04.123 T:1193583520  NOTICE: PLEX.MOVIES: PKC add-on for movies started
11:50:47.382 T:1944783312   ERROR: CPythonInvoker(42, /storage/.kodi/addons/plugin.video.plexkodiconnect.movies/default.py): script didn't stop in 5 seconds - let's kill it
11:50:47.383 T:1944783312   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.plexkodiconnect.movies/?plex_id=234&plex_type=movie&mode=play&filename=Meet the Robinsons (2007).mp4]
11:50:49.277 T:1912599456  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
11:50:49.643 T:1299182496   ERROR: Exception in thread Thread-12:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playqueue.py", line 249, in run
                                                self._compare_playqueues(playqueue, kodi_pl)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playqueue.py", line 217, in _compare_playqueues
                                                PL.delete_playlist_item_from_PMS(playqueue, i)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist_func.py", line 666, in delete_playlist_item_from_PMS
                                                playlist.items[pos].id,
                                            IndexError: list index out of range
11:50:50.246 T:1912599456  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
11:50:54.594 T:1944783312  NOTICE: Previous line repeats 3 times.
11:50:54.594 T:1944783312   ERROR: CPythonInvoker(41, /storage/.kodi/addons/plugin.video.plexkodiconnect.movies/default.py): script didn't stop in 5 seconds - let's kill it
11:50:54.595 T:1944783312   ERROR: Playlist Player: skipping unplayable item: -1, path [plugin://plugin.video.plexkodiconnect.movies/?plex_id=234&plex_type=movie&mode=play&filename=Meet the Robinsons (2007).mp4]
11:50:54.595 T:1944783312 WARNING: Attempt to set unplayable index -1
11:50:56.448 T:1912599456  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
11:51:01.811 T:1944783312  NOTICE: Previous line repeats 2 times.
11:51:01.811 T:1944783312   ERROR: CPythonInvoker(35, /storage/.kodi/addons/plugin.video.plexkodiconnect.movies/default.py): script didn't stop in 5 seconds - let's kill it
11:51:01.812 T:1944783312   ERROR: Playlist Player: skipping unplayable item: -1, path [plugin://plugin.video.plexkodiconnect.movies/?plex_id=234&plex_type=movie&mode=play&filename=Meet the Robinsons (2007).mp4]
11:51:01.812 T:1944783312 WARNING: Attempt to set unplayable index -1
11:51:04.035 T:1912599456  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
...
```

**Comment by FallingSnow** [comment]
Restarted the Pi and it works. Seems it might have had something to do with the playlist.

**Comment by croneter** [comment]
Could you please share your entire log. Bug happened before these trace backs

**Comment by FallingSnow** [comment]
I will try to recreate the error and send you the log.

**Comment by FallingSnow** [comment]
Just saw you closed with a commit. Should I still try to get you a log?

**Comment by croneter** [comment]
No. I think the bug is fixed. Do come back here though if you experience it again - try to grab the entire log immediately. Many thanks!
