### ISSUE TITLE
Generating new Plex device ID doesn't work

### ISSUE THREAD

**Issue by Pavuucek** [croneter/PlexKodiConnect#503]
Opening PKC settings -> Advanced and clicking Generate new unique Plex device Id results in exception.
```
22:11:03.875 T:10476  NOTICE: PLEX.default: plugin.video.plexkodiconnect started
22:11:03.876 T:10476   DEBUG: PLEX.default: Full sys.argv received: ['plugin://plugin.video.plexkodiconnect/', '-1', '?mode=deviceid', 'resume:false']
22:11:03.881 T:10476   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named clientinfo
                                            Traceback (most recent call last):
                                              File "C:\Users\michal\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py", line 188, in <module>
                                                Main()
                                              File "C:\Users\michal\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py", line 121, in __init__
                                                self.deviceid()
                                              File "C:\Users\michal\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py", line 172, in deviceid
                                                from clientinfo import getDeviceId
                                            ImportError: No module named clientinfo
                                            -->End of Python script error report<--
22:11:03.881 T:10476   DEBUG: CPythonInvoker::onExecutionDone(9, C:\Users\michal\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py)
```
[kodi.old.zip](https://github.com/croneter/PlexKodiConnect/files/2160945/kodi.old.zip)

**Comment by Pavuucek** [comment]
👍
