### ISSUE TITLE
Many sessionKey errors in log file

### ISSUE THREAD

**Issue by Pavuucek** [croneter/PlexKodiConnect#504]
I'm getting these errors on all of my devices. 
```
07:31:32.569 T:1431192480   DEBUG: PLEX.websocket_client: PMS_Websocket: Received message from PMS server: {u'PlaySessionStateNotification': [{u'viewOffset': 0, u'url': u'', u'ratingKey': u'', u'state': u'stopped', u'key': u'', u'guid': u''}], u'type': u'playing', u'size': 1}
07:31:32.590 T:1414415264   ERROR: PLEX.librarysync: Processing of Plex Companion message has crashed
07:31:32.590 T:1414415264   ERROR: PLEX.librarysync: Message was: {u'PlaySessionStateNotification': [{u'viewOffset': 0, u'url': u'', u'ratingKey': u'', u'state': u'stopped', u'key': u'', u'guid': u''}], u'type': u'playing', u'size': 1}
07:31:32.602 T:1414415264   ERROR: PLEX.librarysync: Traceback:
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1029, in process_message
                                                self.process_playing(message['PlaySessionStateNotification'])
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1279, in process_playing
                                                session_key = item['sessionKey']
                                            KeyError: 'sessionKey'
```
[logs.zip](https://github.com/croneter/PlexKodiConnect/files/2166301/logs.zip)

**Comment by Pavuucek** [comment]
👍
