### ISSUE TITLE
PlexKodiConnect does not start on Xbox One (X), Microsoft UWP 

### ISSUE THREAD

**Issue by aaronstc1** [croneter/PlexKodiConnect#521]
Receive an error immediately after installing PlexKodiConnect. Also receive error upon restarting Kodi with add-on still installed. 

https://paste.kodi.tv/aluniqisij

Thanks.

**Comment by croneter** [comment]
Ough, this is looking very ugly:
```
09:49:43.145 T:7020   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.MemoryError'>
                                            Traceback (most recent call last):
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\service.py", line 4, in <module>
                                                from resources.lib import service_entry
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\service_entry.py", line 8, in <module>
                                                from . import utils
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\utils.py", line 24, in <module>
                                                from . import path_ops
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\path_ops.py", line 21, in <module>
                                                from .watchdog.utils import unicode_paths
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\watchdog\utils\__init__.py", line 42, in <module>
                                                import win32stat
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\watchdog\utils\win32stat.py", line 28, in <module>
                                                import ctypes
                                              File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.125.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 556, in <module>
                                                _reset_cache()
                                              File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.125.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 276, in _reset_cache
                                                CFUNCTYPE(c_int)(lambda: None)
                                            MemoryError
                                            -->End of Python script error report<--
```
Kodi does not want to import an existing "standard" Python module that PlexKodiConnect needs (or the Python module "watchdog" respectively, which PKC needs). 

Others have had similar issues. I posted in the Kodi forums to see if they know how to solve this: https://forum.kodi.tv/showthread.php?tid=329171&pid=2756715#pid2756715

Any way you could try stable Kodi 17.6? The alpha version might be the issue...

**Comment by aaronstc1** [comment]
Unfortunately, 18 Leia is the only version available on Xbox. 
Although, I had no issues on Windows 10 with 17.6 (though I doubt that bit of info is particularly useful).

**Comment by aaronstc1** [comment]
Still no go.

https://paste.kodi.tv/qafofativo

**Comment by croneter** [comment]
How about now, beta version 2.3.6?

**Comment by aaronstc1** [comment]
No errors with 2.3.6. Do I still need to not sync playlists?

**Comment by croneter** [comment]
Great!

Unfortunately, you will not be able to sync playlists from Kodi to Plex - that piece of software is unavailable with the Xbox restrictions. For more info, see here https://forum.kodi.tv/showthread.php?tid=326228
