### ISSUE TITLE
Seemingly random issue with being unable to play

### ISSUE THREAD

**Issue by kocane** [croneter/PlexKodiConnect#541]
I wish I had a better bug report than this. I'm running Kodi + PlexKodiConnect on various of my family members Raspberry Pis. I myself rarely encounter issues but especially my parents, who have the setup which is located locally where the mediaserver is, often experience being unable to play items. It will simply keep spinning as the item is selected.
It can be a bit hard since I'm rarely on-site but thru SSH I grabbed the log from the raspi, as my dad told me a movie wouldn't play. This was what I could find in the log:
```
20:42:45.695 T:1945526848  NOTICE: ADDONS: Using repository repository.kodi.game
20:42:45.695 T:1945526848  NOTICE: ADDONS: Using repository repository.libreelec.tv
20:42:45.695 T:1945526848  NOTICE: ADDONS: Using repository repository.plexkodiconnectbeta
20:42:45.695 T:1945526848  NOTICE: ADDONS: Using repository repository.xbmc.org
20:42:45.695 T:1945526848  NOTICE: ADDONS: Using repository repository.plexkodiconnectbeta
20:42:45.695 T:1945526848  NOTICE: ADDONS: Using repository repository.xbmc.org
20:42:46.175 T:1735390112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named defusedxml.ElementTree
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 4, in <module>
                                                from resources.lib import service_entry
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 8, in <module>
                                                from . import utils
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 16, in <module>
                                                import defusedxml.ElementTree as defused_etree  # etree parse unsafe
                                            ImportError: No module named defusedxml.ElementTree
                                            -->End of Python script error report<--
20:42:46.823 T:1945526848   ERROR: Window Translator: Can't find window videolibrary
20:42:46.823 T:1945526848 WARNING: Label Formating: $VAR[GlobalFanartVar] is not defined
20:42:47.552 T:1945526848 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
20:42:47.552 T:1945526848  NOTICE: LoadJpeg: unable to load /usr/share/kodi/addons/service.libreelec.settings/resources/skins/Default/media/default/bg.jpg
20:42:48.221 T:1617949600   ERROR: GetDirectory - Error getting
20:42:54.017 T:1506468768   ERROR: Previous line repeats 6 times.
20:42:54.017 T:1506468768  NOTICE: PLEX.MOVIES: PKC add-on for movies started
20:44:39.151 T:1945526848   ERROR: CPythonInvoker(5, /storage/.kodi/addons/plugin.video.plexkodiconnect.movies/default.py): script didn't stop in 5 seconds - let's kill it
20:44:39.151 T:1945526848   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.plexkodiconnect.movies/?plex_id=7074&plex_type=movie&mode=play&filename=darkest.hour.2017.720p.bluray.x264-drones[EtHD].mp4]
20:44:43.873 T:1506468768  NOTICE: PLEX.MOVIES: PKC add-on for movies started
20:44:52.188 T:1945526848   ERROR: CPythonInvoker(6, /storage/.kodi/addons/plugin.video.plexkodiconnect.movies/default.py): script didn't stop in 5 seconds - let's kill it
20:44:52.189 T:1945526848   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.plexkodiconnect.movies/?plex_id=7074&plex_type=movie&mode=play&filename=darkest.hour.2017.720p.bluray.x264-drones[EtHD].mp4]
20:44:57.228 T:1498080160  NOTICE: PLEX.MOVIES: PKC add-on for movies started
20:46:45.155 T:1945526848   ERROR: CPythonInvoker(7, /storage/.kodi/addons/plugin.video.plexkodiconnect.movies/default.py): script didn't stop in 5 seconds - let's kill it
20:46:45.155 T:1945526848   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.plexkodiconnect.movies/?plex_id=7081&plex_type=movie&mode=play&filename=The.Proposition.2005.BluRay.720p.x264.DTS-WiKi.mp4]
```
It is running LibreELEC, latest stable, along with PlexKodiConnect Beta as I found that it addresses some issues that the stable version has. But this issue here actually dates back to before switching to the beta repository.

Perhaps I should aim to use direct paths, atleast locally? Could that make things more stable?

**Comment by croneter** [comment]
You somehow did not install PKC correctly, or pkc did not update correctly. You're missing the Kodi dependency defusedxml. Reinstall PKC from the Repo, over your existing pkc version. See https://github.com/croneter/PlexKodiConnect/wiki/Install-PKC-from-PKC-Repo

**Comment by croneter** [comment]
Naturally you should never have to worry about these dependencies

**Comment by croneter** [comment]
You'd have to get another COMPLETE log to see if something else is affecting playback

**Comment by croneter** [comment]
Any luck @kocane ?

**Comment by kocane** [comment]
@croneter I haven't been at the place where the problematic raspberry pi is, and I'm not experiencing issues on any of my own devices. When I get the chance I'll reinstall LibreELEC and the latest beta on the problematic Raspberry Pi and see...
I don't know if it matters, but it's set up with multiple Kodi problems where each profile has its own sources and database. Could that cause issues or is there a recommended way of doing this? 
I can also give direct paths a go and see how it runs.

**Comment by croneter** [comment]
No multiple Kodi profiles combined with Plex users should pose no issue whatsoever. It's really just that missing dependency until you convince me otherwise ;-)

**Comment by croneter** [comment]
I assume this is fixed, especially if you're using the latest beta 😉 . Let me know here if you still have issues!

**Comment by kocane** [comment]
Hey @croneter 
I got a chance to take a look again and reinstall PKC (and the entire LibreELEC too, tbh). I've set it up with direct paths and playback seems to work fine but I'm getting an error upon startup:
```
13:09:26.963 T:1658975136  NOTICE: PLEX.service_entry: ======== START PlexKodiConnect ========
13:09:26.963 T:1658975136  NOTICE: PLEX.service_entry: Platform: Linux
13:09:26.964 T:1658975136  NOTICE: PLEX.service_entry: KODI Version: 17.6 Git:a9a7a20
13:09:26.966 T:1658975136  NOTICE: PLEX.service_entry: PlexKodiConnect Version: 2.4.10
13:09:26.980 T:1658975136  NOTICE: PLEX.service_entry: PKC Direct Paths: True
13:09:26.993 T:1658975136  NOTICE: PLEX.service_entry: Number of sync threads: 10
13:09:26.994 T:1658975136  NOTICE: PLEX.service_entry: Playlist m3u encoding: utf-8
13:09:26.996 T:1658975136  NOTICE: PLEX.service_entry: Full sys.argv received: ['']
13:09:27.015 T:1658975136  NOTICE: PLEX.service_entry: Sync playlists: true
13:09:27.035 T:1658975136  NOTICE: PLEX.service_entry: Synching only specific Kodi playlists: False
13:09:27.053 T:1658975136  NOTICE: PLEX.service_entry: Kodi playlist prefix: sync_
13:09:27.070 T:1658975136  NOTICE: PLEX.service_entry: Synching only specific Plex playlists: False
13:09:27.084 T:1658975136  NOTICE: PLEX.service_entry: Play playlist prefix: sync_
13:09:27.085 T:1658975136  NOTICE: PLEX.service_entry: XML decoding being used: cElementTree
13:09:27.086 T:1658975136  NOTICE: PLEX.initialsetup: Start (re-)loading PKC settings
13:09:27.088 T:1658975136  NOTICE: PLEX.videonodes: Clearing nodes properties.
13:09:27.483 T:1658975136  NOTICE: PLEX.clientinfo: Unique device Id plex_client_Id loaded: 0a4248d8-ba40-47fd-abf2-746be0db7dbf
13:09:27.487 T:1658975136  NOTICE: PLEX.initialsetup: Done (re-)loading PKC settings
13:09:27.604 T:1658975136  NOTICE: PLEX.initialsetup: Initial setup called.
13:09:27.620 T:1658975136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 8, in <module>
                                                service_entry.start()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 286, in start
                                                Service().ServiceEntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 88, in ServiceEntryPoint
                                                initialsetup.InitialSetup().setup()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/initialsetup.py", line 480, in setup
                                                top_element='advancedsettings') as xml:
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 677, in __enter__
                                                self.tree = defused_etree.parse(self.path)
                                              File "/storage/.kodi/addons/script.module.defusedxml/lib/defusedxml/common.py", line 100, in parse
                                                return _parse(source, parser)
                                              File "<string>", line 62, in parse
                                              File "<string>", line 25, in parse
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--

```
I'm not sure what it means.
Also, as mentioned I'm using multiple users. When creating new users the PKC addons (Helper etc) is disable. I enable em all but how about the dependencies, like defusedxml, is it also disabled? I can't find em on the "all addons" list, to check

**Comment by croneter** [comment]
@kocane please open a new issue with your last post. Thanks!
