### ISSUE TITLE
Crashing when switching users

### ISSUE THREAD

**Issue by kocane** [croneter/PlexKodiConnect#559]
It seems like when switching users I experience issues with PKC.

I noticed that a family members watch history was off. Since I use direct paths, things can play fine but it's without PKC being involved. I also noticed it because "now playing" in the Plex control panel wasn't showing the user as playing anything.

If I reboot (to user selection screen) and pick the user, it works fine (usually it can easily be told by looking at "welcome *user*" pkc notification.

If I switch user I get a crash:
```
23:54:09.987 T:1687425952  NOTICE: PLEX.initialsetup: Initial setup called.
23:54:10.004 T:1687425952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not callable
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 8, in <module>
                                                service_entry.start()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 286, in start
                                                Service().ServiceEntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 88, in ServiceEntryPoint
                                                initialsetup.InitialSetup().setup()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/initialsetup.py", line 480, in setup
                                                top_element='advancedsettings') as xml:
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 677, in __enter__
                                                self.tree = defused_etree.parse(self.path)
                                              File "/storage/.kodi/addons/script.module.defusedxml/lib/defusedxml/common.py", line 100, in parse
                                                return _parse(source, parser)
                                              File "<string>", line 62, in parse
                                              File "<string>", line 25, in parse
                                            TypeError: 'NoneType' object is not callable
                                            -->End of Python script error report<--
```
[Full log is here](https://pastebin.com/EgJzNTsj)

Since issue #541 I've reinstalled Kodi and PKC. All dependencies should be there, I watched it being installed. It doesn't matter which user it is, that I switched to.

**Comment by croneter** [comment]
Can you please attach your advancedsettings.xml file here?

**Comment by kocane** [comment]
> Can you please attach your advancedsettings.xml file here?

```
<advancedsettings>
  <musiclibrary>
    <backgroundupdate>true</backgroundupdate>
  </musiclibrary>
  <videolibrary>
    <cleanonupdate>false</cleanonupdate>
  </videolibrary>
  <video>
    <ignorepercentatend>10</ignorepercentatend>
    <playcountminimumpercent>90</playcountminimumpercent>
    <ignoresecondsatstart>60</ignoresecondsatstart>
  </video>
</advancedsettings>
```

**Comment by croneter** [comment]
New PKC beta version on the way - be patient ;-)

**Comment by kocane** [comment]
@croneter  I'm kinda seeing the same issue in 2.8.7. At first I thought it was after upgrading to LibreELEC 9.0.2 but after several clean installs on both 8.2.5 and 9.0.2 - and issue remains - I think it must lie elsewhere. 

The issue happens when I log out of a secondary profile (not master). On Leia it would display the "welcome *master username*" on the loginscreen itself BEFORE i actually log in. I'm not sure if this is what causes some issues.  Because if I then select another non-masteruser, it doesn't display the welcome message (and videos can't play) but rather displays this error in the kodi.log:
```
2019-07-20 00:53:40.066 T:1646719856  NOTICE: PLEX.service: Another service.py instance is already running - shutting it down now
2019-07-20 00:53:42.943 T:1576764272   ERROR: ## LibreELEC Addon ## connman::monitor::initialize_agent ## ERROR: (TypeError("'NoneType' object is not callable",))
2019-07-20 00:53:42.945 T:1576764272   ERROR: Traceback (most recent call last):
                                              File "/var/lib/jenkins/LE/build2/workspace/RPi2/build.LibreELEC-RPi2.arm-9.0.2/LibreELEC-settings-37e206b712a46213522a567a408382f5f082502a/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/resources/lib/modules/connman.py", line 1263, in initialize_agent
                                              File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
                                              File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
                                              File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 175, in activate_name_owner
                                              File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 358, in get_name_owner
                                              File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 526, in _signal_func
                                            TypeError: 'NoneType' object is not callable
2019-07-20 00:53:48.765 T:1646719856   ERROR: PLEX.service: Could not tell other PKC instance to shut down
```

**Comment by kocane** [comment]
Hm. Jumped all the way back to 2.8.0 where it also seems to be happening

**Comment by croneter** [comment]
As always, please share your entire debug log: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by kocane** [comment]
@croneter ofcourse, sorry - [here you go](https://pastebin.com/gStHsMxv). Errors out towards the end of the log.

**Comment by croneter** [comment]
This is a LibreElec bug, please bring it up with their team
```
2019-07-20 09:56:06.651 T:1553711984   ERROR: ## LibreELEC Addon ## connman::monitor::initialize_agent ## ERROR: (TypeError("'NoneType' object is not callable",))
2019-07-20 09:56:06.651 T:1553711984   ERROR: Traceback (most recent call last):
                                              File "/var/lib/jenkins/LE/build2/workspace/RPi2/build.LibreELEC-RPi2.arm-9.0.2/LibreELEC-settings-37e206b712a46213522a567a408382f5f082502a/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/resources/lib/modules/connman.py", line 1263, in initialize_agent
                                              File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
                                              File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
                                              File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 175, in activate_name_owner
                                              File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 358, in get_name_owner
                                              File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 526, in _signal_func
                                            TypeError: 'NoneType' object is not callable
2019-07-20 09:56:12.325 T:1729733488   ERROR: PLEX.service: Could not shut down other PKC instance
```
Unfortunately, this LibreElec bug leads to PKC failing... :disappointed: Nothing I can do from my side, sorry...

**Comment by kocane** [comment]
@croneter  I'll try to create a bug report for them. It's so odd I can't find anyone else with this issue. I can extremely easy replicate the issue on multiple devices. Even made a VM on my laptop with LibreELEC, where I can replicate the crashing.

**Comment by croneter** [comment]
It's still a LibreElec bug - please bring it up with them.

**Comment by kocane** [comment]
@croneter  I opened a bug report with them but nothing has happened and I'm still without proper support with multiple profiles. I have to reboot all the time :( ... I know the blame likely lies with LibreELEC but do you have any suggestions for a workaround?  I tried user Plex Home users instead, as part of the trial, but buying the Pass just for that functionality just seems so pricey, plus I dunno how to properly incorporate the "switch plex home user" functionality into Kodi for ease of use by family.

**Comment by croneter** [comment]
@kocane sorry, only workaround would be to log off the current Plex user when navigating to Addons - Video Add-ons - PlexKodiConnect.

Crashing when switching Kodi profiles is in Kodis court
