### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by amartini** [croneter/PlexKodiConnect#564]
Getting this error after installing PlexKodiConnect on Kodi 17.6 (Android)

```
10:38:53.003 T:537661654096   ERROR: Previous line repeats 2 times.
10:38:53.003 T:537661654096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
   - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.ImportError'>
  Error Contents: No module named requests
  Traceback (most recent call last):
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 12, in <module>
      from resources.lib import entrypoint, utils, pickler, pkc_listitem, \
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 17, in <module>
      from . import initialsetup
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/initialsetup.py", line 13, in <module>
      from .downloadutils import DownloadUtils as DU
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/downloadutils.py", line 6, in <module>
      import requests
  ImportError: No module named requests
  -->End of Python script error report<--

```

**Comment by dazedcrazy** [comment]
I'm guessing you are missing the requests module https://mirrors.kodi.tv/addons/krypton/script.module.requests/

**Comment by croneter** [comment]
@dazedcrazy is correct, you need the Kodi python module "requests" installed before installing PKC. This should usually happen automatically! I don't know what went wrong with your Kodi installation. 

For a solution, see here: https://forum.kodi.tv/showthread.php?tid=237657
