### ISSUE TITLE
2.5.1 problems

### ISSUE THREAD

**Issue by dazedcrazy** [croneter/PlexKodiConnect#566]
Everytime it resynces on startup it adds another copy of what it added before
![image](https://user-images.githubusercontent.com/9027988/49343583-22742680-f664-11e8-9b4b-eb9e9e92724f.png)
![image](https://user-images.githubusercontent.com/9027988/49343584-2607ad80-f664-11e8-9a00-1b6148aa6f1c.png)
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2637247/kodi.log)
I got up to 5 copies of each episode before i reset the db and it started all over again. 

It also doesn't sync playback of episodes to PMS but it does for movies. I play 12 Monkeys - S01E01 - Splinter which doesn't get synced back to PMS then play Blade Runner 2049 which does. Log:[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2637271/kodi.log)

**Comment by croneter** [comment]
Does it only happen for episodes?

**Comment by dazedcrazy** [comment]
Not every show but the ones it does do it on it's every episode

**Comment by Pavuucek** [comment]
I'm getting duplicates of tvshows and episodes too. Also some of my movies randomly appear and disappear.

[logs+db.zip](https://github.com/croneter/PlexKodiConnect/files/2637313/logs%2Bdb.zip)

![pkc](https://user-images.githubusercontent.com/1253845/49344253-f3b27c00-f674-11e8-9c6b-1b2e3fe8dbaf.png)

**Comment by dazedcrazy** [comment]
Now when i try to sync music i am getting an error
````
20:10:45.508 T:11468   ERROR: PLEX.utils: Error encountered:  - near "WHERE": syntax error
20:10:45.509 T:11468   ERROR: PLEX.utils: _____________________________________________________________
20:10:45.509 T:11468   ERROR: PLEX.utils:     Traceback (most recent call last):
20:10:45.509 T:11468   ERROR: PLEX.utils:       File "C:\Users\komplex\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\process_metadata.py", line 77, in run
20:10:45.509 T:11468   ERROR: PLEX.utils:         self._run()
20:10:45.509 T:11468   ERROR: PLEX.utils:       File "C:\Users\komplex\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\process_metadata.py", line 119, in _run
20:10:45.509 T:11468   ERROR: PLEX.utils:         children=item['children'])
20:10:45.509 T:11468   ERROR: PLEX.utils:       File "C:\Users\komplex\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes\music.py", line 288, in add_update
20:10:45.509 T:11468   ERROR: PLEX.utils:         kodi_id)
20:10:45.509 T:11468   ERROR: PLEX.utils:       File "C:\Users\komplex\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\kodi_db\music.py", line 222, in update_album
20:10:45.509 T:11468   ERROR: PLEX.utils:         ''', (args))
20:10:45.509 T:11468   ERROR: PLEX.utils:     OperationalError: near "WHERE": syntax error
20:10:45.509 T:11468   ERROR: PLEX.utils: _____________________________________________________________
20:10:45.509 T:11468   DEBUG: PLEX.sync.process_metadata: Processing thread terminated

**Comment by Ribero** [comment]
Same thing for me. Each kodi/Pkc restart duplicates TV show episodes. 
I haven't found issues for movies and music but I need to check in-depth.

**Comment by croneter** [comment]
2.5.2 solving this issue?

**Comment by dazedcrazy** [comment]
@croneter it's not pushed to the repo yet lol

**Comment by croneter** [comment]
Should be online now - jeeeez, you're impatient 😛

**Comment by dazedcrazy** [comment]
It was a whole 2 minutes i almost had grew old waiting 😛

**Comment by dazedcrazy** [comment]
Some shows are missing all their episode and a couple still have doubles
![image](https://user-images.githubusercontent.com/9027988/49701190-14cd1c80-fbe1-11e8-9c0f-fb543e61de6b.png)
Log:[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2660876/kodi.log)

Like before movies get their playstate synced back to PMS but not tv episodes. I play The Predator (2018) which gets synced back to PMs then play an episode of Alias Grace which doesn't
Log:[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2660888/kodi.log)

**Comment by croneter** [comment]
Make sure you have 2.5.3, out a couple of minutes ago. Then reset the dB. Duplicates still showing up?

**Comment by dazedcrazy** [comment]
Still the same

**Comment by Pavuucek** [comment]
Good thing is I'm no longer getting duplicate episodes. Bad thing is I'm now getting tvshows that are just empty and don't sync even after kodi restart. Also first sync after starting kodi now takes just a second or even less, which seems suspiciously fast...
[logs+db.zip](https://github.com/croneter/PlexKodiConnect/files/2660943/logs%2Bdb.zip)

**Comment by Pavuucek** [comment]
yes, of course

**Comment by dazedcrazy** [comment]
Trying to use the PKC context menu doesn't work either.
```20:33:55.235 T:7560   DEBUG: PLEX.resources.lib.backgroundthread: (queue.0:worker.0): Active
20:33:55.236 T:7560   DEBUG: PLEX.playback_starter: Starting PlaybackTask with dummy?mode=context_menu&kodi_id=3855&kodi_type=episode
20:33:55.236 T:7560   DEBUG: PLEX.playback_starter: Received mode: context_menu, params: {u'kodi_id': u'3855', u'mode': u'context_menu', u'kodi_type': u'episode'}
20:33:55.238 T:7560   DEBUG: PLEX.context_entry: Found plex_id: None plex_type: episode
20:33:55.238 T:7560   DEBUG: PLEX.playback_starter: Finished PlaybackTask
20:33:55.238 T:7560   DEBUG: PLEX.resources.lib.backgroundthread: (queue.0:worker.0): Idle```

**Comment by dazedcrazy** [comment]
![image](https://user-images.githubusercontent.com/9027988/49702749-ea388f00-fbf3-11e8-998a-5f68331c98c6.png)
The plex.db file has no entries for episodes
I know the plex.db structure change but the stable version db for comparison
![image](https://user-images.githubusercontent.com/9027988/49702777-4bf8f900-fbf4-11e8-8bde-a5bb8dcc111b.png)

**Comment by croneter** [comment]
Try 2.5.4 please

**Comment by dazedcrazy** [comment]
I don't see any doubles, playback of episodes/movies/music all sync back to PMS. But some TV shows are missing all or some of their episodes. Log: [kodi.log](https://github.com/croneter/PlexKodiConnect/files/2664569/kodi.log)
I do see ``ERROR: PLEX.tvshows: Item not yet synced`` for shows that are missing or missing episodes

**Comment by croneter** [comment]
Did you reset the DB completely? PKC shouldn't really be missing anything, darn! Can't reproce the issue here with my setup

**Comment by dazedcrazy** [comment]
Yeah i reset it twice. I''ll try again

**Comment by croneter** [comment]
Darn. Could you please share your library with me, if you don't mind? Croneter 😉 

Logs are not really helpful with this bug. I need to track it down step-by-step

**Comment by dazedcrazy** [comment]
Shared. Also here's a log from first launch after resetting the db. [kodi.log](https://github.com/croneter/PlexKodiConnect/files/2664672/kodi.log)

**Comment by Abasz** [comment]
I think the duplicate issue is still a problem on my end with 2.5.1. Kodi rC1

**Comment by BlackMamba248** [comment]
Just updated to 2.5.5 and it seems TV shows aren't synced completely. Missing about 1/3 of total episodes for TV shows. Did sometimes see a sync error but didn't show up consistently

**Comment by Norien** [comment]
I'm seeing exactly the same thing, Kodi RC2 with add-on 2.5.5

Missing some tv series and sync error popping up randomly

**Comment by craZy-C** [comment]
I will add to that as well. Kodi 17.6 and PKC 2.5.5. No duplicates but some shows missing all together. If you add another to its folder it syncs what is missing from that folder and returns. No logs as I am at work.

**Comment by croneter** [comment]
Is beta version 2.5.6 solving this issue?

**Comment by dazedcrazy** [comment]
It's actually syncing less than it was before lol gimme a sec I'll get some logs from after a db reset

**Comment by dazedcrazy** [comment]
If you uncheck "Enable Music Library" and do a db reset the music library is still there  when you start Kodi again

**Comment by craZy-C** [comment]
I disabled music for now and updated to 2.5.6, Opted for the Kodi DB reset, last item and In my case it says unable to stop the database try again later ?

**Comment by craZy-C** [comment]
@croneter Seems my logs are huge 7.8mb and 10.8mb Have Rared them as too large fro pastebin and linked below via dropbox
https://www.dropbox.com/sh/bwx79r92hzyoxs2/AABSeHJwm6066a5egSqO7OR1a?dl=0
I still may end up wiping soon anyway
