### ISSUE TITLE
Kodi 18 RC5

### ISSUE THREAD

**Issue by ekyriakides** [croneter/PlexKodiConnect#600]
For some reason the XBOX ONE Kodi version is on RC5 which doesn't seem to work with PKC (stable or beta). Logs attached. 

Stable (2.4.1) wouldn't work at all (library sync thread has crashed). Logs below :

```
12:18:23.503 T:2136  NOTICE: PLEX.librarysync: Db version:
12:18:23.635 T:2136  NOTICE: PLEX.librarysync: Refreshing video nodes and playlists now
12:18:24.137 T:2136   ERROR: PLEX.librarysync: LibrarySync thread crashed. Error message: no such table: path
12:18:24.496 T:2136   ERROR: PLEX.librarysync: Traceback:
                                            Traceback (most recent call last):
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1500, in run
                                                self._run_internal()
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1547, in _run_internal
                                                kodi_db.setup_path_table()
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\kodidb_functions.py", line 63, in setup_path_table
                                                path_id = self.get_path('plugin://%s.movies/' % v.ADDON_ID)
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\kodidb_functions.py", line 185, in get_path
                                                (path,))
                                            OperationalError: no such table: path
12:18:24.525 T:5836   ERROR: Control 1001 in window 13001 has been asked to focus, but it can't
12:18:30.515 T:2136   ERROR: Exception in thread Thread-8:
                                            Traceback (most recent call last):
                                              File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.140.70_x64__4n2hpmxwrvr6p\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1500, in run
                                                self._run_internal()
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1547, in _run_internal
                                                kodi_db.setup_path_table()
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\kodidb_functions.py", line 63, in setup_path_table
                                                path_id = self.get_path('plugin://%s.movies/' % v.ADDON_ID)
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\kodidb_functions.py", line 185, in get_path
                                                (path,))
                                            OperationalError: no such table: path
12:19:45.139 T:2532   ERROR: XFILE::CDirectory::GetDirectory - Error getting
12:20:17.656 T:2532   ERROR: Previous line repeats 2 times.
```

Latest BETA  (2.5.13). Logs below :

```
11:42:53.783 T:2468   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.MemoryError'>
                                            Traceback (most recent call last):
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\service.py", line 4, in <module>
                                                from resources.lib import service_entry
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\service_entry.py", line 12, in <module>
                                                from . import sync
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\sync.py", line 8, in <module>
                                                from . import library_sync, timing
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\__init__.py", line 6, in <module>
                                                from .websocket import store_websocket_message, process_websocket_messages, \
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\websocket.py", line 12, in <module>
                                                from .. import backgroundthread, playlists, plex_functions as PF, itemtypes
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\playlists\__init__.py", line 17, in <module>
                                                from .common import Playlist, PlaylistError, PlaylistObserver
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\playlists\common.py", line 8, in <module>
                                                from ..watchdog import events
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\watchdog\events.py", line 92, in <module>
                                                from .utils import has_attribute
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\watchdog\utils\__init__.py", line 42, in <module>
                                                import win32stat
                                              File "U:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\plugin.video.plexkodiconnect\resources\lib\watchdog\utils\win32stat.py", line 28, in <module>
                                                import ctypes
                                              File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.140.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 556, in <module>
                                                _reset_cache()
                                              File "S:\Program Files\WindowsApps\XBMCFoundation.Kodi_17.9.140.70_x64__4n2hpmxwrvr6p\system\python\Lib\ctypes\__init__.py", line 276, in _reset_cache
                                                CFUNCTYPE(c_int)(lambda: None)
                                            MemoryError
                                            -->End of Python script error report<--
11:42:55.423 T:1920   ERROR: AddOnLog: Joystick Support: Device "Sony Interactive Entertainment Wireless Controller": can't find <controller> tag
11:42:55.545 T:1920  NOTICE: PERIPHERALS::CPeripheralAddon::Register - new joystick device registered on addon->peripheral.joystick/0: Xbox 360-compatible controller
11:43:12.915 T:3356   ERROR: XFILE::CDirectory::GetDirectory - Error getting
11:43:14.997 T:4556   ERROR: Previous line repeats 6 times.
11:43:14.997 T:4556  NOTICE: PLEX.default: plugin.video.plexkodiconnect started
11:43:15.103 T:4556  NOTICE: PLEX.default: plugin.video.plexkodiconnect stopped
11:43:21.100 T:660  NOTICE: PLEX.default: plugin.video.plexkodiconnect started
11:43:21.108 T:660  NOTICE: PLEX.default: plugin.video.plexkodiconnect stopped
11:43:21.212 T:2404   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.plexkodiconnect/?mode=settings
11:43:26.163 T:1832   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexkodiconnect/?mode=settings) failed
11:43:27.835 T:6052  NOTICE: PLEX.default: plugin.video.plexkodiconnect started
11:43:27.840 T:6052  NOTICE: PLEX.default: plugin.video.plexkodiconnect stopped
11:43:48.989 T:1832   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
11:43:52.461 T:636  NOTICE: PLEX.default: plugin.video.plexkodiconnect started
11:43:52.466 T:636  NOTICE: PLEX.default: plugin.video.plexkodiconnect stopped
11:43:52.560 T:3496   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.plexkodiconnect/?mode=settings
11:45:58.872 T:1832   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexkodiconnect/?mode=settings) failed
11:46:00.462 T:3972  NOTICE: PLEX.default: plugin.video.plexkodiconnect started
11:46:00.466 T:3972  NOTICE: PLEX.entrypoint: Request to manually enter new PMS address
11:46:16.422 T:1688  NOTICE: PLEX.default: plugin.video.plexkodiconnect started
11:46:16.744 T:1832   ERROR: Control 1001 in window 13000 has been asked to focus, but it can't
11:46:52.823 T:1688  NOTICE: PLEX.default: plugin.video.plexkodiconnect stopped
11:47:10.084 T:5008   ERROR: XFILE::CDirectory::GetDirectory - Error getting
```

**Comment by croneter** [comment]
Sorry, only "official" Kodi 18 Release Candidates are supported. Use Kodi 17.6 until you can get a more stable Kodi version for XBOX. 

Example: I cannot do anything about the first `MemoryError`

**Comment by MacQwerty** [comment]
@ekyriakides, make sure you at least use the beta release channel as not even Kodi 18 RC4 is supported by the stable version yet. Hopefully the beta version will work, otherwise, you have to go back to an earlier version and wait for a KODI 18 version PKC supports

**Comment by ekyriakides** [comment]
@MacQwerty Unfortunately us (XBOX ONE users) can't control what version is on the Microsoft/Xbox One store. I used to have RC3 which kind of worked (nothing showed up after sync, only in folders) and I thought let's re-install Kodi... Then RC5 got installed and since then I can't get stable nor beta to work at all.

**Comment by Lukeid** [comment]
Hello @croneter,

I have problems also with RC5, I get the following error with Kodi 18 RC5 and PKC v2.5.14:
OperationalError: no such table: main.actor

I know RC5 it is not supported yet, but it may help to make it compatible in the future.

Bets regards,
Lukeid

**Comment by Lukeid** [comment]
Hello again,

Today PKC was updated to v2.5.16, now it is working.

Thank you!

**Comment by shareonline** [comment]
Hmm brand new install for me with 18.5 RC and v2. 5.19 but all I get is an error under startup. No setup link or alike.. 😕

**Comment by croneter** [comment]
@shareonline
Also follow the setup instructions here on the  Github Wiki to the letter...

**Comment by shareonline** [comment]
> @shareonline
> Do NOT get the Kodi nightly version but the official RC 5.2 build from [www.kodi.tv/download](http://www.kodi.tv/download)

Hey @croneter . and thank you so much for PKC! We are using it all over the house :) 
I should have posted more info, so sorry about that. I tried this on my xbox one just for kicks, and xbox users can't really choose what build we are going to use. 
I'm not sure we can even get logs, but maybe kodi has an extention for it, so we can copy logs to usb or something.
But for me don't do more about this issue, i can see that xbox one kodi and pkc is still a little sketchy for users, and it is probably because the xbox builds are missing some things (don't know for sure). 
We have Nvidia Shield all around the house and use your stable version, and have absolutely zero issues :)
Keep up what you are doing @croneter you are effectively fixing what both Kodi and Plex should have done for themselves a long time ago ;)

**Comment by croneter** [comment]
Thanks :laughing: Yes, Xbox builds are still a problem!
