### ISSUE TITLE
plexkodiconnect v2.5.22 not support with  Kodi: 18 Leia rc5

### ISSUE THREAD

**Issue by mutluerol** [croneter/PlexKodiConnect#625]
19:19:01.114 T:140473607907072  NOTICE: PLEX.service: Delaying Plex startup by: 0 sec...
19:19:01.117 T:140473607907072   ERROR: PLEX.service: The current Kodi version is incompatible
19:19:01.117 T:140473607907072   ERROR: PLEX.service: Error: Video DB 115 not supported
19:19:01.165 T:140475456703040   ERROR: Control 1001 in window 13000 has been asked to focus, but it can't

19:18:59.404 T:140473280755456  NOTICE: ADDON: plugin.video.plexkodiconnect v2.5.22 installed

Kodi: 18 Leia rc5

**Comment by mutluerol** [comment]
I am using Gentoo Distro, so i am installing emerge way. 
it is not nightly. it is kodi-18.0_rc5

**Comment by MacQwerty** [comment]
Kodi 18 final is scheduled to [January 31](https://github.com/xbmc/xbmc/milestone/117), so there shouldn't be a too long wait 👍

**Comment by mutluerol** [comment]
Ok, Thank You. I will wait :+1:  :))

**Comment by croneter** [comment]
Exactly the same - use an official RC download

**Comment by mutluerol** [comment]
still i have problem with plex channels listing channels but not working; i have 3 plugins; LiveTVH, Youtube, IPTV;
error below;

22:07:05.396 T:140208716191488   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OverflowError'>
                                            Error Contents: Python int too large to convert to SQLite INTEGER
                                            Traceback (most recent call last):
                                              File "/home/erol/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 201, in <module>
                                                Main()
                                              File "/home/erol/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 64, in __init__
                                                plex_section_id=params.get('id'))
                                              File "/home/erol/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 761, in browse_plex
                                                __build_item(item, direct_paths)
                                              File "/home/erol/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 862, in __build_item
                                                listitem = api.create_listitem()
                                              File "/home/erol/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_api.py", line 1540, in create_listitem
                                                append_sxxexx)
                                              File "/home/erol/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_api.py", line 1643, in _create_video_listitem
                                                db_item = plexdb.item_by_id(plex_id, self.plex_type())
                                              File "/home/erol/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_db/common.py", line 87, in item_by_id
                                                answ = method(plex_id)
                                              File "/home/erol/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_db/movies.py", line 51, in movie
                                                (plex_id, ))
                                            OverflowError: Python int too large to convert to SQLite INTEGER
                                            -->End of Python script error report<--

**Comment by croneter** [comment]
@mutluerol 
Open a new issue and share your entire DEBUG log please as explained here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
