### ISSUE TITLE
Changed to beta repo

### ISSUE THREAD

**Issue by loeffelpan** [croneter/PlexKodiConnect#631]
I just changed to beta repo and got an error on starting kodi.
Should I do something more than uninstalling from native repo and installing from beta repo?

```
09:24:57.738 T:1684927232  NOTICE: PLEX.service: Delaying Plex startup by: 0 sec...
09:25:00.449 T:1684927232  NOTICE: PLEX.service: ======== START PlexKodiConnect ========
09:25:00.450 T:1684927232  NOTICE: PLEX.service: Platform: Linux
09:25:00.482 T:1684927232  NOTICE: PLEX.service: KODI Version: 17.6
09:25:00.483 T:1684927232  NOTICE: PLEX.service: PlexKodiConnect Version: 2.5.22
09:25:00.499 T:1684927232  NOTICE: PLEX.service: PKC Direct Paths: True
09:25:00.511 T:1684927232  NOTICE: PLEX.service: Number of sync threads: 10
09:25:00.512 T:1684927232  NOTICE: PLEX.service: Playlist m3u encoding: utf-8
09:25:00.513 T:1684927232  NOTICE: PLEX.service: Full sys.argv received: ['']
09:25:00.527 T:1684927232  NOTICE: PLEX.service: Sync playlists: false
09:25:00.539 T:1684927232  NOTICE: PLEX.service: Synching only specific Kodi playlists: False
09:25:00.551 T:1684927232  NOTICE: PLEX.service: Kodi playlist prefix: sync_
09:25:00.565 T:1684927232  NOTICE: PLEX.service: Synching only specific Plex playlists: False
09:25:00.577 T:1684927232  NOTICE: PLEX.service: Play playlist prefix: sync_
09:25:00.596 T:1684927232  NOTICE: PLEX.service: Db version: 2.4.11
09:25:00.597 T:1684927232  NOTICE: PLEX.service: Kodi video database version: 107
09:25:00.597 T:1684927232  NOTICE: PLEX.service: Kodi music database version: 60
09:25:00.598 T:1684927232  NOTICE: PLEX.service: Kodi texture database version: 13
09:25:02.450 T:1684927232  NOTICE: PLEX.videonodes: Clearing nodes properties.
09:25:02.462 T:1684927232  NOTICE: PLEX.clientinfo: Unique device Id plex_client_Id loaded: b2f4bbad-c674-4532-8e2b-59e11b9ed7ac
09:25:04.951 T:1684927232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: ''
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 8, in <module>
                                                service_entry.start()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 514, in start
                                                Service().ServiceEntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 361, in ServiceEntryPoint
                                                app.init()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/app/__init__.py", line 27, in init
                                                APP = App(entrypoint)
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/app/application.py", line 18, in __init__
                                                self.load()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/app/application.py", line 44, in load
                                                self.fetch_pms_item_number = int(utils.settings('fetch_pms_item_number'))
                                            ValueError: invalid literal for int() with base 10: ''
                                            -->End of Python script error report<--
```

**Comment by croneter** [comment]
A Kodi setting for PKC got corrupted. This can happen from time to time, unfortunately. 

Please reset the PKC settings. Go to the PKC settings, then hit "Default values" or some such thing. 

Let me know if this does not help

**Comment by croneter** [comment]
Ah yeah - you need to restart Kodi after that 🙂

**Comment by loeffelpan** [comment]
If a setting got corrupted, why does changing back to native repo work without reset settings?

**Comment by croneter** [comment]
"no value" should not even be possible - it's what's crashing PKC. Glad it's solved now
