### ISSUE TITLE
plexkodiconnect sequence item 0: expected string or unicode, int found

### ISSUE THREAD

**Issue by krachlatte** [croneter/PlexKodiConnect#658]
after upgrading kodi to leia this error is showing, and there are not image availaible

plexkodiconnect sequence item 0: expected string or unicode, int found

please let me kno what you need

**Comment by croneter** [comment]
I need logs, please follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by krachlatte** [comment]
here we go then:

20:29:03.570 T:27736   ERROR: PLEX.utils: Error encountered: sync.py crashed - sequence item 0: expected string or Unicode, int found
20:29:03.590 T:27736   ERROR: PLEX.utils: _____________________________________________________________
20:29:03.592 T:27736   ERROR: PLEX.utils:     Traceback (most recent call last):
20:29:03.593 T:27736   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 145, in run
20:29:03.595 T:27736   ERROR: PLEX.utils:         self._run_internal()
20:29:03.598 T:27736   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 203, in _run_internal
20:29:03.599 T:27736   ERROR: PLEX.utils:         self.start_library_sync(show_dialog=True, block=True)
20:29:03.602 T:27736   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 100, in start_library_sync
20:29:03.603 T:27736   ERROR: PLEX.utils:         library_sync.start(show_dialog, repair, self.on_library_scan_finished)
20:29:03.603 T:27736   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 433, in start
20:29:03.604 T:27736   ERROR: PLEX.utils:         FullSync(repair, callback, show_dialog).run()
20:29:03.605 T:27736   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 954, in wrapper
20:29:03.606 T:27736   ERROR: PLEX.utils:         result = func(*args, **kwargs)
20:29:03.607 T:27736   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 409, in run
20:29:03.607 T:27736   ERROR: PLEX.utils:         if PLAYLIST_SYNC_ENABLED and not playlists.full_sync():
20:29:03.608 T:27736   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/__init__.py", line 165, in full_sync
20:29:03.609 T:27736   ERROR: PLEX.utils:         return _full_sync()
20:29:03.609 T:27736   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/__init__.py", line 248, in _full_sync
20:29:03.610 T:27736   ERROR: PLEX.utils:         plex_pl.create(playlist)
20:29:03.610 T:27736   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/plex_pl.py", line 31, in create
20:29:03.611 T:27736   ERROR: PLEX.utils:         pms.add_items(playlist, plex_ids)
20:29:03.611 T:27736   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/pms.py", line 111, in add_items
20:29:03.612 T:27736   ERROR: PLEX.utils:         % (app.CONN.machine_identifier, ','.join(plex_ids)))
20:29:03.613 T:27736   ERROR: PLEX.utils:     TypeError: sequence item 0: expected string or Unicode, int found
20:29:03.614 T:27736   ERROR: PLEX.utils: _____________________________________________________________
20:29:03.616 T:25182   DEBUG: ------ Window Init (DialogNotification.xml) ------
20:29:03.617 T:27736   ERROR: Exception in thread Thread-3:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 145, in run
                                                self._run_internal()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 203, in _run_internal
                                                self.start_library_sync(show_dialog=True, block=True)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 100, in start_library_sync
                                                library_sync.start(show_dialog, repair, self.on_library_scan_finished)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 433, in start
                                                FullSync(repair, callback, show_dialog).run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 954, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 409, in run
                                                if PLAYLIST_SYNC_ENABLED and not playlists.full_sync():
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/__init__.py", line 165, in full_sync
                                                return _full_sync()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/__init__.py", line 248, in _full_sync
                                                plex_pl.create(playlist)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/plex_pl.py", line 31, in create
                                                pms.add_items(playlist, plex_ids)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/pms.py", line 111, in add_items
                                                % (app.CONN.machine_identifier, ','.join(plex_ids)))
                                            TypeError: sequence item 0: expected string or Unicode, int found

**Comment by croneter** [comment]
You did not follow the instructions. Please enable debug logging, reproduce the issue and share the entire log (just drop the file here). Be sure to remove the Plex tokens

**Comment by krachlatte** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2818923/kodi.log)
please find the full file including debug and tokens removed....

traceback stays the same

many thanks for looking into this

**Comment by croneter** [comment]
Fixed in 2.6.2

**Comment by croneter** [comment]
You're welcome. No it's in stable also
