### ISSUE TITLE
KeyError: sessionKey and PKC not synching as a consequence

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#659]
```
13:22:06.488 T:139850589460224   ERROR: PLEX.utils: Error encountered: sync.py crashed - u'sessionKey'
13:22:06.490 T:139850589460224   ERROR: PLEX.utils: _____________________________________________________________
13:22:06.490 T:139850589460224   ERROR: PLEX.utils:     Traceback (most recent call last):
13:22:06.490 T:139850589460224   ERROR: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 145, in run
13:22:06.490 T:139850589460224   ERROR: PLEX.utils:         self._run_internal()
13:22:06.490 T:139850589460224   ERROR: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 275, in _run_internal
13:22:06.490 T:139850589460224   ERROR: PLEX.utils:         library_sync.store_websocket_message(message)
13:22:06.490 T:139850589460224   ERROR: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/websocket.py", line 44, in store_websocket_message
13:22:06.491 T:139850589460224   ERROR: PLEX.utils:         process_playing(message['PlaySessionStateNotification'])
13:22:06.491 T:139850589460224   ERROR: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/websocket.py", line 259, in process_playing
13:22:06.491 T:139850589460224   ERROR: PLEX.utils:         session_key = message['sessionKey']
13:22:06.491 T:139850589460224   ERROR: PLEX.utils:     KeyError: u'sessionKey'
13:22:06.491 T:139850589460224   ERROR: PLEX.utils: _____________________________________________________________
13:22:06.491 T:139850589460224   ERROR: Exception in thread Thread-3:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 145, in run
                                                self._run_internal()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 275, in _run_internal
                                                library_sync.store_websocket_message(message)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/websocket.py", line 44, in store_websocket_message
                                                process_playing(message['PlaySessionStateNotification'])
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/websocket.py", line 259, in process_playing
                                                session_key = message['sessionKey']
                                            KeyError: u'sessionKey'
```

Workaround for now: reboot Kodi

**Comment by croneter** [comment]
Fixed in 2.6.2
