### ISSUE TITLE
Cache All Artwork fails on 2.6.1

### ISSUE THREAD

**Issue by jbruns** [croneter/PlexKodiConnect#665]
Kodi 17.6 - Android 8/SHIELD TV - PKC 2.6.1 (clean install today)

Repro:
Instruct PKC to cache all artwork. Confirm the operation. Reset the existing cache.

Logging:
```11:42:44.794 T:203541107952  NOTICE: PLEX.kodi_db: Resetting cached artwork
11:42:45.946 T:203541107952   ERROR: PLEX.utils: Error encountered: sync.py crashed - 'ImageCachingThread' object has no attribute 'cancel'
11:42:45.950 T:203541107952   ERROR: PLEX.utils: _____________________________________________________________
11:42:45.950 T:203541107952   ERROR: PLEX.utils:     Traceback (most recent call last):
11:42:45.952 T:203541107952   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 145, in run
11:42:45.952 T:203541107952   ERROR: PLEX.utils:         self._run_internal()
11:42:45.953 T:203541107952   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 244, in _run_internal
11:42:45.953 T:203541107952   ERROR: PLEX.utils:         self.triage_lib_scans()
11:42:45.954 T:203541107952   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 81, in triage_lib_scans
11:42:45.954 T:203541107952   ERROR: PLEX.utils:         self.start_image_cache_thread()
11:42:45.954 T:203541107952   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 138, in start_image_cache_thread
11:42:45.954 T:203541107952   ERROR: PLEX.utils:         self.image_cache_thread.cancel()
11:42:45.955 T:203541107952   ERROR: PLEX.utils:     AttributeError: 'ImageCachingThread' object has no attribute 'cancel'
11:42:45.955 T:203541107952   ERROR: PLEX.utils: _____________________________________________________________
11:42:45.955 T:203541107952   ERROR: Exception in thread Thread-3:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM64/tools/depends/xbmc-depends/aarch64-linux-android-android-21/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 145, in run
                                                self._run_internal()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 244, in _run_internal
                                                self.triage_lib_scans()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 81, in triage_lib_scans
                                                self.start_image_cache_thread()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 138, in start_image_cache_thread
                                                self.image_cache_thread.cancel()
                                            AttributeError: 'ImageCachingThread' object has no attribute 'cancel'```

**Comment by croneter** [comment]
Fixed in 2.6.2
