### ISSUE TITLE
Error encountered: sync.py crashed - u'sessionKey' (stops PKC background sync)

### ISSUE THREAD

**Issue by ashleybone** [croneter/PlexKodiConnect#728]
Kodi v18, PKC v 2.7.0, PMS v1.14.1.5488

I saw a new KeyError today when an error notification - u'kodi_type' - popped up on Kodi (running on Windows 7).  Background sync would not work after the error until Kodi was restarted.  Interestingly, I had another instance of Kodi (running on Linux) up at the time, and it did not encounter this error - no log file error message, and background sync continued to work.

Sorry for the lack of debug messages in the log snippet, but I've only seen this happen once after running PKC for the last few weeks.

```
13:31:07.568 T:2788   ERROR: PLEX.utils: Error encountered: sync.py crashed - u'kodi_type'
13:31:07.569 T:2788   ERROR: PLEX.utils: _____________________________________________________________
13:31:07.569 T:2788   ERROR: PLEX.utils:     Traceback (most recent call last):
13:31:07.569 T:2788   ERROR: PLEX.utils:       File "C:\Users\ashley\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\sync.py", line 124, in run
13:31:07.570 T:2788   ERROR: PLEX.utils:         self._run_internal()
13:31:07.570 T:2788   ERROR: PLEX.utils:       File "C:\Users\ashley\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\sync.py", line 246, in _run_internal
13:31:07.570 T:2788   ERROR: PLEX.utils:         library_sync.store_websocket_message(message)
13:31:07.570 T:2788   ERROR: PLEX.utils:       File "C:\Users\ashley\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\websocket.py", line 42, in store_websocket_message
13:31:07.570 T:2788   ERROR: PLEX.utils:         process_playing(message['PlaySessionStateNotification'])
13:31:07.570 T:2788   ERROR: PLEX.utils:       File "C:\Users\ashley\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\websocket.py", line 349, in process_playing
13:31:07.570 T:2788   ERROR: PLEX.utils:         app.ACCOUNT.plex_username, session['kodi_type'], plex_id,
13:31:07.570 T:2788   ERROR: PLEX.utils:     KeyError: u'kodi_type'
13:31:07.571 T:2788   ERROR: PLEX.utils: _____________________________________________________________
13:31:07.571 T:2788  NOTICE: PLEX.sync: ###===--- Sync Thread Stopped ---===###
13:31:07.572 T:2788   ERROR: Exception in thread Thread-3:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\ashley\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\sync.py", line 124, in run
                                                self._run_internal()
                                              File "C:\Users\ashley\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\sync.py", line 246, in _run_internal
                                                library_sync.store_websocket_message(message)
                                              File "C:\Users\ashley\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\websocket.py", line 42, in store_websocket_message
                                                process_playing(message['PlaySessionStateNotification'])
                                              File "C:\Users\ashley\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\library_sync\websocket.py", line 349, in process_playing
                                                app.ACCOUNT.plex_username, session['kodi_type'], plex_id,
                                            KeyError: u'kodi_type'

```

**Comment by croneter** [comment]
PKC version 2.7.1 should solve this issue. Let me know here if this is not the case.
