### ISSUE TITLE
Can't start video via Plex Website

### ISSUE THREAD

**Issue by hobbypunk90** [croneter/PlexKodiConnect#74]
Hey, it looks like the kodi api has changed in 16.1?
Everytime i try to start a video via plex website, i get this error:

```
07:52:55 T:1558705056   ERROR: EXCEPTION Thrown (PythonToCppException) :
-->Python callback/script returned the following error<--
  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.TypeError'>
  Error Contents: addtoPlaylist_xbmc() takes exactly 2 arguments (3 given)
  Traceback (most recent call last):
    File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 192, in <module>
      Main()
    File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 137, in __init__
      modes[mode](itemid, params=sys.argv[2])
    File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 68, in plexCompanion
      return playlist.Playlist().playAll(itemids, resume)
    File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist.py", line 103, in playAll
      self.__addToPlaylist(itemids, startPlayer=True)
    File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlist.py", line 81, in __addToPlaylist
      self.addtoPlaylist_xbmc(self.playlist, item)
    TypeError: addtoPlaylist_xbmc() takes exactly 2 arguments (3 given)
-->End of Python script error report<--
```

**Comment by croneter** [comment]
Does it work for you if you use another Plex client, e.g. Android or iOS?

**Comment by croneter** [comment]
Never had your problem, could not replicate it. Thanks if you test this once the next release is out ;-)
