### ISSUE TITLE
Character problem when syncing 

### ISSUE THREAD

**Issue by Lukeid** [croneter/PlexKodiConnect#772]
Hello,

Some days ago syncing stop working with following error:
```
2019-03-16 21:23:31.863 T:32173  NOTICE: PLEX.sync: Doing initial sync on Kodi startup
2019-03-16 21:23:31.869 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting definitions
2019-03-16 21:23:31.869 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: trying to load setting definitions from old format...
2019-03-16 21:23:31.881 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting values
2019-03-16 21:23:31.887 T:32173   DEBUG: CSettingsManager: requested setting (lastfullsync) was not found.
2019-03-16 21:23:31.887 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting lastfullsync. Creating a setting on-the-fly...
2019-03-16 21:23:31.887 T:32173   DEBUG: CSettingsManager: requested setting (networkCreds) was not found.
2019-03-16 21:23:31.888 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting networkCreds. Creating a setting on-the-fly...
2019-03-16 21:23:31.897 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting definitions
2019-03-16 21:23:31.897 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: trying to load setting definitions from old format...
2019-03-16 21:23:31.906 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting values
2019-03-16 21:23:31.910 T:32173   DEBUG: CSettingsManager: requested setting (lastfullsync) was not found.
2019-03-16 21:23:31.910 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting lastfullsync. Creating a setting on-the-fly...
2019-03-16 21:23:31.911 T:32173   DEBUG: CSettingsManager: requested setting (networkCreds) was not found.
2019-03-16 21:23:31.911 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting networkCreds. Creating a setting on-the-fly...
2019-03-16 21:23:31.921 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting definitions
2019-03-16 21:23:31.921 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: trying to load setting definitions from old format...
2019-03-16 21:23:31.930 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting values
2019-03-16 21:23:31.934 T:32173   DEBUG: CSettingsManager: requested setting (lastfullsync) was not found.
2019-03-16 21:23:31.934 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting lastfullsync. Creating a setting on-the-fly...
2019-03-16 21:23:31.935 T:32173   DEBUG: CSettingsManager: requested setting (networkCreds) was not found.
2019-03-16 21:23:31.935 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting networkCreds. Creating a setting on-the-fly...
2019-03-16 21:23:31.944 T:32173  NOTICE: PLEX.sync.sections: Starting synching sections from the PMS
2019-03-16 21:23:31.949 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting definitions
2019-03-16 21:23:31.950 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: trying to load setting definitions from old format...
2019-03-16 21:23:31.960 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting values
2019-03-16 21:23:31.964 T:32173   DEBUG: CSettingsManager: requested setting (lastfullsync) was not found.
2019-03-16 21:23:31.965 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting lastfullsync. Creating a setting on-the-fly...
2019-03-16 21:23:31.965 T:32173   DEBUG: CSettingsManager: requested setting (networkCreds) was not found.
2019-03-16 21:23:31.965 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting networkCreds. Creating a setting on-the-fly...
2019-03-16 21:23:32.206 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting definitions
2019-03-16 21:23:32.206 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: trying to load setting definitions from old format...
2019-03-16 21:23:32.217 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting values
2019-03-16 21:23:32.221 T:32173   DEBUG: CSettingsManager: requested setting (lastfullsync) was not found.
2019-03-16 21:23:32.221 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting lastfullsync. Creating a setting on-the-fly...
2019-03-16 21:23:32.222 T:32173   DEBUG: CSettingsManager: requested setting (networkCreds) was not found.
2019-03-16 21:23:32.222 T:32173   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting networkCreds. Creating a setting on-the-fly...
2019-03-16 21:23:32.369 T:32173  NOTICE: PLEX.sync.full_sync: Done full_sync
2019-03-16 21:23:32.370 T:32173   ERROR: PLEX.utils: Error encountered: sync.py crashed - 'ascii' codec can't encode character u'\xfa' in position 23: ordinal not in range(128)
2019-03-16 21:23:32.382 T:32173   ERROR: PLEX.utils: _____________________________________________________________
2019-03-16 21:23:32.382 T:32173   ERROR: PLEX.utils:     Traceback (most recent call last):
2019-03-16 21:23:32.383 T:32173   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 124, in run
2019-03-16 21:23:32.384 T:32173   ERROR: PLEX.utils:         self._run_internal()
2019-03-16 21:23:32.385 T:32173   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 200, in _run_internal
2019-03-16 21:23:32.387 T:32173   ERROR: PLEX.utils:         self.start_library_sync(block=True)
2019-03-16 21:23:32.387 T:32173   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 82, in start_library_sync
2019-03-16 21:23:32.388 T:32173   ERROR: PLEX.utils:         library_sync.start(show_dialog, repair, self.on_library_scan_finished)
2019-03-16 21:23:32.389 T:32173   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 451, in start
2019-03-16 21:23:32.390 T:32173   ERROR: PLEX.utils:         FullSync(repair, callback, show_dialog).run()
2019-03-16 21:23:32.391 T:32173   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 404, in run
2019-03-16 21:23:32.392 T:32173   ERROR: PLEX.utils:         self._run()
2019-03-16 21:23:32.394 T:32173   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 875, in wrapper
2019-03-16 21:23:32.395 T:32173   ERROR: PLEX.utils:         result = func(*args, **kwargs)
2019-03-16 21:23:32.396 T:32173   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 413, in _run
2019-03-16 21:23:32.397 T:32173   ERROR: PLEX.utils:         if not sections.sync_from_pms(self):
2019-03-16 21:23:32.398 T:32173   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/sections.py", line 562, in sync_from_pms
2019-03-16 21:23:32.399 T:32173   ERROR: PLEX.utils:         LOG.info('Done synching sections from the PMS: %s', SECTIONS)
2019-03-16 21:23:32.400 T:32173   ERROR: PLEX.utils:       File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 1174, in info
2019-03-16 21:23:32.401 T:32173   ERROR: PLEX.utils:       File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 1293, in _log
2019-03-16 21:23:32.402 T:32173   ERROR: PLEX.utils:       File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 1303, in handle
2019-03-16 21:23:32.403 T:32173   ERROR: PLEX.utils:       File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
2019-03-16 21:23:32.404 T:32173   ERROR: PLEX.utils:       File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 766, in handle
2019-03-16 21:23:32.405 T:32173   ERROR: PLEX.utils:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/loghandler.py", line 49, in emit
2019-03-16 21:23:32.406 T:32173   ERROR: PLEX.utils:         xbmc.log(try_encode(self.format(record)),
2019-03-16 21:23:32.407 T:32173   ERROR: PLEX.utils:       File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 741, in format
2019-03-16 21:23:32.408 T:32173   ERROR: PLEX.utils:       File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 465, in format
2019-03-16 21:23:32.409 T:32173   ERROR: PLEX.utils:       File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 329, in getMessage
2019-03-16 21:23:32.410 T:32173   ERROR: PLEX.utils:     UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 23: ordinal not in range(128)
2019-03-16 21:23:32.411 T:32173   ERROR: PLEX.utils: _____________________________________________________________
2019-03-16 21:23:32.416 T:32173  NOTICE: PLEX.sync: ###===--- Sync Thread Stopped ---===###
2019-03-16 21:23:32.421 T:32173   ERROR: Exception in thread Thread-4:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 124, in run
                                                self._run_internal()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 200, in _run_internal
                                                self.start_library_sync(block=True)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 82, in start_library_sync
                                                library_sync.start(show_dialog, repair, self.on_library_scan_finished)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 451, in start
                                                FullSync(repair, callback, show_dialog).run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 404, in run
                                                self._run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 875, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/full_sync.py", line 413, in _run
                                                if not sections.sync_from_pms(self):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/sections.py", line 562, in sync_from_pms
                                                LOG.info('Done synching sections from the PMS: %s', SECTIONS)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 1174, in info
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 1293, in _log
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 1303, in handle
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 766, in handle
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/loghandler.py", line 49, in emit
                                                xbmc.log(try_encode(self.format(record)),
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 741, in format
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 465, in format
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/logging/__init__.py", line 329, in getMessage
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in position 23: ordinal not in range(128)
2019-03-16 21:23:33.124 T:32122   DEBUG: Version Check: Version installed {u'major': 18, u'tag': u'stable', u'minor': 1, u'revision': u'20190311-a456bde2ef'}
```

I wait to see if next update fixed it, but today PKC was updated and the problem persist.

u'\xfa' is a "ú" letter, that may be from "Música" library. But I'm not sure.

I will apreciate any help beacause now the full video library (wich doesn't contain a "ú" in it's name) is not synced.

Thank you very much.

Best regardas,
 Lukeid

**Comment by croneter** [comment]
Please share the entire log file

**Comment by Lukeid** [comment]
Here it is: [https://pastebin.com/0uhzssrv](https://pastebin.com/0uhzssrv)

Thank you very much.

**Comment by croneter** [comment]
Ouch, thanks very much for this bug report!!

**Comment by croneter** [comment]
Should be solved with stable and beta version 2.7.7. Let me know here if this is not the case.

**Comment by Lukeid** [comment]
Thank you very much for the fix and the software! :)

I'm glad I could help.

**Comment by Lukeid** [comment]
It is working with 2.7.7. :)
