### ISSUE TITLE
Encoding problem in syncing

### ISSUE THREAD

**Issue by pasine** [croneter/PlexKodiConnect#8]
I am getting an alert whenever I try to sync.
I checked the logs and this is what they show.

```
ERROR: PlexKodiConnect Items -> itemtypes.py for tv episode has crashed for item 1191. Error:
ERROR: PlexKodiConnect Items -> 'ascii' codec can't encode character u'\xe0' in position 83: ordinal not in range(128)
NOTICE: PlexKodiConnect Items -> Traceback:
                Traceback (most recent call last):
                File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/itemtypes.py", line 1191, in add_updateEpisode
                                                self.run_add_updateEpisode(item, viewtag, viewid)
                File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/itemtypes.py", line 1311, in run_add_updateEpisode
                                                playurl = API.getFilePath()
                File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/PlexAPI.py", line 1242, in getFilePath
                                                res = unquote(res).decode('utf-8')
                File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
                                                return codecs.utf_8_decode(input, errors, True)
                UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 83: ordinal not in range(128)
```

**Comment by croneter** [comment]
Thanks! Hope to fix this in the next release
