### ISSUE TITLE
Casting from iOS not working

### ISSUE THREAD

**Issue by thruster999** [croneter/PlexKodiConnect#945]
Hi

I’ve installed the latest beta (v2.9x) and can no longer cast from my iOS devices (to android devices). Kodi appears in the casting list but casting doesn’t work. 

I’ve re-installed v2.80 to get casting to work again. 

Thanks

**Comment by croneter** [comment]
Please enable Kodi DEBUG logging, restart Kodi, then try to cast from iOS. Then share you Kodi log according to https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

I don't have an iOS device, unfortunately... So can't test

**Comment by DomiStyle** [comment]
I have the same problem but on Android. Casting with 2.8.7 and below works, casting with 2.9.0 and above doesn't.

Here's the debug log:

    2019-07-31 19:41:51.298 T:3379475248   DEBUG: PLEX.listener: Serving GET request...
    2019-07-31 19:41:51.299 T:3379475248   DEBUG: PLEX.listener: remote request_path: player/playback/skipTo
    2019-07-31 19:41:51.300 T:3379475248   DEBUG: PLEX.listener: params received from remote: {u'X-Plex-Token': u'XXXX', u'includeExternalMedia': u'1', u'type': u'video', u'commandID': u'2', u'key': u'/library/metadata/486552'}
    2019-07-31 19:41:51.301 T:3379475248   DEBUG: PLEX.companion: Received request_path: player/playback/skipTo, params: {u'X-Plex-Token': u'XXXX', u'includeExternalMedia': u'1', u'type': u'video', u'commandID': u'2', u'key': u'/library/metadata/486552'}
    2019-07-31 19:41:51.302 T:3379475248   DEBUG: PLEX.companion: Skipping to playQueueItemID None, plex_id 486552
    2019-07-31 19:41:51.305 T:3843048240   DEBUG: DatabaseUtils::GetSortFieldList: unknown field 31
    2019-07-31 19:41:51.332 T:3851440944   DEBUG: GetAlbumsByWhereJSON query: SELECT a1.*, album_artist.idArtist AS idArtist, artist.strArtist AS strArtist FROM (SELECT albumview.idAlbum, strAlbum, strReview, strGenres, strThemes, strMoods, strStyles, strType, strLabel, fRating, iYear, strArtists, iTimesPlayed, art.url AS thumbnail FROM albumview LEFT JOIN art ON art.media_id = idAlbum AND art.media_type = 'album' AND art.type = 'thumb' WHERE albumview.strReleaseType = 'album' ORDER BY iTimesPlayed DESC, CASE WHEN CAST(strAlbum AS INTEGER) = 0 THEN 100000000 ELSE CAST(strAlbum AS INTEGER) END DESC, strAlbum COLLATE NOCASE DESC, CASE WHEN CAST(strArtists AS INTEGER) = 0 THEN 100000000 ELSE CAST(strArtists AS INTEGER) END DESC, strArtists COLLATE NOCASE DESC, albumview.idAlbum DESC LIMIT 20) AS a1 JOIN album_artist ON album_artist.idAlbum = a1.idAlbum JOIN artist ON artist.idArtist = album_artist.idArtist GROUP BY a1.idAlbum, album_artist.idArtist ORDER BY iTimesPlayed DESC, CASE WHEN CAST(strAlbum AS INTEGER) = 0 THEN 100000000 ELSE CAST(strAlbum AS INTEGER) END DESC, strAlbum COLLATE NOCASE DESC, CASE WHEN CAST(strArtists AS INTEGER) = 0 THEN 100000000 ELSE CAST(strArtists AS INTEGER) END DESC, strArtists COLLATE NOCASE DESC, a1.idAlbum DESC, album_artist.iOrder
    2019-07-31 19:41:51.334 T:3379475248   DEBUG: PLEX.listener: Serving GET request...
    2019-07-31 19:41:51.334 T:3851440944   DEBUG: GetAlbumsByWhereJSON - query took 3 ms
    2019-07-31 19:41:51.336 T:3379475248   DEBUG: PLEX.listener: remote request_path: player/playback/playMedia
    2019-07-31 19:41:51.337 T:3379475248   DEBUG: PLEX.listener: params received from remote: {u'includeExternalMedia': u'1', u'protocol': u'https', u'key': u'/library/metadata/486552', u'X-Plex-Token': u'XXXX', u'address': u'192-168-10-200.106f3ed17c5a4c869d19232b8c533ecb.plex.direct', u'commandID': u'3', u'token': u'transient-38642795-049e-4b1e-a2eb-708004552691', u'containerKey': u'/playQueues/19422?own=1&repeat=0&window=200', u'offset': u'0', u'machineIdentifier': u'8138d1b28443ec816188aea4f58fa6fc2a0b66aa', u'type': u'video', u'port': u'32400'}
    2019-07-31 19:41:51.337 T:3379475248   DEBUG: PLEX.companion: Received request_path: player/playback/playMedia, params: {u'includeExternalMedia': u'1', u'protocol': u'https', u'key': u'/library/metadata/486552', u'X-Plex-Token': u'XXXX', u'address': u'192-168-10-200.106f3ed17c5a4c869d19232b8c533ecb.plex.direct', u'commandID': u'3', u'token': u'transient-38642795-049e-4b1e-a2eb-708004552691', u'containerKey': u'/playQueues/19422?own=1&repeat=0&window=200', u'offset': u'0', u'machineIdentifier': u'8138d1b28443ec816188aea4f58fa6fc2a0b66aa', u'type': u'video', u'port': u'32400'}
    2019-07-31 19:41:51.363 T:3438949168   DEBUG: PLEX.plex_companion: Processing: {u'action': u'playlist', u'data': {u'includeExternalMedia': u'1', u'protocol': u'https', u'key': u'/library/metadata/486552', u'X-Plex-Token': u'XXXX', u'address': u'192-168-10-200.106f3ed17c5a4c869d19232b8c533ecb.plex.direct', u'commandID': u'3', u'token': u'transient-38642795-049e-4b1e-a2eb-708004552691', u'containerKey': u'/playQueues/19422?own=1&repeat=0&window=200', u'offset': u'0', u'machineIdentifier': u'8138d1b28443ec816188aea4f58fa6fc2a0b66aa', u'type': u'video', u'port': u'32400'}}
    2019-07-31 19:41:51.367 T:3438949168  NOTICE: PLEX.plex_companion: ----===## Plex Companion stopped ##===----
    2019-07-31 19:41:51.373 T:3438949168   ERROR: Exception in thread Thread-5:
                                                Traceback (most recent call last):
                                                File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_companion.py", line 256, in run
                                                    self._run()
                                                File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_companion.py", line 350, in _run
                                                    self._process_tasks(task)
                                                File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_companion.py", line 240, in _process_tasks
                                                    self._process_playlist(data)
                                                File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_companion.py", line 170, in _process_playlist
                                                    key=key)
                                                TypeError: update_playqueue_from_PMS() got an unexpected keyword argument 'key'
    2019-07-31 19:41:51.421 T:3843048240   DEBUG: DatabaseUtils::GetSortFieldList: unknown field 31
    2019-07-31 19:41:51.452 T:3851440944   DEBUG: Skin Widgets: Total time needed to request recommended queries: 0:00:11.609519
    2019-07-31 19:41:51.533 T:3422163760  NOTICE: PLEX.utils: It took 0:00:10.325197 to run the function playstate_per_section
    2019-07-31 19:41:51.534 T:3422163760   DEBUG: PLEX.sync.full_sync: Processing 81 playstates for library section {'index': 1, 'name': '   Movies (UHD)', 'section_id': 31, 'section_type': 'movie', 'sync_to_kodi': True, 'last_sync': 1564594814}
    2019-07-31 19:41:51.538 T:3843048240   DEBUG: DatabaseUtils::GetSortFieldList: unknown field 31
    2019-07-31 19:41:51.729 T:3438949168   DEBUG: Previous line repeats 1 times.
    2019-07-31 19:41:51.730 T:3438949168   DEBUG: Skin Helper Service --> Started Background worker...
    2019-07-31 19:41:51.736 T:3422163760  NOTICE: PLEX.utils: It took 0:00:00.202366 to run the function playstate_per_section

I'm running Kodi 18, playing something directly works just fine. I tried with direct paths and without but neither worked.

**Comment by croneter** [comment]
Share the entire debug log please!

**Comment by croneter** [comment]
Does PKC **BETA** version 2.9.2 help?

**Comment by DomiStyle** [comment]
Works for me now on Android. Thanks @croneter!

**Comment by thruster999** [comment]
Hi. Sorry. I’ve been away. I can create and send the logs still if needed.

How do I get hold of 2.9.2? I only have up until 2.9.1 in my update list.

Thanks

Paul


On Aug 2, 2019, at 3:38 AM, croneter <notifications@github.com<mailto:notifications@github.com>> wrote:


Does PKC BETA version 2.9.2 help?

**Comment by thruster999** [comment]
I found 2.92. Problem fixed.

Thank you!

Paul


On Aug 2, 2019, at 10:10 AM, Paul Mercia <paul_mercia@hotmail.com<mailto:paul_mercia@hotmail.com>> wrote:

Hi. Sorry. I’ve been away. I can create and send the logs still if needed.

How do I get hold of 2.9.2? I only have up until 2.9.1 in my update list.

Thanks

Paul


On Aug 2, 2019, at 3:38 AM, croneter <notifications@github.com<mailto:notifications@github.com>> wrote:


Does PKC BETA version 2.9.2 help?
